.TH IBUS-ENGINE-KEYMAN "1" "September 2023" "ibus-engine-keyman" "User Commands"
.SH NAME
ibus-engine-keyman \- multiple language input engine based on ibus
.SH DESCRIPTION
\&ibus\-engine\-keyman [options]
.TP
this command should run from ibus, don't run it directly.
.TP
\fB\-h\fR, \fB\-\-help\fR
show this message.
.TP
\fB\-x\fR, \fB\-\-xml\fR
generate XML listing all keyboards. This is used by ibus.
.TP
\fB\-i\fR, \fB\-\-ibus\fR
Component is executed by ibus
.TP
\fB\-\-testing\fR
Component is executed by integration tests.
.SS "example:"
.IP
\&./ibus\-engine\-keyman --ibus

.SH "SEE ALSO"
.BR ibus(1)
