/*
  Name:             keybd_shift
  Copyright:        Copyright (C) SIL International.
  Documentation:
  Description:
  Create Date:      11 Dec 2009

  Modified Date:    9 Aug 2015
  Authors:          mcdurdin
  Related Files:
  Dependencies:

  Bugs:
  Todo:
  Notes:
  History:          11 Dec 2009 - mcdurdin - I934 - x64 - Initial version
                    12 Mar 2010 - mcdurdin - I934 - x64 - Complete
                    12 Mar 2010 - mcdurdin - I2229 - Remove hints and warnings
                    31 Dec 2014 - mcdurdin - I4548 - V9.0 - When Alt is down, release of Ctrl, Shift is not detectable within TIP in some languages
                    09 Aug 2015 - mcdurdin - I4844 - Tidy up PostDummyKeyEvent calls
*/
#include "pch.h"
#include "kbd.h"

// The modifier VKs Keyman manages. Not the hook's accepted-VK set: isModifierKey takes nine VKs,
// which collapse onto these six. Do not unify them.
const BYTE KeymanModifierVks[KEYMAN_MODIFIER_VK_COUNT] = {
  VK_LMENU, VK_RMENU, VK_LCONTROL, VK_RCONTROL, VK_LSHIFT, VK_RSHIFT
};

/**
  do_keybd_event adds a keyboard event into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  This function mimics the keybd_event Windows API function, but instead of posting the event
  to the system keyboard event queue, it appends it to our internal event queue in pInputs.
  This allows us to send an atomic set of key events with SendInput.

  In this function, we map back the extended modifier keys. Now, the history of the PC keyboard
  means that this is a little weird. The original PC XT keyboard had Left and Right Shift keys,
  but only a single Ctrl and a single Alt key. This means, that the shift keys were each assigned
  their own scan code. However, Windows maps both keys to the same virtual key code (VK_SHIFT) for
  most purposes.

  When the Right Ctrl and Right Alt keys were introduced, they were differentiated from the original
  keys not by separate scan codes, but by an extended prefix byte (E0), together with the original
  scan code. Again, Windows does not differentiate with virtual keys (VK_CONTROL and VK_MENU).

  This means, to check for Left vs Right Shift, you need to test the scan code (2A and 36)
  respectively. However, to test for Left vs Right Ctrl/Alt, you need to test the Extended bit in
  the flags for the message.

  There are a few places where VK_LSHIFT, VK_RSHIFT, VK_LCONTROL, VK_RCONTROL, VK_LMENU, and
  VK_RMENU can be used, such as GetKeyState or MapVirtualKey. However, these virtual key codes
  should never be emitted and will never be received as a key event.

  To add an additional wrinkle to an already wrinkly story, Keyman (ab)uses the scan code property
  of key events to identify key events that it has synthesized, as opposed to those generated by
  the user or by another app (e.g. Remote Desktop scenarios). Instead of using the correct scan
  code, it will stuff the key event with a 0xFF scan code, and replace that in its GetMessage
  so the end application gets a look at the correct scan code. However, this will obviously not
  work with Right Shift, which is differentiated from Left Shift _only_ by scan code. Fortunately,
  we can afford to not care about this -- it means a little extra flag setting behind the scenes
  as the right shift key is released and re-pressed during key events, but nothing too dramatic.
*/
void do_keybd_event(LPINPUT pInputs, int *n, BYTE vk, BYTE scan, DWORD flags, ULONG_PTR extraInfo) {   // I4548
  INPUT input;
  input.type = INPUT_KEYBOARD;

  switch(vk) {
  case VK_RCONTROL:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LCONTROL:
    vk = VK_CONTROL;
    break;

  case VK_RMENU:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LMENU:
    vk = VK_MENU;
    break;

  case VK_RSHIFT:
    scan = SCANCODE_RSHIFT; // from kbd.h
    /*fallthrough*/
  case VK_LSHIFT:
    vk = VK_SHIFT;
    break;
  }

  input.ki.wVk = vk;
  input.ki.wScan = scan;
  input.ki.dwFlags = flags;
  input.ki.time = 0;
  input.ki.dwExtraInfo = extraInfo;
  SendDebugMessageFormat("n=%d, vk=%s, scan=%x, flags=%x", *n, Debug_VirtualKey(vk), scan, flags);

  pInputs[*n] = input;
  (*n)++;
}

/**
  keybd_sendprefix pushes a dummy keystroke into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  The keybd_sendprefix call is needed, for example, if the user presses Alt+F which matches a rule
  in the current Keyman keyboard, because without the dummy prefix key, faking the release of the
  Alt key will activate the mainmenu of the current application.
*/
void keybd_sendprefix(LPINPUT pInputs, int *n)
{
  SendDebugEntry();
  //SendDebugMessageFormat("sending prefix down+up");
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, 0, 0);   // I4548   // I4844
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, 0);   // I4548   // I4844
  SendDebugExit();
}

/**
  keybd_shift_release records the current keyboard state and then releases any modifier
  keys. If a modifier key must be released, it first sends a dummy prefix key to prevent
  isolated modifier key actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), in which we will store
                       the initial modifier state for later restoration by keybd_shift_reset
              sendPrefix  FALSE suppresses the dummy prefix keystroke. #8064 FR-014: the prefix
                       exists for ONE reason -- an isolated Alt release opens the window menu -- and
                       inside a batch it costs nothing, because it lands between the keyboard's own
                       output keys. A STANDALONE correction is different: it is a separate SendInput
                       fired from a posted message, so its prefix lands in whatever has focus by
                       then, and the prefix VK is registry-overridable (REGSZ_ZapVirtualKeyCode,
                       k32_globals.cpp:378) so it cannot be assumed unassigned. Defaulted TRUE so
                       the batch path is untouched; only PrepareModifierVerificationCorrection
                       passes FALSE, and only when no Alt is in the set
*/
void keybd_shift_release(LPINPUT pInputs, int *n, LPBYTE const kbd, BOOL sendPrefix = TRUE) {
  BOOL hasSentPrefix = FALSE;

  SendDebugEntry();
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      if (!hasSentPrefix && sendPrefix) {
        keybd_sendprefix(pInputs, n);
        hasSentPrefix = TRUE;
      }
      SendDebugMessageFormat("sending keyup vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP);
    }
  }
  SendDebugExit();
}

/**
  keybd_shift_reset returns the modifiers to their original pressed state and, if any modifier
  key presses are emitted, emits also a dummy 'prefix' keystroke in order to prevent default
  modifier actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), previously set by
                       keybd_shift_release
              pPressIndex  optional out; KEYMAN_MODIFIER_VK_COUNT ints, one per slot of
                       KeymanModifierVks, set to the pInputs index of that modifier's KEYDOWN, or
                       left at -1 where none was emitted. #8064 FR-015b: the caller needs to know
                       WHERE each restore press went, so that a short SendInput can be reconciled
                       exactly. Recorded here, at the point of emission, rather than reconstructed
                       by the caller -- a caller that recomputed the layout would be duplicating
                       this loop's ordering and would drift from it silently
*/
void keybd_shift_reset(LPINPUT pInputs, int *n, LPBYTE const kbd, int *pPressIndex = NULL) {
  BOOL needsPrefix = FALSE;

  SendDebugEntry();
  if (pPressIndex != NULL) {
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      pPressIndex[i] = -1;
    }
  }

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      SendDebugMessageFormat("sending keydown vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      if (pPressIndex != NULL) {
        pPressIndex[i] = *n; // the slot this KEYDOWN is about to occupy
      }
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, 0, EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP);
      needsPrefix = TRUE;
    }
  }

  if (needsPrefix) {
    keybd_sendprefix(pInputs, n);
  }
  SendDebugExit();
}

/**
  keybd_shift evaluates the current keyboard modifier state and queues key events in order to
  initially set modifiers to "up" and, after the output key events are queued, resets the modifiers
  to their initial state.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              isReset  are we clearing or resetting the modifier state?
              kbd      pointer to keyboard state (256 byte array) that owner must maintain but
                       that we will fill

  There must be enough space in pInputs to contain 6 x up + 6 x down + 2 prefix-down + 2 prefix-up event = 16 events,
  to support both the clear and reset calls.
*/
void keybd_shift(LPINPUT pInputs, int *n, BOOL isReset, LPBYTE const kbd, int *pPressIndex) {
  if (isReset) {
    keybd_shift_reset(pInputs, n, kbd, pPressIndex);
  } else {
    // Nothing to report for the release direction: the release half emits KEYUPs, and it is the
    // restore PRESSES that a short send drops.
    keybd_shift_release(pInputs, n, kbd);
  }
}


/**
  CaptureLiveModifierState takes one reading per managed modifier into liveOut.

  Parameters: liveOut              256 bytes, 0x80 for each modifier the OS reports held
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  One acquisition point per batch, so the reconcile and the release set cannot disagree about what
  was held. GetAsyncKeyState, not GetKeyState/GetKeyboardState: those read the calling thread's
  processed queue, the stale source.

  Not widened to the generic VK_SHIFT/CONTROL/MENU isModifierKey also accepts -- GetAsyncKeyState
  reports the chiral halves even for a generic injection. Measured rather than assumed:
  GenericShiftSendInputReflectsInBothAsyncKeyStates injects a generic wVk with scan 0 and reads back
  the chiral half, and the recorded run is in the GH-8064 manual test's evidence directory.

  That test is also the trip-wire, so this is what trips it: if it ever reports VK_LSHIFT and
  VK_RSHIFT both up while VK_SHIFT reads down, widen this to OR the generic reading into both chiral
  halves when neither already reports held. Safe in that direction -- over-reporting live state can
  only add a release or a reconcile-clear, never the unmatched KEYDOWN of #8064 -- but deliberately
  not added ahead of the need: it costs three more reader calls every batch and breaks the
  one-reading-per-managed-modifier invariant BatchTakesOneLiveReadingPerManagedModifier pins.
*/
void CaptureLiveModifierState(LPBYTE liveOut, PGETASYNCKEYSTATE pfnGetAsyncKeyState) {
  // Zeroed in full: no caller stack residue is mistaken for a held modifier.
  memset(liveOut, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (pfnGetAsyncKeyState(KeymanModifierVks[i]) < 0) {
      liveOut[KeymanModifierVks[i]] = 0x80;
    }
  }
}

/**
  ReconcileModifierCache clears any modifier the cache reports held while the live state reports it
  up. Returns TRUE if the two disagreed.

  Parameters: kbd   the modifier cache (256 byte array), reconciled in place
              live  the live snapshot from CaptureLiveModifierState. Read, never written

  A dropped modifier KEYUP otherwise leaves that byte set for the life of the process, and
  keybd_shift_reset presses the modifier for real (#8064). Clears but never sets: the user may
  release before SendInput runs.
*/
BOOL ReconcileModifierCache(LPBYTE const kbd, LPBYTE const live) {
  BOOL disagreed = FALSE;

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    const BYTE vk = KeymanModifierVks[i];
    if ((kbd[vk] & 0x80) && !(live[vk] & 0x80)) {
      SendDebugMessageFormat("cache says held but OS says up, clearing vkey=%s", Debug_VirtualKey(vk));
      kbd[vk] = 0;
      disagreed = TRUE;
    }
  }

  return disagreed;
}

/**
  PrepareInjectedInputBatch assembles one injected batch into pInputs and returns the event count:
  release half, output keys, restore half.

  Parameters: pInputs              at least MAX_KEYEVENT_INPUTS INPUT structures
              kbd                  the modifier cache (256 bytes), reconciled in place
              pSharedData          the output keys to wrap; nInputs is clamped here
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState
              feedIsConfigured     FALSE degrades the release set to the cache alone; see below
              pRestorePressedMask  optional out; bitmask over KeymanModifierVks of what the restore
                                   half pressed, scoping PrepareModifierVerificationCorrection
              pfnDiagnostic        optional; called for each hold this batch cannot keep. See
                                   ModifierDiagnosticCode in serialkeyeventcommon.h. NULL means no
                                   reporting and changes no behaviour -- nothing here decides
                                   anything on whether a diagnostic sink is bound
              pUserHeld            optional; the user-held signal. NULL means no signal and the
                                   restore half falls back to the cache alone, which is FR-104's
                                   fallback and the shape if US0 is struck. See
                                   UserHeldModifierSignal in serialkeyeventcommon.h
              pRestoreEventIndex   optional out; KEYMAN_MODIFIER_VK_COUNT ints, one per bit of
                                   pRestorePressedMask, giving the BUFFER INDEX of the restore
                                   KEYDOWN that bit stands for, or -1 where the bit is clear.
                                   #8064 FR-015b: SendInput can send fewer events than it was
                                   given, and the events it drops are the tail -- which is exactly
                                   where the restore presses are. A caller that knows the index of
                                   each press can clear precisely the bits whose press did not go
                                   out, and leave the rest. Clearing the whole mask on any short
                                   send would suppress the verification pass for presses that DID
                                   land, which is a second dropped hold rather than a fix for the
                                   first

  A free function so the gtest project can reach it; serialkeyeventserver.cpp is #ifndef _WIN64.
  The output-key copy stops MAX_KEYEVENT_INPUTS_MODIFIERS short of the end so the restore half
  fits: the worst case fills the buffer exactly, so an off-by-one is a heap overrun.

  feedIsConfigured mirrors flag_ShouldSerializeInput, which gates the hook's cache feed. With the
  feed off, kbd never updates after its launch seed, so a release the live state adds could never be
  balanced by a later restore, which reads kbd. Passing kbd keeps both halves reading the same stale
  state.
  The name is exact and the distinction matters: it says the feed is configured, never that the feed
  is working. See the declaration in serialkeyeventcommon.h.
*/
int PrepareInjectedInputBatch(
  LPINPUT pInputs,
  LPBYTE const kbd,
  const SerialKeyEventSharedData *pSharedData,
  PGETASYNCKEYSTATE pfnGetAsyncKeyState,
  BOOL feedIsConfigured,
  DWORD *pRestorePressedMask,
  PMODIFIERDIAGNOSTIC pfnDiagnostic,
  int *pRestoreEventIndex,
  const UserHeldModifierSignal *pUserHeld) {
  DWORD nInputs = min(pSharedData->nInputs, MAX_KEYEVENT_INPUTS);
  int n         = 0;

  // TRANSIENT, and it will be gone in the next commit: the seam exists and nothing emits through it
  // yet, which is what makes the FR-002 and FR-006 cases in keybd_shift.tests.cpp genuinely red.
  // keyman32.vcxproj builds with warnings as errors (C2220), so an unreferenced parameter cannot be
  // left to sit even for one commit.
  BYTE live[256];
  CaptureLiveModifierState(live, pfnGetAsyncKeyState);

  // #8064 FR-006 / FR-007. BEFORE the reconcile, because the reconcile is about to clear the very
  // bytes this reads. Every managed modifier reading up live while the cache claims two or more
  // held is the shape a desktop switch leaves: the user held two modifiers, released them somewhere
  // the feed could not see -- the secure desktop, a console window -- and came back. The reconcile
  // will clear both, the release half will release nothing, the restore half will press nothing,
  // and cache and OS will agree perfectly afterwards. ReconcileModifierCache is structurally blind
  // to that forever: it tests for cache-up-and-live-down, and this state IS cache-up-and-live-down.
  // It is doing its job. The only thing that can be added is that somebody is told.
  //
  // TWO OR MORE, not one, and the threshold is the load-bearing half of the requirement. Exactly
  // one modifier held at launch and released before the feed was live is the ordinary launch-seed
  // case 002's reconcile exists to clear; firing there would put a warning in the log on a normal
  // session, and a diagnostic that cries wolf is one nobody reads when it matters.
  if (pfnDiagnostic != NULL) {
    int liveHeld = 0, cacheClaimed = 0;
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      if (live[KeymanModifierVks[i]] & 0x80) {
        liveHeld++;
      }
      if (kbd[KeymanModifierVks[i]] & 0x80) {
        cacheClaimed++;
      }
    }
    if (liveHeld == 0 && cacheClaimed >= 2) {
      // Once per batch, vk = 0: this is a statement about the batch, not about a key. Which keys
      // were lost is in ReconcileModifierCache's own per-VK clearing lines, logged immediately
      // below for exactly this set.
      pfnDiagnostic(PossibleDesktopSwitch, 0);
    }
  }

  // Clear before keybd_shift below presses it for real (#8064). Only ever clears, so this stays
  // safe when !feedIsConfigured.
  //
  // #8064 FR-007a, A STANDING INVARIANT AND NOT A COMMENT ABOUT TODAY'S CODE: any mechanism that
  // suppresses this reconcile MUST also suppress this batch's restore half. The restore half reads
  // the very bytes the reconcile would have cleared, so leaving the reconcile out while leaving the
  // restore in presses a modifier nobody is holding. An earlier draft did exactly that -- skip the
  // reconcile when the state looks like a desktop switch -- and it reintroduced #8064 with cache
  // and OS AGREEING, which is the one state ReconcileModifierCache can never detect, because the
  // verification pass tests for cache-up-and-live-down and this is its opposite.
  //
  // The guard above is therefore a REPORT and never a suppression: it emits and returns, and causes
  // no press that would not otherwise be emitted. Losing a hold is the accepted direction here
  // (FR-001, FR-004); manufacturing a press is never one.
  ReconcileModifierCache(kbd, live);

  // #8064 FR-002. The release set is live, the restore set is kbd, so a modifier the OS holds that
  // the cache does not claim is released here and never pressed back -- a hold this batch drops.
  // That is correct and stays: releasing on the cache alone reopens 002/FR-001's silent text
  // destruction via Ctrl+Backspace. What FR-002 adds is that it stops happening in silence, so a
  // user reporting "my Ctrl went dead" has something in the log to match.
  //
  // Guarded on feedIsConfigured because with the feed off both halves read the same kbd, so the
  // condition cannot arise and reporting it would be a lie about every degraded batch.
  if (pfnDiagnostic != NULL && feedIsConfigured) {
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      const BYTE vk = KeymanModifierVks[i];
      if ((live[vk] & 0x80) && !(kbd[vk] & 0x80)) {
        pfnDiagnostic(ReleasedWithoutCacheClaim, vk);
      }
    }
  }

  // Post-reconcile kbd is a subset of live, so their union IS live -- both sets confined to the same
  // managed six, so there is no index at which they can differ. Pinned by
  // ReconcileLeavesTheCacheASubsetOfLiveState -- delete that test and this line is a guess again.
  // The !feedIsConfigured arm passes kbd instead; see feedIsConfigured above.
  keybd_shift(pInputs, &n, FALSE, feedIsConfigured ? live : kbd);

  for (DWORD i = 0; i < nInputs && n < MAX_KEYEVENT_INPUTS - MAX_KEYEVENT_INPUTS_MODIFIERS; i++, n++) {
    pInputs[n].type           = INPUT_KEYBOARD;
    pInputs[n].ki.wVk         = pSharedData->inputs[i].wVk;
    pInputs[n].ki.wScan       = pSharedData->inputs[i].wScan;
    pInputs[n].ki.dwFlags     = pSharedData->inputs[i].dwFlags;
    pInputs[n].ki.time        = pSharedData->inputs[i].time;
    pInputs[n].ki.dwExtraInfo = (ULONG_PTR)pSharedData->inputs[i].extraInfo;
  }

  // #8064 FR-101. The restore set is `kbd OR (pUserHeld->held & ~pUserHeld->unknown)`.
  //
  // NOT live, and that exclusion is the requirement, not an implementation detail: live OS state
  // reports the same value for "the user is holding it" and "we pressed it ourselves one message
  // ago", so restoring from it manufactures unmatched presses -- #8064 from a new direction, and on
  // hardware with no physical Right Ctrl the user cannot clear it at all. FR-102.
  //
  // The signal is admissible where live state is not, because it reports what a NON-KEYMAN source
  // observed, and reports *unknown* rather than stale when it cannot observe. It only ever WIDENS
  // what the cache already justifies; it can add a press the cache missed, never veto one the cache
  // asserts. NULL means no signal and the cache alone -- FR-104's fallback, and the shape if US0 is
  // struck.
  //
  // kbd itself is not modified. The cache records what Keyman's feed saw and nothing here may
  // rewrite that; the widening lives in a local so the two sources stay distinguishable.
  BYTE restoreSet[256];
  memcpy(restoreSet, kbd, sizeof(restoreSet));

  if (pUserHeld != NULL) {
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      const BYTE vk = KeymanModifierVks[i];
      // held & ~unknown, the effective read, everywhere. Reading held alone is the bug this whole
      // structure exists to make impossible to write by accident.
      if ((pUserHeld->held[vk] & 0x80) && !(pUserHeld->unknown[vk] & 0x80)) {
        restoreSet[vk] = 0x80;
      }
    }
  }

  // No reconcile against live here -- mid-batch OS state is Keyman's own doing, not ground truth.
  //
  // #8064 FR-015b: keybd_shift_reset records where it put each press, at the point of emission. The
  // caller needs that to reconcile a short SendInput exactly; see pRestoreEventIndex above.
  keybd_shift(pInputs, &n, TRUE, restoreSet, pRestoreEventIndex);

  // #8064 FR-103. Built from restoreSet and NOT from kbd, so it covers the presses FR-101 added.
  // Those are the presses most likely to race a user release, because they are made about a key the
  // user is actively holding -- and a press the mask omits can never be corrected, since the
  // verification pass is scoped by it.
  if (pRestorePressedMask != NULL) {
    DWORD mask = 0;
    for (int i = 0; i < _countof(KeymanModifierVks); i++) {
      if (restoreSet[KeymanModifierVks[i]] & 0x80) {
        mask |= (1u << i);
      }
    }
    *pRestorePressedMask = mask;
  }

  return n;
}

/**
  PrepareModifierVerificationCorrection releases modifiers the OS still holds that the cache says
  nobody holds: a batch's restore press can outlive a user release that raced it, and
  ReconcileModifierCache only catches that on the *next* batch, which may never arrive.

  Parameters: pInputs              at least MAX_KEYEVENT_INPUTS_MODIFIERS INPUT structures
              kbd                  the modifier cache, read only. The CURRENT cache, not a snapshot
                                   from when the batch was built -- see
                                   WM_KEYMAN_VERIFY_MODIFIER_EVENT for why that is safe here
              restorePressedMask   PrepareInjectedInputBatch's out-param, via the verify message's
                                   wParam. Scopes the check to the VKs that batch touched; any
                                   other disagreement belongs to some other batch
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  Emitted through keybd_shift_release for its Keyman tagging, which keeps the correction out of the
  cache, and for its prefix protection -- but the prefix is now CONDITIONAL (#8064 FR-014 / A8).

  The prefix exists for one reason: an isolated Alt release opens the window menu. Inside a batch it
  is free, because it lands between the keyboard's own output keys. This correction is not inside a
  batch: it is a separate SendInput fired from a posted message some time after the batch's own send
  returned, into whatever has focus BY THEN. So a prefix down/up pair here lands in the user's
  document, or in a control with its own idea of what that key means -- and the prefix VK is
  registry-overridable (REGSZ_ZapVirtualKeyCode, k32_globals.cpp:378), so it cannot be assumed
  unassigned on every machine.

  So the prefix is sent only when an Alt-family VK is in the correction set, which is the case it was
  written for. A correction releasing only Shift or only Ctrl needs no protection from a menu that
  cannot open, and sends nothing extra.

  Known false positive: a fresh user KEYDOWN posted after the verify message is still queued behind
  it, so this can release a hold that has become genuine again. Accepted -- an unmatched KEYUP is
  re-pressable, an unmatched KEYDOWN on hardware with no physical Right Ctrl is not.

  It cannot fire on the serialized path: there the hook eats the user KEYDOWN, and only the server's
  re-injection reaches the OS, from the same handler that writes the cache, so live state never
  leads it. It fires only where the hook passes the event through -- console focus, touch panel
  visible, and the handoff-failure fallback, all at k32_lowlevelkeyboardhook.cpp:248-292 -- where
  the OS applies the KEYDOWN at once while the cache feed is still queued behind the verify.

  Rejected: widening this to also *set* cache bytes so that false positive cannot arise. That
  reintroduces the unmatched KEYDOWN from a third direction, and it breaks ReconcileModifierCache's
  clears-but-never-sets rule, which this deliberately mirrors.
*/
int PrepareModifierVerificationCorrection(
  LPINPUT pInputs,
  LPBYTE const kbd,
  DWORD restorePressedMask,
  PGETASYNCKEYSTATE pfnGetAsyncKeyState,
  const UserHeldModifierSignal *pUserHeld) {
  int n = 0;

  BYTE live[256];
  CaptureLiveModifierState(live, pfnGetAsyncKeyState);

  BYTE correction[256];
  memset(correction, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (!(restorePressedMask & (1u << i))) {
      continue; // outside the set this batch touched -- not this verification's problem
    }
    const BYTE vk = KeymanModifierVks[i];

    // #8064 FR-103a. THE PAIRING THAT IS THE WHOLE DIFFERENCE BETWEEN US0 DELIVERING AND US0
    // DELIVERING NOTHING. This pass corrects on cache-up-and-live-down, and that is EXACTLY the
    // state every FR-101 restore creates whenever the cache is blind -- which, inside the A0
    // window, is always. Widening the mask (FR-103) without this check would release the modifier
    // one message after the restore pressed it, reproducing the very no-op the signal was
    // introduced to escape, at a cost of two injected events per batch.
    //
    // So: never correct a VK the signal reports the user still holds. Same effective read as the
    // restore half, held & ~unknown, or the two halves would disagree about the same key.
    if (pUserHeld != NULL && (pUserHeld->held[vk] & 0x80) && !(pUserHeld->unknown[vk] & 0x80)) {
      SendDebugMessageFormat(
        "verification: declining to correct vkey=%s -- the user-held signal reports the user is "
        "still holding it, and this batch pressed it on that word",
        Debug_VirtualKey(vk));
      continue;
    }

    if (!(kbd[vk] & 0x80) && (live[vk] & 0x80)) {
      SendDebugMessageFormat("verification: OS holds vkey=%s that the cache says nobody holds, correcting", Debug_VirtualKey(vk));
      correction[vk] = 0x80;
    }
  }

  // FR-014: ANY Alt in the set, not just the first VK in it -- Shift sorts before Alt in
  // KeymanModifierVks, so a first-VK check would suppress the prefix on a Shift+Alt correction,
  // which is exactly the case that needs it.
  const BOOL hasAlt = (correction[VK_LMENU] & 0x80) || (correction[VK_RMENU] & 0x80);

  keybd_shift_release(pInputs, &n, correction, hasAlt);

  return n;
}

/**
  UpdateModifierCacheFromKeyEvent applies one modifier key event to the cache, collapsing the
  hook's VKs onto the chiral pair the cache is keyed by.

  Parameters: kbd              the modifier cache (256 bytes), updated in place
              bVk              the event's virtual key as the hook reported it
              fIsExtendedKey   the event's KEYEVENTF_EXTENDEDKEY flag
              bScan            the event's scan code; for VK_SHIFT this is the only chirality signal
              fIsUp            TRUE for a KEYUP

  Applies every modifier event the hook posts, Keyman's own included -- the post precedes the
  "generated by Keyman" pass-through -- so this is not a record of what the user physically holds.
  A balanced batch nets out; see KeymanOwnRestorePressOutlivesTheUsersRealRelease for the cost when
  a real user event interleaves.
*/
void UpdateModifierCacheFromKeyEvent(LPBYTE kbd, BYTE bVk, BOOL fIsExtendedKey, BYTE bScan, BOOL fIsUp) {
  switch (bVk) {
  case VK_CONTROL:
    // Left and right control are distinguished by a 0xE0 prefix byte
    bVk = fIsExtendedKey ? VK_RCONTROL : VK_LCONTROL;
    break;
  case VK_MENU:
    // Left and right alt are distinguished by a 0xE0 prefix byte
    bVk = fIsExtendedKey ? VK_RMENU : VK_LMENU;
    break;
  case VK_SHIFT:
    // Left and right shift are distinguished by scan code alone
    bVk = bScan == SCANCODE_RSHIFT ? VK_RSHIFT : VK_LSHIFT;
    break;
  case VK_LCONTROL:
  case VK_RCONTROL:
  case VK_LSHIFT:
  case VK_RSHIFT:
  case VK_LMENU:
  case VK_RMENU:
    // These are technically not needed but perhaps some app will send them through SendInput
    // and we'll have to deal with them?
    break;
  default:
    return;
  }

  kbd[bVk] = fIsUp ? 0 : 0x80;
}

/**
  #8064 W5 / FR-100a, FR-101, FR-104a. Applies one RAW KEYBOARD event to the user-held signal.

  Parameters: pSignal          the signal, updated in place
              vkey             RAWKEYBOARD::VKey
              makeCode         RAWKEYBOARD::MakeCode -- for VK_SHIFT the only chirality signal
              rawFlags         RAWKEYBOARD::Flags: RI_KEY_BREAK, RI_KEY_E0, RI_KEY_E1
              extraInformation RAWKEYBOARD::ExtraInformation

  THE DISCRIMINATOR IS "NOT KEYMAN'S OWN", AND "NOT INJECTED" IS A REFUTED ONE (I-U1). This applies
  the event unless IsKeymanInjectedKeyEvent says it is ours -- the same policy, byte for byte, as
  the hook's own cache-feed gate. It is NOT a test for injection, and the difference is the entire
  reason this signal is worth having:

    - Remote Desktop delivers genuine user keystrokes as OS-injected events (extraInfo 0x4321DCBA).
    - The Keyman OSK delivers genuine user clicks as OS-injected events.

  Both are the user, and both must reach the signal, or a hold made over RDP is one the restore half
  will drop. IsKeymanInjectedKeyEventTests carries regression guards for both populations. The
  function deliberately does NOT take hDevice, so the refuted device-identity policy is not even
  expressible here -- and the W0 probe recorded that hDevice is unusable for this anyway.

  Chirality is derived exactly as UpdateModifierCacheFromKeyEvent derives it, because both write a
  256-byte array keyed by the chiral VK and a disagreement between them would be silent: RI_KEY_E0
  for Control and Alt, MakeCode for Shift.

  A KEYUP writes held = 0 and a KEYDOWN writes held = 0x80. EITHER WAY unknown is cleared: a fresh
  observation of a key is the only thing that clears its poison (I-U3), and an observation is
  exactly what this is.
*/
void UpdateUserHeldFromRawKeyboard(
  UserHeldModifierSignal *pSignal,
  USHORT vkey, USHORT makeCode, USHORT rawFlags, ULONG extraInformation) {
  if (pSignal == NULL) {
    return;
  }

  // Keyman's own events are not evidence about what the user is holding. Same gate as the hook's.
  if (IsKeymanInjectedKeyEvent(makeCode, (ULONG_PTR)extraInformation)) {
    return;
  }

  const BOOL isExtended = (rawFlags & RI_KEY_E0) != 0;
  const BOOL isUp       = (rawFlags & RI_KEY_BREAK) != 0;

  BYTE vk = (BYTE)vkey;
  switch (vk) {
  case VK_CONTROL:
    vk = isExtended ? VK_RCONTROL : VK_LCONTROL;
    break;
  case VK_MENU:
    vk = isExtended ? VK_RMENU : VK_LMENU;
    break;
  case VK_SHIFT:
    vk = makeCode == SCANCODE_RSHIFT ? VK_RSHIFT : VK_LSHIFT;
    break;
  case VK_LCONTROL:
  case VK_RCONTROL:
  case VK_LSHIFT:
  case VK_RSHIFT:
  case VK_LMENU:
  case VK_RMENU:
    break;
  default:
    return; // nothing outside the managed six is written
  }

  pSignal->held[vk]    = isUp ? 0 : 0x80;
  pSignal->unknown[vk] = 0; // a fresh observation, so this key is knowable again
}

/**
  #8064 W5 / FR-104, FR-104a. Marks the named keys as ones the signal cannot currently speak for.

  PER KEY, AND CLEARED ONLY BY A FRESH OBSERVATION OF THAT KEY -- never on a timer (I-U3). A timer
  would decide a key is knowable again because time passed, which is precisely the reasoning that
  makes a stale shadow dangerous: the UAC case is a user who held Ctrl, released it on the secure
  desktop where nothing could see it, and came back. No amount of elapsed time makes the last
  observation true again; only a new observation does.

  held is left untouched. The effective read is held & ~unknown everywhere, so poisoning suppresses
  the claim without destroying it, and one real event restores the key to service.
*/
void PoisonUserHeldKeys(UserHeldModifierSignal *pSignal, LPBYTE const vks, int count) {
  if (pSignal == NULL || vks == NULL) {
    return;
  }
  for (int i = 0; i < count; i++) {
    pSignal->unknown[vks[i]] = 0x80;
  }
}

/**
  #8064 W5 / FR-104b. Poisons every managed modifier at once.

  The whole-signal case: the feed is not established yet, the active desktop is not the user's, the
  session changed, or the raw-input registration was displaced. In each of those the signal has no
  standing to speak about ANY key, so saying so about all six is the honest answer rather than an
  abundance of caution.
*/
void PoisonAllUserHeldKeys(UserHeldModifierSignal *pSignal) {
  if (pSignal == NULL) {
    return;
  }
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    pSignal->unknown[KeymanModifierVks[i]] = 0x80;
  }
}

/**
  IsKeymanInjectedKeyEvent reports whether a key event the hook received was injected by Keyman
  rather than produced by the user's keyboard.

  Parameters: scanCode   the event's scan code as the hook reported it
              extraInfo  the event's dwExtraInfo as the hook reported it

  Two arms; neither covers the managed set alone. SCAN_FLAG_KEYMAN_KEY_EVENT catches everything
  injected with the 0xFF scan overload, including the five direct keybd_event call sites
  (keyman32.cpp:924-925, kmhook_keyboard.cpp:147, kmprocessactions.cpp:101-102), which carry no tag
  in dwExtraInfo -- keybd_event's fourth parameter, which all five already pass, as 0.
  EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP catches Right Shift, whose 0xFF scan do_keybd_event overwrites
  with SCANCODE_RSHIFT so the receiving app can tell which Shift it was.

  Equality on the tag, never extraInfo != 0: mstsc stamps 0x4321DCBA on genuine remote user input,
  which the next batch would then strip. Not EXTRAINFO_FLAG_SERIALIZED_USER_KEY_EVENT either --
  those are real user keystrokes the server already applies to the cache. Not LLKHF_INJECTED: the
  OSK sets it too, and an OSK sticky modifier is meant to be real machine-wide (#8064).
*/
BOOL IsKeymanInjectedKeyEvent(DWORD scanCode, ULONG_PTR extraInfo) {
  return scanCode == SCAN_FLAG_KEYMAN_KEY_EVENT || extraInfo == EXTRAINFO_FLAG_KEYMAN_MODIFIER_WRAP;
}

/**
  ShouldFeedModifierCache decides whether a modifier key event the hook received belongs in the
  serializer's modifier cache.

  Parameters: serializeInput  the hook's flag_ShouldSerializeInput, read at the call site
              scanCode        the event's scan code, raw, exactly as the hook reported it
              extraInfo       the event's dwExtraInfo, raw, exactly as the hook reported it

  Keyman's own injected modifiers must not feed the cache: a batch's restore press can outlive the
  user's release, leaving the cache holding a modifier nobody holds -- undetectable by the reconcile,
  because the OS agrees (#8064). Callers pass the raw scan code and dwExtraInfo, before any
  normalisation, and must keep the call ahead of the "generated by Keyman" pass-through check: the
  post precedes that check on purpose, so modifiers are tracked with no Keyman keyboard active.

  Pure by design. No globals, no hook state, no logging -- the hook keeps ownership of the server
  lookup, the PostMessage and every SendDebugMessageFormat around it, and this function owns only
  the decision. That is what makes it reachable from keyman32.tests.vcxproj, which cannot link
  k32_lowlevelkeyboardhook.cpp at all: it is entirely inside #ifndef _WIN64.

  This function exists because the suite used to mirror it. Deleting the !IsKeymanInjectedKeyEvent
  term from the hook left all 68 tests green, because the two cases billed "this is the fix for
  #8064" ran against keybd_shift.tests.cpp's own ApplyThroughTheGate helper and never reached
  production code. Do not reintroduce a mirror; call this.
*/
BOOL ShouldFeedModifierCache(BOOL serializeInput, DWORD scanCode, ULONG_PTR extraInfo) {
  return serializeInput && !IsKeymanInjectedKeyEvent(scanCode, extraInfo);
}

/**
  PostKeyEventAndDecideEat hands a key event to the serial key event server and reports whether the
  hook should eat it.

  Parameters: hwndServer  the serializer's window, or NULL if there is no server to hand off to
              vkCode      the event's virtual key, posted as wParam
              flags       the event's flags, posted as lParam; the caller has already converted them
                          with LLKHFFlagstoWMKeymanKeyEventFlags
              pfnPost     the post seam; production passes PostMessage, the suite a stub

  Returns TRUE only when the handoff actually succeeded, which is the whole point. Eating on trust
  destroys the user's key event whenever PostMessage fails, and for a modifier KEYUP that is how
  #8064 re-asserts: the OS stays latched, the cache still says down, and the clear-only reconcile can
  never see it. Unserialized beats destroyed.

  A NULL hwndServer is a real route, not defensive padding: PostMessage to a NULL hwnd does not
  fail, it misroutes to the calling thread's own queue, so the handoff is silently destroyed while
  the return value says it worked. Checked here, before the post is attempted.

  No logging inside -- the hook logs around the call, as it does today -- and no re-implementation of
  the caller's pass-through, touch-panel or console checks, which run before this is reached.
*/
BOOL PostKeyEventAndDecideEat(HWND hwndServer, DWORD vkCode, DWORD flags, PPOSTMESSAGEFN pfnPost) {
  if (hwndServer == NULL) {
    return FALSE;
  }

  return pfnPost(hwndServer, WM_KEYMAN_KEY_EVENT, vkCode, flags) ? TRUE : FALSE;
}
