/*
  Name:             keybd_shift
  Copyright:        Copyright (C) SIL International.
  Documentation:
  Description:
  Create Date:      11 Dec 2009

  Modified Date:    9 Aug 2015
  Authors:          mcdurdin
  Related Files:
  Dependencies:

  Bugs:
  Todo:
  Notes:
  History:          11 Dec 2009 - mcdurdin - I934 - x64 - Initial version
                    12 Mar 2010 - mcdurdin - I934 - x64 - Complete
                    12 Mar 2010 - mcdurdin - I2229 - Remove hints and warnings
                    31 Dec 2014 - mcdurdin - I4548 - V9.0 - When Alt is down, release of Ctrl, Shift is not detectable within TIP in some languages
                    09 Aug 2015 - mcdurdin - I4844 - Tidy up PostDummyKeyEvent calls
*/
#include "pch.h"
#include "kbd.h"

/**
  The modifier virtual keys Keyman manages. Every modifier loop iterates this table, and
  KEYMAN_MODIFIER_VK_COUNT derives MAX_KEYEVENT_INPUTS_MODIFIERS, so adding one is a single edit.

  Not the low level hook's accepted-VK set: that is nine VKs (isModifierKey, guarded by
  IsModifierKeyAcceptsExactlyNineVks) which collapse into these six. Do not unify them.
*/
const BYTE KeymanModifierVks[KEYMAN_MODIFIER_VK_COUNT] = {
  VK_LMENU, VK_RMENU, VK_LCONTROL, VK_RCONTROL, VK_LSHIFT, VK_RSHIFT
};

/**
  do_keybd_event adds a keyboard event into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  This function mimics the keybd_event Windows API function, but instead of posting the event
  to the system keyboard event queue, it appends it to our internal event queue in pInputs.
  This allows us to send an atomic set of key events with SendInput.

  In this function, we map back the extended modifier keys. Now, the history of the PC keyboard
  means that this is a little weird. The original PC XT keyboard had Left and Right Shift keys,
  but only a single Ctrl and a single Alt key. This means, that the shift keys were each assigned
  their own scan code. However, Windows maps both keys to the same virtual key code (VK_SHIFT) for
  most purposes.

  When the Right Ctrl and Right Alt keys were introduced, they were differentiated from the original
  keys not by separate scan codes, but by an extended prefix byte (E0), together with the original
  scan code. Again, Windows does not differentiate with virtual keys (VK_CONTROL and VK_MENU).

  This means, to check for Left vs Right Shift, you need to test the scan code (2A and 36)
  respectively. However, to test for Left vs Right Ctrl/Alt, you need to test the Extended bit in
  the flags for the message.

  There are a few places where VK_LSHIFT, VK_RSHIFT, VK_LCONTROL, VK_RCONTROL, VK_LMENU, and
  VK_RMENU can be used, such as GetKeyState or MapVirtualKey. However, these virtual key codes
  should never be emitted and will never be received as a key event.

  To add an additional wrinkle to an already wrinkly story, Keyman (ab)uses the scan code property
  of key events to identify key events that it has synthesized, as opposed to those generated by
  the user or by another app (e.g. Remote Desktop scenarios). Instead of using the correct scan
  code, it will stuff the key event with a 0xFF scan code, and replace that in its GetMessage
  so the end application gets a look at the correct scan code. However, this will obviously not
  work with Right Shift, which is differentiated from Left Shift _only_ by scan code. Fortunately,
  we can afford to not care about this -- it means a little extra flag setting behind the scenes
  as the right shift key is released and re-pressed during key events, but nothing too dramatic.
*/
void do_keybd_event(LPINPUT pInputs, int *n, BYTE vk, BYTE scan, DWORD flags, ULONG_PTR extraInfo) {   // I4548
  INPUT input;
  input.type = INPUT_KEYBOARD;

  switch(vk) {
  case VK_RCONTROL:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LCONTROL:
    vk = VK_CONTROL;
    break;

  case VK_RMENU:
    flags |= KEYEVENTF_EXTENDEDKEY;
    /*fallthrough*/
  case VK_LMENU:
    vk = VK_MENU;
    break;

  case VK_RSHIFT:
    scan = SCANCODE_RSHIFT; // from kbd.h
    /*fallthrough*/
  case VK_LSHIFT:
    vk = VK_SHIFT;
    break;
  }

  input.ki.wVk = vk;
  input.ki.wScan = scan;
  input.ki.dwFlags = flags;
  input.ki.time = 0;
  input.ki.dwExtraInfo = extraInfo;
  SendDebugMessageFormat("n=%d, vk=%s, scan=%x, flags=%x", *n, Debug_VirtualKey(vk), scan, flags);

  pInputs[*n] = input;
  (*n)++;
}

/**
  keybd_sendprefix pushes a dummy keystroke into the keyboard event queue.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add

  The keybd_sendprefix call is needed, for example, if the user presses Alt+F which matches a rule
  in the current Keyman keyboard, because without the dummy prefix key, faking the release of the
  Alt key will activate the mainmenu of the current application.
*/
void keybd_sendprefix(LPINPUT pInputs, int *n)
{
  SendDebugEntry();
  //SendDebugMessageFormat("sending prefix down+up");
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, 0, 0);   // I4548   // I4844
  do_keybd_event(pInputs, n, (BYTE) Globals::get_vk_prefix(), SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, 0);   // I4548   // I4844
  SendDebugExit();
}

/**
  keybd_shift_release records the current keyboard state and then releases any modifier
  keys. If a modifier key must be released, it first sends a dummy prefix key to prevent
  isolated modifier key actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), in which we will store
                       the initial modifier state for later restoration by keybd_shift_reset
*/
void keybd_shift_release(LPINPUT pInputs, int *n, LPBYTE const kbd) {
  BOOL hasSentPrefix = FALSE;

  SendDebugEntry();
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      if (!hasSentPrefix) {
        keybd_sendprefix(pInputs, n);
        hasSentPrefix = TRUE;
      }
      SendDebugMessageFormat("sending keyup vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, KEYEVENTF_KEYUP, 0);
    }
  }
  SendDebugExit();
}

/**
  keybd_shift_reset returns the modifiers to their original pressed state and, if any modifier
  key presses are emitted, emits also a dummy 'prefix' keystroke in order to prevent default
  modifier actions such as Alt opening up a menu.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              kbd      pointer to keyboard state (256 byte array), previously set by
                       keybd_shift_release
*/
void keybd_shift_reset(LPINPUT pInputs, int *n, LPBYTE const kbd) {
  BOOL needsPrefix = FALSE;

  SendDebugEntry();
  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (kbd[KeymanModifierVks[i]] & 0x80) {
      SendDebugMessageFormat("sending keydown vkey=%s", Debug_VirtualKey(KeymanModifierVks[i]));
      do_keybd_event(pInputs, n, KeymanModifierVks[i], SCAN_FLAG_KEYMAN_KEY_EVENT, 0, 0);
      needsPrefix = TRUE;
    }
  }

  if (needsPrefix) {
    keybd_sendprefix(pInputs, n);
  }
  SendDebugExit();
}

/**
  keybd_shift evaluates the current keyboard modifier state and queues key events in order to
  initially set modifiers to "up" and, after the output key events are queued, resets the modifiers
  to their initial state.

  Parameters: pInputs  array of INPUT structures which we will fill with our key events.
              n        pointer to current index into pInput, which we increment for each key
                       event we add
              isReset  are we clearing or resetting the modifier state?
              kbd      pointer to keyboard state (256 byte array) that owner must maintain but
                       that we will fill

  There must be enough space in pInputs to contain 6 x up + 6 x down + 2 prefix-down + 2 prefix-up event = 16 events,
  to support both the clear and reset calls.
*/
void keybd_shift(LPINPUT pInputs, int *n, BOOL isReset, LPBYTE const kbd) {
  if (isReset) {
    keybd_shift_reset(pInputs, n, kbd);
  } else {
    keybd_shift_release(pInputs, n, kbd);
  }
}


/**
  CaptureLiveModifierState takes one reading per managed modifier into liveOut.

  Parameters: liveOut              256 bytes, 0x80 for each modifier the OS reports held
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  The single acquisition point for live state in a batch. Everything downstream reads liveOut, so
  the reconcile and the release set are computed from one snapshot. A reading per consumer let the
  two disagree -- the user can press or release in between -- and a batch assembled from two
  snapshots can release a modifier and then decline to restore it. Exactly
  KEYMAN_MODIFIER_VK_COUNT readings, pinned by BatchTakesOneLiveReadingPerManagedModifier.

  GetAsyncKeyState, not GetKeyState or GetKeyboardState: those read the calling thread's processed
  queue, the stale source.

  Not a gap, measured: SendInput does not return until the injected press is visible to
  GetAsyncKeyState, so a previous batch's re-press cannot still be in flight here. Pinned by
  DISABLED_ReconcileDoesNotRaceItsOwnInjectedRestorePress, which also records what would break.
*/
void CaptureLiveModifierState(LPBYTE liveOut, PGETASYNCKEYSTATE pfnGetAsyncKeyState) {
  // Zeroed in full: no caller stack residue is mistaken for a held modifier.
  memset(liveOut, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    if (pfnGetAsyncKeyState(KeymanModifierVks[i]) < 0) {
      liveOut[KeymanModifierVks[i]] = 0x80;
    }
  }
}

/**
  ReconcileModifierCache clears any modifier the cache reports held while the live state reports it
  up. Returns TRUE if the two disagreed.

  Parameters: kbd   the modifier cache (256 byte array), reconciled in place
              live  the live snapshot from CaptureLiveModifierState. Read, never written

  A dropped modifier KEYUP leaves that cache byte set for the life of the process, and
  keybd_shift_reset then presses the modifier for real. See #8064.

  Clears but never sets, since the user may release before SendInput runs.
*/
BOOL ReconcileModifierCache(LPBYTE const kbd, LPBYTE const live) {
  BOOL disagreed = FALSE;

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    const BYTE vk = KeymanModifierVks[i];
    if ((kbd[vk] & 0x80) && !(live[vk] & 0x80)) {
      SendDebugMessageFormat("cache says held but OS says up, clearing vkey=%s", Debug_VirtualKey(vk));
      kbd[vk] = 0;
      disagreed = TRUE;
    }
  }

  return disagreed;
}

/**
  ComputeModifierReleaseState fills releaseStateOut with the union of the modifiers the cache holds
  and the modifiers the OS holds.

  Parameters: kbd              the modifier cache (256 bytes). Read, never written
              releaseStateOut  256 bytes, the release set. Must not alias kbd
              live             the live snapshot from CaptureLiveModifierState. Read, never written

  The mirror of #8064: a modifier the OS holds that the cache never saw would otherwise let the
  batch inject its output keys with that modifier live. The union is explicit so that removing the
  reconcile cannot quietly make this a cache-only read.
*/
void ComputeModifierReleaseState(LPBYTE const kbd, LPBYTE releaseStateOut, LPBYTE const live) {
  // Zeroed in full: no caller stack residue reaches keybd_shift_release.
  memset(releaseStateOut, 0, 256);

  for (int i = 0; i < _countof(KeymanModifierVks); i++) {
    const BYTE vk = KeymanModifierVks[i];
    if ((kbd[vk] & 0x80) || (live[vk] & 0x80)) {
      releaseStateOut[vk] = 0x80;
    }
  }
}

/**
  PrepareInjectedInputBatch assembles one injected batch into pInputs and returns the event count:
  release half, output keys, restore half.

  Parameters: pInputs              at least MAX_KEYEVENT_INPUTS INPUT structures
              kbd                  the modifier cache (256 bytes), reconciled in place
              pSharedData          the output keys to wrap; nInputs is clamped here
              pfnGetAsyncKeyState  live modifier state reader; production passes GetAsyncKeyState

  A free function so the gtest project can reach it; serialkeyeventserver.cpp is #ifndef _WIN64.
  The output-key copy stops MAX_KEYEVENT_INPUTS_MODIFIERS short of the end so the restore half
  fits: the worst case fills the buffer exactly, so an off-by-one is a heap overrun. See #8064.
*/
int PrepareInjectedInputBatch(
  LPINPUT pInputs,
  LPBYTE const kbd,
  const SerialKeyEventSharedData *pSharedData,
  PGETASYNCKEYSTATE pfnGetAsyncKeyState) {
  DWORD nInputs = min(pSharedData->nInputs, MAX_KEYEVENT_INPUTS);
  int n         = 0;

  // One reading per modifier for the whole batch. Both consumers below read this, so they cannot
  // disagree about what the OS held at the top of the batch.
  BYTE live[256];
  CaptureLiveModifierState(live, pfnGetAsyncKeyState);

  // Clear any modifier the cache thinks is held but the OS does not, before keybd_shift_reset
  // below presses it for real. See #8064.
  ReconcileModifierCache(kbd, live);

  // Locals, never member state: a second long-lived cache is a second thing to keep in sync.
  BYTE releaseState[256];
  ComputeModifierReleaseState(kbd, releaseState, live);

  keybd_shift(pInputs, &n, FALSE, releaseState);

  for (DWORD i = 0; i < nInputs && n < MAX_KEYEVENT_INPUTS - MAX_KEYEVENT_INPUTS_MODIFIERS; i++, n++) {
    pInputs[n].type           = INPUT_KEYBOARD;
    pInputs[n].ki.wVk         = pSharedData->inputs[i].wVk;
    pInputs[n].ki.wScan       = pSharedData->inputs[i].wScan;
    pInputs[n].ki.dwFlags     = pSharedData->inputs[i].dwFlags;
    pInputs[n].ki.time        = pSharedData->inputs[i].time;
    pInputs[n].ki.dwExtraInfo = (ULONG_PTR)pSharedData->inputs[i].extraInfo;
  }

  // Not reconciled here: mid-batch the OS state is Keyman's own doing, not ground truth. And kbd,
  // never releaseState -- re-pressing on the OS's word is unsafe, since the user may let go before
  // SendInput runs. That unmatched KEYDOWN is #8064.
  keybd_shift(pInputs, &n, TRUE, kbd);

  return n;
}
