
#ifndef DEBUGSTORE_H
#define DEBUGSTORE_H

#define DEBUGSTORE_BEGIN	L"B"
#define DEBUGSTORE_BEGIN_C	L'B'

#define DEBUGSTORE_MATCH		L"M"
#define DEBUGSTORE_MATCH_C		L'M'

#define DEBUGSTORE_NOMATCH		L"N"
#define DEBUGSTORE_NOMATCH_C	L'N'

#define DEBUGSTORE_GROUP		L"G"
#define DEBUGSTORE_GROUP_C		L'G'

#define DEBUGSTORE_DEADKEY		L"D"
#define DEBUGSTORE_DEADKEY_C	L'D'

#endif /* DEBUGSTORE_H */ 
