#
# This file adds labels based on the scopes in resources/scopes/scopes.json and
# resources/scopes/commit-types.json
# Currently it must be manually kept up to date. Not all labels are added, only
# common ones. The others are commented out. There is still some variance between
# folder names and labels; consider this documentation of that ;-)

docs: docs/**

#
# Add labels based on changed files using actions/labeler
#

android/: android/**
android/app/: android/KMAPro/**
android/engine/: android/KMEA/**
android/samples/: android/Samples/**

common/:
  - common/**
  - resources/**

common/models/: common/models/**
common/models/templates/: common/models/templates/**
common/models/wordbreakers/: common/models/wordbreakers/**

common/resources/: resources/**
common/web/: common/web/**

core/:
  - core/**

developer/:
  - developer/**

developer/compilers/:
  - developer/src/kmc/**
  - developer/src/kmcmplib/**
  - developer/src/kmc-*/**

developer/ide/:
  - developer/src/server/**
  - developer/src/tike/**


ios/: ios/**
ios/app/: ios/keyman/**
ios/engine/: ios/engine/**
ios/samples/: ios/samples/**

linux/: linux/**
linux/config/: linux/keyman-config/**
linux/engine/:
  - linux/ibus-keyman/**
  - linux/legacy/ibus-kmfl/**
  - linux/legacy/kmflcomp/**
  - linux/legacy/libkmfl/**

mac/: mac/**
# mac/config/:
# mac/engine/: mac/**

oem/: oem/**
oem/fv/: oem/firstvoices/**
oem/fv/android/: oem/firstvoices/android/**
oem/fv/ios/: oem/firstvoices/ios/**
oem/fv/windows/: oem/firstvoices/windows/**

web/: web/**
# web/bookmarklet/
web/engine/: web/source/**
web/ui/: web/source/kmwui*
web/samples/: web/samples/**

windows/: windows/**
windows/config/: windows/src/desktop/**
windows/engine/: windows/src/engine/**
