version: v1

# This file adds labels based on the scopes in resources/scopes/scopes.json and
# resources/scopes/commit-types.json
# Currently it must be manually kept up to date. Not all labels are added, only
# common ones. The others are commented out. There is still some variance between
# folder names and labels; consider this documentation of that ;-)

#
# Add labels based on the PR title using fuxingloh/multi-labeler
#

labels:
  #
  # conventional commit / semantic PR styles
  #

  - label: 'auto'
    matcher:
      title: '^auto(\(|:)'
  - label: 'change'
    matcher:
      title: '^change(\(|:)'
  - label: 'chore'
    matcher:
      title: '^chore(\(|:)'
  - label: 'docs'
    matcher:
      title: '^docs(\(|:)'
  - label: 'feat'
    matcher:
      title: '^feat(\(|:)'
  - label: 'fix'
    matcher:
      title: '^fix(\(|:)'
  - label: 'refactor'
    matcher:
      title: '^refactor(\(|:)'
  - label: 'style'
    matcher:
      title: '^style(\(|:)'
  - label: 'test'
    matcher:
      title: '^test(\(|:)'

  #
  # additional meta flags
  #

  # stable-targeted patches; note, this does not pick up chained PRs automatically
  - label: 'stable'
    matcher:
      baseBranch: '^stable-.+'

  # PRs marked as cherry-picks by title
  - label: 'cherry-pick'
    matcher:
      title: '(🍒|:cherries:)'

  # long-lived feature branches
  - label: 'feature-branch'
    matcher:
      branch: '^feature-.+'

  #
  # Scopes that we look for in the PR title
  #

  - label: 'android/'
    matcher:
      title: '\(.*android.*\):'
  - label: 'common/'
    matcher:
      title: '\(.*common.*\):'
  - label: 'core/'
    matcher:
      title: '\(.*core.*\):'
  - label: 'developer/'
    matcher:
      title: '\(.*developer.*\):'
  - label: 'ios/'
    matcher:
      title: '\(.*ios.*\):'
  - label: 'linux/'
    matcher:
      title: '\(.*linux.*\):'
  - label: 'mac/'
    matcher:
      title: '\(.*mac.*\):'
  - label: 'oem/'
    matcher:
      title: '\(.*oem.*\):'
  - label: 'web/'
    matcher:
      title: '\(.*web.*\):'
  - label: 'windows/'
    matcher:
      title: '\(.*windows.*\):'
