//Autogenerated file - do not modify!
namespace com.keyman.environment {
  export var VERSION = "15.0";
  export var BUILD = 163;
  export var ENVIRONMENT = "local";
  export var SENTRY_RELEASE = "release-15.0.163-alpha-local";
}

