#!/usr/bin/python3

import sys
from keyman.get_kmp import get_kmp

def main(argv):
	if len(sys.argv) != 2:
		print("get_kmp.py <keyboard id>")
		sys.exit(2)
	keyboardid = sys.argv[1]
	get_kmp(keyboardid)

if __name__ == "__main__":
	main(sys.argv[1:])
