#!/usr/bin/python3

import argparse
import sys
from keyman_config import __version__
from keyman_config.install_kmp import install_kmp
from keyman_config.list_installed_kmp import get_kmp_version
from keyman_config.get_kmp import get_keyboard_data, get_kmp

def main():
	parser = argparse.ArgumentParser(description='Install a Keyman keyboard, either a local .kmp file or specify a keyboard id to download and install')
	parser.add_argument('-f', metavar='<kmpfile>', help='Keyman kmp file')
	parser.add_argument('-k', metavar='<keyboardid>', help='Keyman keyboard id')
	parser.add_argument('--version', action='version', version='%(prog)s version '+__version__)

	args = parser.parse_args()
	if args.k and args.f:
		print("km-package-install: error: too many arguments: either install a local kmp file or specify a keyboard id to download and install.")
		sys.exit(2)

	if args.f:
		name, ext = os.path.splitext(args.f)
		if ext != ".kmp":
			print("km-package-install: Input file", args.f, "is not a kmp file.")
			print("km-package-install -f <kmpfile>")
			sys.exit(2)

		if not os.path.isfile(args.f):
			print("km-package-install: Keyman kmp file", args.f, "not found.")
			print("km-package-install -f <kmpfile>")
			sys.exit(2)

		install_kmp(args.f)
	elif args.k:
		installed_kmp_ver = get_kmp_version(args.k)
		kbdata = get_keyboard_data(args.k)
		if not kbdata:
			print("km-package-install: error: Could not download keyboard data for", args.k)
			sys.exit(3)
		if installed_kmp_ver:
			if kbdata['version'] == installed_kmp_ver:
				print("km-package-install: The %s version of the %s keyboard is already installed." % (installed_kmp_ver, args.k))
				sys.exit(1)
			elif float(kbdata['version']) > float(installed_kmp_ver):
				print("km-package-install: A newer version of %s keyboard is available. Uninstalling old version %s then downloading and installing new version %s." % (args.k, installed_kmp_ver, kbdata['version']))
				uninstall_kmp(args.k)

		kmpfile = get_kmp(args.k)
		if kmpfile:
			install_kmp(kmpfile, True)
		else:
			print("km-package-install: error: Could not download keyboard package", args.k)
			sys.exit(2)
	else:
		print("km-package-install: error: no arguments: either install a local kmp file or specify a keyboard id to download and install.")
		sys.exit(2)



if __name__ == "__main__":
	main()
