#!/usr/bin/python3

import argparse
import logging
import sys

from keyman_config import __version__
from keyman_config.uninstall_kmp import uninstall_kmp

def main():
	parser = argparse.ArgumentParser(description='Uninstall Keyman keyboard package.')
	parser.add_argument('id', help='Keyman keyboard id')
	parser.add_argument('--version', action='version', version='%(prog)s version '+__version__)
	parser.add_argument('-v', action='store_true', help='verbose logging')
	parser.add_argument('-vv', action='store_true', help='very verbose logging')

	args = parser.parse_args()
	if args.v:
		logging.basicConfig(level=logging.INFO, format='%(levelname)s:%(message)s')
	elif args.vv:
		logging.basicConfig(level=logging.DEBUG, format='%(levelname)s:%(message)s')
	else:
		logging.basicConfig(format='%(levelname)s:%(message)s')

	uninstall_kmp(args.id)

if __name__ == "__main__":
	main()
