#!/usr/bin/python3

import argparse
import logging

from keyman_config import __version__


def main():
    parser = argparse.ArgumentParser(description='Uninstall Keyman keyboard package.')
    parser.add_argument('id', help='Keyman keyboard id')
    parser.add_argument('-s', '--shared', action='store_true', help='Uninstall from shared area /usr/local')
    parser.add_argument('--version', action='version', version='%(prog)s version ' + __version__)
    parser.add_argument('-v', '--verbose', action='store_true', help='verbose logging')
    parser.add_argument('-vv', '--veryverbose', action='store_true', help='very verbose logging')

    args = parser.parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.INFO, format='%(levelname)s:%(message)s')
    elif args.veryverbose:
        logging.basicConfig(level=logging.DEBUG, format='%(levelname)s:%(message)s')
    else:
        logging.basicConfig(format='%(levelname)s:%(message)s')

    from keyman_config.uninstall_kmp import uninstall_kmp
    uninstall_kmp(args.id, args.shared)


if __name__ == "__main__":
    main()
