#!/usr/bin/python3

import argparse
import logging
import os

from keyman_config import __version__


def main():
    parser = argparse.ArgumentParser(description='Download Keyman keyboard package to ~/.cache/keyman')
    parser.add_argument('id', help='Keyman keyboard id')
    parser.add_argument('--version', action='version', version='%(prog)s version ' + __version__)
    parser.add_argument('-v', '--verbose', action='store_true', help='verbose logging')
    parser.add_argument('-vv', '--veryverbose', action='store_true', help='very verbose logging')

    args = parser.parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.INFO, format='%(levelname)s:%(message)s')
    elif args.veryverbose:
        logging.basicConfig(level=logging.DEBUG, format='%(levelname)s:%(message)s')
    else:
        logging.basicConfig(format='%(levelname)s:%(message)s')

    from keyman_config.get_kmp import get_kmp, keyman_cache_dir
    get_kmp(args.id)
    if os.path.exists(os.path.join(keyman_cache_dir(), 'kmpdirlist')):
        os.remove(os.path.join(keyman_cache_dir(), 'kmpdirlist'))


if __name__ == "__main__":
    main()
