#!/usr/bin/python3

import argparse
import sys
import os.path

from keyman_config import __version__
from keyman_config.kmpmetadata import parseinfdata, parsemetadata

def main():
	parser = argparse.ArgumentParser(description='Parse Keymap package data kmp.json or kmp.inf')
	parser.add_argument('file', help='Either a kmp.json or kmp.inf')
	parser.add_argument('--version', action='version', version='%(prog)s version '+__version__)

	args = parser.parse_args()


	if not os.path.isfile(args.file):
		print("kmpmetadata.py Input file ", args.file, " not found.")
		print("kmpmetadata.py <kmp.json> or <kmp.inf>")
		sys.exit(2)
	
	name, ext = os.path.splitext(args.file)
	if ext == ".json":
		parsemetadata(args.file, True)
	elif ext == ".inf":
		parseinfdata(args.file, True)
	else:
		print("kmpmetadata.py Input file must be json or inf.")
		print("kmpmetadata.py <kmp.json> or <kmp.inf>")
		sys.exit(2)

if __name__ == "__main__":
        main()

