
#ifndef DEBUGSTORE_H
#define DEBUGSTORE_H

#define DEBUGSTORE_BEGIN	u"B"
#define DEBUGSTORE_BEGIN_C	u'B'

#define DEBUGSTORE_MATCH		u"M"
#define DEBUGSTORE_MATCH_C		u'M'

#define DEBUGSTORE_NOMATCH		u"N"
#define DEBUGSTORE_NOMATCH_C	u'N'

#define DEBUGSTORE_GROUP		u"G"
#define DEBUGSTORE_GROUP_C		u'G'

#define DEBUGSTORE_DEADKEY		u"D"
#define DEBUGSTORE_DEADKEY_C	u'D'

#endif /* DEBUGSTORE_H */ 
