
#ifndef DEBUGSTORE_H
#define DEBUGSTORE_H

#define DEBUGSTORE_BEGIN	u"B"
#define DEBUGSTORE_BEGIN_C	u'B'

#define DEBUGSTORE_MATCH_U		u"M"
#define DEBUGSTORE_MATCH_L		L"M"

#define DEBUGSTORE_NOMATCH_U	u"N"
#define DEBUGSTORE_NOMATCH_L	L"N"

#define DEBUGSTORE_GROUP_U		u"G"
#define DEBUGSTORE_GROUP_L		L"G"

#define DEBUGSTORE_DEADKEY_U	u"D"
#define DEBUGSTORE_DEADKEY_L	L"D"

#endif /* DEBUGSTORE_H */
