
static PCWSTR VKeyNames[256] = {
// Key Codes
	L"K_?00",				// &H0
	L"K_LBUTTON",			// &H1
	L"K_RBUTTON",			// &H2
	L"K_CANCEL",		   	// &H3
	L"K_MBUTTON",			// &H4
	L"K_?05",				// &H5
	L"K_?06",				// &H6
	L"K_?07",				// &H7
	L"K_BKSP",	    		// &H8
	L"K_TAB",	    		// &H9
	L"K_?0A",				// &HA
	L"K_?0B",				// &HB
	L"K_KP5",		    	// &HC
	L"K_ENTER",				// &HD
	L"K_?0E",				// &HE
	L"K_?0F",				// &HF
	L"K_SHIFT",				// &H10
	L"K_CONTROL",			// &H11
	L"K_ALT",				// &H12
	L"K_PAUSE",				// &H13
	L"K_CAPS",				// &H14
	L"K_KANJI?15",			// &H15
	L"K_KANJI?16",			// &H16
	L"K_KANJI?17",			// &H17
	L"K_KANJI?18",			// &H18
	L"K_KANJI?19",			// &H19
	L"K_?1A",				// &H1A
	L"K_ESC",				// &H1B
	L"K_KANJI?1C",			// &H1C
	L"K_KANJI?1D",			// &H1D
	L"K_KANJI?1E",			// &H1E
	L"K_KANJI?1F",			// &H1F
	L"K_SPACE",				// &H20
	L"K_PGUP",				// &H21
	L"K_PGDN",				// &H22
	L"K_END",				// &H23
	L"K_HOME",				// &H24
	L"K_LEFT",				// &H25
	L"K_UP",				// &H26
	L"K_RIGHT",				// &H27
	L"K_DOWN",				// &H28
	L"K_SEL",				// &H29
	L"K_PRINT",				// &H2A
	L"K_EXEC",				// &H2B
	L"K_PRTSCN",			// &H2C
	L"K_INS",				// &H2D
	L"K_DEL",				// &H2E
	L"K_HELP",				// &H2F
	L"K_0",					// &H30
	L"K_1",					// &H31
	L"K_2",					// &H32
	L"K_3",					// &H33
	L"K_4",					// &H34
	L"K_5",					// &H35
	L"K_6",					// &H36
	L"K_7",					// &H37
	L"K_8",					// &H38
	L"K_9",					// &H39
	L"K_?3A",				// &H3A
	L"K_?3B",				// &H3B
	L"K_?3C",				// &H3C
	L"K_?3D",				// &H3D
	L"K_?3E",				// &H3E
	L"K_?3F",				// &H3F
	L"K_?40",				// &H40

	L"K_A",					// &H41
	L"K_B",					// &H42
	L"K_C",					// &H43
	L"K_D",					// &H44
	L"K_E",					// &H45
	L"K_F",					// &H46
	L"K_G",					// &H47
	L"K_H",					// &H48
	L"K_I",					// &H49
	L"K_J",					// &H4A
	L"K_K",					// &H4B
	L"K_L",					// &H4C
	L"K_M",					// &H4D
	L"K_N",					// &H4E
	L"K_O",					// &H4F
	L"K_P",					// &H50
	L"K_Q",					// &H51
	L"K_R",					// &H52
	L"K_S",					// &H53
	L"K_T",					// &H54
	L"K_U",					// &H55
	L"K_V",					// &H56
	L"K_W",					// &H57
	L"K_X",					// &H58
	L"K_Y",					// &H59
	L"K_Z",					// &H5A
	L"K_?5B",				// &H5B
	L"K_?5C",				// &H5C
	L"K_?5D",				// &H5D
	L"K_?5E",				// &H5E
	L"K_?5F",				// &H5F
	L"K_NP0",				// &H60
	L"K_NP1",				// &H61
	L"K_NP2",				// &H62
	L"K_NP3",				// &H63
	L"K_NP4",				// &H64
	L"K_NP5",				// &H65
	L"K_NP6",				// &H66
	L"K_NP7",				// &H67
	L"K_NP8",				// &H68
	L"K_NP9",				// &H69
	L"K_NPSTAR",			// &H6A
	L"K_NPPLUS",			// &H6B
	L"K_SEPARATOR",			// &H6C
	L"K_NPMINUS",			// &H6D
	L"K_NPDOT",				// &H6E
	L"K_NPSLASH",			// &H6F
	L"K_F1",				// &H70
	L"K_F2",				// &H71
	L"K_F3",				// &H72
	L"K_F4",				// &H73
	L"K_F5",				// &H74
	L"K_F6",				// &H75
	L"K_F7",				// &H76
	L"K_F8",				// &H77
	L"K_F9",				// &H78
	L"K_F10",				// &H79
	L"K_F11",				// &H7A
	L"K_F12",				// &H7B
	L"K_F13",				// &H7C
	L"K_F14",				// &H7D
	L"K_F15",				// &H7E
	L"K_F16",				// &H7F
	L"K_F17",				// &H80
	L"K_F18",				// &H81
	L"K_F19",				// &H82
	L"K_F20",				// &H83
	L"K_F21",				// &H84
	L"K_F22",				// &H85
	L"K_F23",				// &H86
	L"K_F24",				// &H87

	L"K_?88",				// &H88
	L"K_?89",				// &H89
	L"K_?8A",				// &H8A
	L"K_?8B",				// &H8B
	L"K_?8C",				// &H8C
	L"K_?8D",				// &H8D
	L"K_?8E",				// &H8E
	L"K_?8F",				// &H8F

	L"K_NUMLOCK",			// &H90
	L"K_SCROLL",			// &H91

	L"K_?92",				// &H92
	L"K_?93",				// &H93
	L"K_?94",				// &H94
	L"K_?95",				// &H95
	L"K_?96",				// &H96
	L"K_?97",				// &H97
	L"K_?98",				// &H98
	L"K_?99",				// &H99
	L"K_?9A",				// &H9A
	L"K_?9B",				// &H9B
	L"K_?9C",				// &H9C
	L"K_?9D",				// &H9D
	L"K_?9E",				// &H9E
	L"K_?9F",				// &H9F
	L"K_?A0",				// &HA0
	L"K_?A1",				// &HA1
	L"K_?A2",				// &HA2
	L"K_?A3",				// &HA3
	L"K_?A4",				// &HA4
	L"K_?A5",				// &HA5
	L"K_?A6",				// &HA6
	L"K_?A7",				// &HA7
	L"K_?A8",				// &HA8
	L"K_?A9",				// &HA9
	L"K_?AA",				// &HAA
	L"K_?AB",				// &HAB
	L"K_?AC",				// &HAC
	L"K_?AD",				// &HAD
	L"K_?AE",				// &HAE
	L"K_?AF",				// &HAF
	L"K_?B0",				// &HB0
	L"K_?B1",				// &HB1
	L"K_?B2",				// &HB2
	L"K_?B3",				// &HB3
	L"K_?B4",				// &HB4
	L"K_?B5",				// &HB5
	L"K_?B6",				// &HB6
	L"K_?B7",				// &HB7
	L"K_?B8",				// &HB8
	L"K_?B9",				// &HB9

	L"K_COLON",				// &HBA
	L"K_EQUAL",				// &HBB
	L"K_COMMA",				// &HBC
	L"K_HYPHEN",			// &HBD
	L"K_PERIOD",			// &HBE
	L"K_SLASH",				// &HBF
	L"K_BKQUOTE",			// &HC0

	L"K_?C1",				// &HC1
	L"K_?C2",				// &HC2
	L"K_?C3",				// &HC3
	L"K_?C4",				// &HC4
	L"K_?C5",				// &HC5
	L"K_?C6",				// &HC6
	L"K_?C7",				// &HC7
	L"K_?C8",				// &HC8
	L"K_?C9",				// &HC9
	L"K_?CA",				// &HCA
	L"K_?CB",				// &HCB
	L"K_?CC",				// &HCC
	L"K_?CD",				// &HCD
	L"K_?CE",				// &HCE
	L"K_?CF",				// &HCF
	L"K_?D0",				// &HD0
	L"K_?D1",				// &HD1
	L"K_?D2",				// &HD2
	L"K_?D3",				// &HD3
	L"K_?D4",				// &HD4
	L"K_?D5",				// &HD5
	L"K_?D6",				// &HD6
	L"K_?D7",				// &HD7
	L"K_?D8",				// &HD8
	L"K_?D9",				// &HD9
	L"K_?DA",				// &HDA

	L"K_LBRKT",				// &HDB
	L"K_BKSLASH",			// &HDC
	L"K_RBRKT",				// &HDD
	L"K_QUOTE",				// &HDE
	L"K_oDF",				// &HDF
	L"K_oE0",				// &HE0
	L"K_oE1",				// &HE1
	L"K_oE2",				// &HE2
	L"K_oE3",				// &HE3
	L"K_oE4",				// &HE4

	L"K_?E5",				// &HE5

	L"K_oE6",				// &HE6

	L"K_?E7",				// &HE7
	L"K_?E8",				// &HE8

	L"K_oE9",				// &HE9
	L"K_oEA",				// &HEA
	L"K_oEB",				// &HEB
	L"K_oEC",				// &HEC
	L"K_oED",				// &HED
	L"K_oEE",				// &HEE
	L"K_oEF",				// &HEF
	L"K_oF0",				// &HF0
	L"K_oF1",				// &HF1
	L"K_oF2",				// &HF2
	L"K_oF3",				// &HF3
	L"K_oF4",				// &HF4
	L"K_oF5",				// &HF5

	L"K_?F6",				// &HF6
	L"K_?F7",				// &HF7
	L"K_?F8",				// &HF8
	L"K_?F9",				// &HF9
	L"K_?FA",				// &HFA
	L"K_?FB",				// &HFB
	L"K_?FC",				// &HFC
	L"K_?FD",				// &HFD
	L"K_?FE",				// &HFE
	L"K_?FF"				// &HFF
	};
	
//----------------------------------------------------------------------------
static PKMX_WCHAR VKeyNames_S2[256] = {
// Key Codes
	u"K_?00",				// &H0
	u"K_LBUTTON",			// &H1
	u"K_RBUTTON",			// &H2
	u"K_CANCEL",		   	// &H3
	u"K_MBUTTON",			// &H4
	u"K_?05",				// &H5
	u"K_?06",				// &H6
	u"K_?07",				// &H7
	u"K_BKSP",	    		// &H8
	u"K_TAB",	    		// &H9
	u"K_?0A",				// &HA
	u"K_?0B",				// &HB
	u"K_KP5",		    	// &HC
	u"K_ENTER",				// &HD
	u"K_?0E",				// &HE
	u"K_?0F",				// &HF
	u"K_SHIFT",				// &H10
	u"K_CONTROL",			// &H11
	u"K_ALT",				// &H12
	u"K_PAUSE",				// &H13
	u"K_CAPS",				// &H14
	u"K_KANJI?15",			// &H15
	u"K_KANJI?16",			// &H16
	u"K_KANJI?17",			// &H17
	u"K_KANJI?18",			// &H18
	u"K_KANJI?19",			// &H19
	u"K_?1A",				// &H1A
	u"K_ESC",				// &H1B
	u"K_KANJI?1C",			// &H1C
	u"K_KANJI?1D",			// &H1D
	u"K_KANJI?1E",			// &H1E
	u"K_KANJI?1F",			// &H1F
	u"K_SPACE",				// &H20
	u"K_PGUP",				// &H21
	u"K_PGDN",				// &H22
	u"K_END",				// &H23
	u"K_HOME",				// &H24
	u"K_LEFT",				// &H25
	u"K_UP",				// &H26
	u"K_RIGHT",				// &H27
	u"K_DOWN",				// &H28
	u"K_SEL",				// &H29
	u"K_PRINT",				// &H2A
	u"K_EXEC",				// &H2B
	u"K_PRTSCN",			// &H2C
	u"K_INS",				// &H2D
	u"K_DEL",				// &H2E
	u"K_HELP",				// &H2F
	u"K_0",					// &H30
	u"K_1",					// &H31
	u"K_2",					// &H32
	u"K_3",					// &H33
	u"K_4",					// &H34
	u"K_5",					// &H35
	u"K_6",					// &H36
	u"K_7",					// &H37
	u"K_8",					// &H38
	u"K_9",					// &H39
	u"K_?3A",				// &H3A
	u"K_?3B",				// &H3B
	u"K_?3C",				// &H3C
	u"K_?3D",				// &H3D
	u"K_?3E",				// &H3E
	u"K_?3F",				// &H3F
	u"K_?40",				// &H40

	u"K_A",					// &H41
	u"K_B",					// &H42
	u"K_C",					// &H43
	u"K_D",					// &H44
	u"K_E",					// &H45
	u"K_F",					// &H46
	u"K_G",					// &H47
	u"K_H",					// &H48
	u"K_I",					// &H49
	u"K_J",					// &H4A
	u"K_K",					// &H4B
	u"K_L",					// &H4C
	u"K_M",					// &H4D
	u"K_N",					// &H4E
	u"K_O",					// &H4F
	u"K_P",					// &H50
	u"K_Q",					// &H51
	u"K_R",					// &H52
	u"K_S",					// &H53
	u"K_T",					// &H54
	u"K_U",					// &H55
	u"K_V",					// &H56
	u"K_W",					// &H57
	u"K_X",					// &H58
	u"K_Y",					// &H59
	u"K_Z",					// &H5A
	u"K_?5B",				// &H5B
	u"K_?5C",				// &H5C
	u"K_?5D",				// &H5D
	u"K_?5E",				// &H5E
	u"K_?5F",				// &H5F
	u"K_NP0",				// &H60
	u"K_NP1",				// &H61
	u"K_NP2",				// &H62
	u"K_NP3",				// &H63
	u"K_NP4",				// &H64
	u"K_NP5",				// &H65
	u"K_NP6",				// &H66
	u"K_NP7",				// &H67
	u"K_NP8",				// &H68
	u"K_NP9",				// &H69
	u"K_NPSTAR",			// &H6A
	u"K_NPPLUS",			// &H6B
	u"K_SEPARATOR",			// &H6C
	u"K_NPMINUS",			// &H6D
	u"K_NPDOT",				// &H6E
	u"K_NPSLASH",			// &H6F
	u"K_F1",				// &H70
	u"K_F2",				// &H71
	u"K_F3",				// &H72
	u"K_F4",				// &H73
	u"K_F5",				// &H74
	u"K_F6",				// &H75
	u"K_F7",				// &H76
	u"K_F8",				// &H77
	u"K_F9",				// &H78
	u"K_F10",				// &H79
	u"K_F11",				// &H7A
	u"K_F12",				// &H7B
	u"K_F13",				// &H7C
	u"K_F14",				// &H7D
	u"K_F15",				// &H7E
	u"K_F16",				// &H7F
	u"K_F17",				// &H80
	u"K_F18",				// &H81
	u"K_F19",				// &H82
	u"K_F20",				// &H83
	u"K_F21",				// &H84
	u"K_F22",				// &H85
	u"K_F23",				// &H86
	u"K_F24",				// &H87

	u"K_?88",				// &H88
	u"K_?89",				// &H89
	u"K_?8A",				// &H8A
	u"K_?8B",				// &H8B
	u"K_?8C",				// &H8C
	u"K_?8D",				// &H8D
	u"K_?8E",				// &H8E
	u"K_?8F",				// &H8F

	u"K_NUMLOCK",			// &H90
	u"K_SCROLL",			// &H91

	u"K_?92",				// &H92
	u"K_?93",				// &H93
	u"K_?94",				// &H94
	u"K_?95",				// &H95
	u"K_?96",				// &H96
	u"K_?97",				// &H97
	u"K_?98",				// &H98
	u"K_?99",				// &H99
	u"K_?9A",				// &H9A
	u"K_?9B",				// &H9B
	u"K_?9C",				// &H9C
	u"K_?9D",				// &H9D
	u"K_?9E",				// &H9E
	u"K_?9F",				// &H9F
	u"K_?A0",				// &HA0
	u"K_?A1",				// &HA1
	u"K_?A2",				// &HA2
	u"K_?A3",				// &HA3
	u"K_?A4",				// &HA4
	u"K_?A5",				// &HA5
	u"K_?A6",				// &HA6
	u"K_?A7",				// &HA7
	u"K_?A8",				// &HA8
	u"K_?A9",				// &HA9
	u"K_?AA",				// &HAA
	u"K_?AB",				// &HAB
	u"K_?AC",				// &HAC
	u"K_?AD",				// &HAD
	u"K_?AE",				// &HAE
	u"K_?AF",				// &HAF
	u"K_?B0",				// &HB0
	u"K_?B1",				// &HB1
	u"K_?B2",				// &HB2
	u"K_?B3",				// &HB3
	u"K_?B4",				// &HB4
	u"K_?B5",				// &HB5
	u"K_?B6",				// &HB6
	u"K_?B7",				// &HB7
	u"K_?B8",				// &HB8
	u"K_?B9",				// &HB9

	u"K_COLON",				// &HBA
	u"K_EQUAL",				// &HBB
	u"K_COMMA",				// &HBC
	u"K_HYPHEN",			// &HBD
	u"K_PERIOD",			// &HBE
	u"K_SLASH",				// &HBF
	u"K_BKQUOTE",			// &HC0

	u"K_?C1",				// &HC1
	u"K_?C2",				// &HC2
	u"K_?C3",				// &HC3
	u"K_?C4",				// &HC4
	u"K_?C5",				// &HC5
	u"K_?C6",				// &HC6
	u"K_?C7",				// &HC7
	u"K_?C8",				// &HC8
	u"K_?C9",				// &HC9
	u"K_?CA",				// &HCA
	u"K_?CB",				// &HCB
	u"K_?CC",				// &HCC
	u"K_?CD",				// &HCD
	u"K_?CE",				// &HCE
	u"K_?CF",				// &HCF
	u"K_?D0",				// &HD0
	u"K_?D1",				// &HD1
	u"K_?D2",				// &HD2
	u"K_?D3",				// &HD3
	u"K_?D4",				// &HD4
	u"K_?D5",				// &HD5
	u"K_?D6",				// &HD6
	u"K_?D7",				// &HD7
	u"K_?D8",				// &HD8
	u"K_?D9",				// &HD9
	u"K_?DA",				// &HDA

	u"K_LBRKT",				// &HDB
	u"K_BKSLASH",			// &HDC
	u"K_RBRKT",				// &HDD
	u"K_QUOTE",				// &HDE
	u"K_oDF",				// &HDF
	u"K_oE0",				// &HE0
	u"K_oE1",				// &HE1
	u"K_oE2",				// &HE2
	u"K_oE3",				// &HE3
	u"K_oE4",				// &HE4

	u"K_?E5",				// &HE5

	u"K_oE6",				// &HE6

	u"K_?E7",				// &HE7
	u"K_?E8",				// &HE8

	u"K_oE9",				// &HE9
	u"K_oEA",				// &HEA
	u"K_oEB",				// &HEB
	u"K_oEC",				// &HEC
	u"K_oED",				// &HED
	u"K_oEE",				// &HEE
	u"K_oEF",				// &HEF
	u"K_oF0",				// &HF0
	u"K_oF1",				// &HF1
	u"K_oF2",				// &HF2
	u"K_oF3",				// &HF3
	u"K_oF4",				// &HF4
	u"K_oF5",				// &HF5

	u"K_?F6",				// &HF6
	u"K_?F7",				// &HF7
	u"K_?F8",				// &HF8
	u"K_?F9",				// &HF9
	u"K_?FA",				// &HFA
	u"K_?FB",				// &HFB
	u"K_?FC",				// &HFC
	u"K_?FD",				// &HFD
	u"K_?FE",				// &HFE
	u"K_?FF"				// &HFF
	};
