var KVKL_Eurolatin={
  "tablet":
    {
    "font":"Tahoma",
    "layer":[
      {  
        "id":"default",
        "row":[
          {
            "id":"1",
            "key":[
              {"id":"K_Q","text":"q",
                "sk":[
                  {"id":"K_A78C"}
                ]
              },
              {"id":"K_W","text":"w",
                "sk":[
                  {"id":"K_1E81"},
                  {"id":"K_1E83"},
                  {"id":"K_0175"},
                  {"id":"K_1E85"},
                  {"id":"K_1E98"},
                  {"id":"K_1E87"},
                  {"id":"K_1E89"}
                ]
              },
              {"id":"K_E","text":"e",
                "sk":[
                  {"id":"K_00E8"},
                  {"id":"K_0205"},
                  {"id":"K_00E9"},
                  {"id":"K_00EA"},
                  {"id":"K_011B"},
                  {"id":"K_0207"},
                  {"id":"K_0115"},
                  {"id":"K_1EBD"},
                  {"id":"K_0113"},
                  {"id":"K_00EB"},
                  {"id":"K_0117"},
                  {"id":"K_1EB9"},
                  {"id":"K_0119"},
                  {"id":"K_0259"},
                  {"id":"K_025B"}
                ]
              },
              {"id":"K_R","text":"r",
                "sk":[
                  {"id":"K_0211"},
                  {"id":"K_0155"},
                  {"id":"K_0159"},
                  {"id":"K_0213"},
                  {"id":"K_024D"},
                  {"id":"K_1E5F"},
                  {"id":"K_1E59"},
                  {"id":"K_1E5B"},
                  {"id":"K_0157"}
                ]
              },
              {"id":"K_T","text":"t",
                "sk":[
                  {"id":"K_0165"},
                  {"id":"K_0167"},
                  {"id":"K_1E6F"},
                  {"id":"K_1E97"},
                  {"id":"K_1E6B"},
                  {"id":"K_1E6D"},
                  {"id":"K_0163"},
                  {"id":"K_00FE"}                
				        ]              
              },
              {"id":"K_Y","text":"y",
                "sk":[
                  {"id":"K_1EF3"},
                  {"id":"K_00FD"},
                  {"id":"K_0177"},
                  {"id":"K_1EF9"},
                  {"id":"K_0233"},
                  {"id":"K_00FF"},
                  {"id":"K_1E99"},
                  {"id":"K_1E8F"},
                  {"id":"K_1EF5"}
				        ]
              },
              {"id":"K_U","text":"u",
                "sk":[
                  {"id":"K_00F9"},
                  {"id":"K_0215"},
                  {"id":"K_00FA"},
                  {"id":"K_0171"},
                  {"id":"K_00FB"},
                  {"id":"K_01D4"},
                  {"id":"K_0217"},
                  {"id":"K_016D"},
                  {"id":"K_0169"},
                  {"id":"K_016B"},
                  {"id":"K_00FC"},
                  {"id":"K_016F"},
                  {"id":"K_1EE5"},
                  {"id":"K_0173"}
                ]
              },
              {"id":"K_I","text":"i",
                "sk":[
                  {"id":"K_00EC"},
                  {"id":"K_0209"},
                  {"id":"K_00ED"},
                  {"id":"K_00EE"},
                  {"id":"K_01D0"},
                  {"id":"K_020B"},
                  {"id":"K_012D"},
                  {"id":"K_0129"},
                  {"id":"K_012B"},
                  {"id":"K_00EF"},
                  {"id":"K_0131"},
                  {"id":"K_1ECB"},
                  {"id":"K_012F"},
                  {"id":"K_0272"},
                  {"id":"K_0133"}
                ]
              },
              {"id":"K_O","text":"o",
                "sk":[
                  {"id":"K_00F2"},
                  {"id":"K_020D"},
                  {"id":"K_00F3"},
                  {"id":"K_0151"},
                  {"id":"K_00F4"},
                  {"id":"K_01D2"},
                  {"id":"K_020F"},
                  {"id":"K_014F"},
                  {"id":"K_00F5"},
                  {"id":"K_014D"},
                  {"id":"K_00F6"},
                  {"id":"K_022F"},
                  {"id":"K_1ECD"},
                  {"id":"K_01EB"},
                  {"id":"K_0275"},
                  {"id":"K_00F8"},
                  {"id":"K_0254"},
                  {"id":"K_0153"},
                  {"id":"K_01A3"}
                ]
              },
              {"id":"K_P","text":"p",
                "sk":[
                  {"id":"K_1E55"},
                  {"id":"K_0070"},
                  {"id":"K_1E57"}
                ]
              }
              ]
          },
          {
            "id":"2",
            "key":[
              {"id":"K_A","text":"a","pad":"40",
                "sk":[
                  {"id":"K_00E0"},
                  {"id":"K_0201"},
                  {"id":"K_00E1"},
                  {"id":"K_00E2"},
                  {"id":"K_01CE"},
                  {"id":"K_0203"},
                  {"id":"K_0103"},
                  {"id":"K_00E3"},
                  {"id":"K_0101"},
                  {"id":"K_00E4"},
                  {"id":"K_00E5"},
                  {"id":"K_0227"},
                  {"id":"K_1EA1"},
                  {"id":"K_0105"},
                  {"id":"K_00E6"}
                ]
              },
              {"id":"K_S","text":"s",
                "sk":[
                  {"id":"K_015B"},
                  {"id":"K_015D"},
                  {"id":"K_0161"},
                  {"id":"K_1E61"},
                  {"id":"K_1E63"},
                  {"id":"K_015F"},
                  {"id":"K_00DF"},
                  {"id":"K_017F"}
                ]
              },
              {"id":"K_D","text":"d",
                "sk":[
                  {"id":"K_010F"},
                  {"id":"K_0111"},
                  {"id":"K_1E0F"},
                  {"id":"K_1E0B"},
                  {"id":"K_1E0D"},
                  {"id":"K_1E11"},
                  {"id":"K_00F0"},
                  {"id":"K_01C6"}
                ]
              },
              {"id":"K_F","text":"f",
                "sk":[
                  {"id":"K_1E1F"},
                  {"id":"K_FB01"},
                  {"id":"K_FB02"}
                ]
              },
              {"id":"K_G","text":"g",
                "sk":[
                  {"id":"K_01F5"},
                  {"id":"K_011D"},
                  {"id":"K_01E7"},
                  {"id":"K_011F"},
                  {"id":"K_0067"},
                  {"id":"K_1E21"},
                  {"id":"K_0121"},
                  {"id":"K_0123"},
                  {"id":"K_0242"},
                  {"id":"K_01E5"}
                ]
              },
              {"id":"K_H","text":"h",
                "sk":[
                  {"id":"K_0125"},
                  {"id":"K_021F"},
                  {"id":"K_1E2B"},
                  {"id":"K_0127"},
                  {"id":"K_1E96"},
                  {"id":"K_1E27"},
                  {"id":"K_1E23"},
                  {"id":"K_1E25"},
                  {"id":"K_1E29"}
                ]
              },
              {"id":"K_J","text":"j",
                "sk":[
                  {"id":"K_0135"},
                  {"id":"K_01F0"},
                  {"id":"K_0249"},
                  {"id":"K_0237"}
                ]
              },
              {"id":"K_K","text":"k",
                "sk":[
                  {"id":"K_1E31"},
                  {"id":"K_01E9"},
                  {"id":"K_1E35"},
                  {"id":"K_1E33"},
                  {"id":"K_0137"},
                  {"id":"K_0138"}
                ]
              },
              {"id":"K_L","text":"l",
                "sk":[
                  {"id":"K_013A"},
                  {"id":"K_013E"},
                  {"id":"K_026B"},
                  {"id":"K_0142"},
                  {"id":"K_1E3B"},
                  {"id":"K_0140"},
                  {"id":"K_1E37"},
                  {"id":"K_013C"},
                  {"id":"K_01C9"}
                ]
              },
              {"sp":"10","width":"10"}
              ]
          },
          {
            "id":"3",
            "key":[
              {"id":"K_SHIFT","text":"ABC","width":"100","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_Z","text":"z",
                "sk":[
                  {"id":"K_017A"},
                  {"id":"K_1E91"},
                  {"id":"K_017E"},
                  {"id":"K_01B6"},
                  {"id":"K_1E95"},
                  {"id":"K_017C"},
                  {"id":"K_1E93"},
                  {"id":"K_2C6C"},
                  {"id":"K_0292"},
                  {"id":"K_01EF"}
                ]
              },
              {"id":"K_X","text":"x",
                "sk":[
                  {"id":"K_1E8D"},
                  {"id":"K_1E8B"}
                ]
              },
              {"id":"K_C","text":"c",
                "sk":[
                  {"id":"K_0107"},
                  {"id":"K_0109"},
                  {"id":"K_010D"},
                  {"id":"K_010B"},
                  {"id":"K_00E7"}
                ]
              },
              {"id":"K_V","text":"v",
                "sk":[
                  {"id":"K_1E7D"},
                  {"id":"K_1E7F"}
                ]
              },
              {"id":"K_B","text":"b",
                "sk":[
                  {"id":"K_0180"},
                  {"id":"K_1E07"},
                  {"id":"K_1E03"},
                  {"id":"K_1E05"}
                ]
              },
              {"id":"K_N","text":"n",
                "sk":[
                  {"id":"K_014B"},
                  {"id":"K_01F9"},
                  {"id":"K_0144"},
                  {"id":"K_0148"},
                  {"id":"K_00F1"},
                  {"id":"K_1E49"},
                  {"id":"K_1E45"},
                  {"id":"K_1E47"},
                  {"id":"K_0146"},
                  {"id":"K_0149"},
                  {"id":"K_01CC"}
                ]
              },
              {"id":"K_M","text":"m",
                "sk":[
                  {"id":"K_1E3F"},
                  {"id":"K_1E41"},
                  {"id":"K_1E43"}
                ]
              },
              {"id":"K_PERIOD","text":".",
                "sk":[
                {"id":"K_COMMA","text":","},
                {"id":"K_0021"},
                {"id":"K_003F"},
                {"id":"K_0027"},
                {"id":"K_005C"},
                {"id":"K_003A"},
                {"id":"K_003B"}                
                ]
              },
              {"id":"K_BKSP","text":"BkSp","width":"10","font":"Arial","fontsize":"0.65em","sp":"1"}
              ]
          },
          {
            "id":"4",
            "key":[
              {"id":"K_LOPT","width":"150","text":"","sp":"1"},
              {"id":"K_NUMLOCK","text":"123...","font":"Arial","fontsize":"0.65em","sp":"1","nextlayer":"numeric","width":"150"},
              {"sp":"10","width":"20"},
              {"id":"K_SPACE","width":"380","sp":"0"},
              {"sp":"10","width":"20"},
              {"id":"K_ENTER","text":"Enter","width":"150","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_ROPT","width":"100","text":"","sp":"1"}
              ]
          }
          ]
      },
      {  
        "id":"shift",
        "row":[
          {
            "id":"1",
            "key":[
              {"id":"K_Q","text":"Q",
                "sk":[
                  {"id":"K_A78B"}
                ]
              },
              {"id":"K_W","text":"W",
                "sk":[
                  {"id":"K_1E80"},
                  {"id":"K_1E82"},
                  {"id":"K_0174"},
                  {"id":"K_1E84"},
                  {"id":"K_1E86"},
                  {"id":"K_1E88"}
                ]
              },
              {"id":"K_E","text":"E",
                "sk":[
                  {"id":"K_00C8"},
                  {"id":"K_0204"},
                  {"id":"K_00C9"},
                  {"id":"K_00CA"},
                  {"id":"K_011A"},
                  {"id":"K_0206"},
                  {"id":"K_0114"},
                  {"id":"K_1EBC"},
                  {"id":"K_0112"},
                  {"id":"K_00CB"},
                  {"id":"K_0116"},
                  {"id":"K_1EB8"},
                  {"id":"K_0118"},
                  {"id":"K_018F"},
                  {"id":"K_0190"}
                ]
              },
              {"id":"K_R","text":"R",
                "sk":[
                  {"id":"K_0210"},
                  {"id":"K_0154"},
                  {"id":"K_0158"},
                  {"id":"K_0212"},
                  {"id":"K_024C"},
                  {"id":"K_1E5E"},
                  {"id":"K_1E58"},
                  {"id":"K_1E5A"},
                  {"id":"K_0156"}
                ]
              },
              {"id":"K_T","text":"T",
                "sk":[
                  {"id":"K_0164"},
                  {"id":"K_0166"},
                  {"id":"K_1E6E"},
                  {"id":"K_1E6A"},
                  {"id":"K_1E6C"},
                  {"id":"K_0162"},
                  {"id":"K_00DE"}
                ]
              },
              {"id":"K_Y","text":"Y",
                "sk":[
                  {"id":"K_1EF2"},
                  {"id":"K_00DD"},
                  {"id":"K_0176"},
                  {"id":"K_1EF8"},
                  {"id":"K_0232"},
                  {"id":"K_0178"},
                  {"id":"K_1E8E"},
                  {"id":"K_1EF4"}
                ]
              },
              {"id":"K_U","text":"U",
                "sk":[
                  {"id":"K_00D9"},
                  {"id":"K_0214"},
                  {"id":"K_00DA"},
                  {"id":"K_0170"},
                  {"id":"K_00DB"},
                  {"id":"K_01D3"},
                  {"id":"K_0216"},
                  {"id":"K_016C"},
                  {"id":"K_0168"},
                  {"id":"K_016A"},
                  {"id":"K_00DC"},
                  {"id":"K_016E"},
                  {"id":"K_1EE4"},
                  {"id":"K_0172"}
                ]
              },
              {"id":"K_I","text":"I",
                "sk":[
                  {"id":"K_00CC"},
                  {"id":"K_0208"},
                  {"id":"K_00CD"},
                  {"id":"K_00CE"},
                  {"id":"K_01CF"},
                  {"id":"K_020A"},
                  {"id":"K_012C"},
                  {"id":"K_0128"},
                  {"id":"K_012A"},
                  {"id":"K_00CF"},
                  {"id":"K_0130"},
                  {"id":"K_1ECA"},
                  {"id":"K_012E"},
                  {"id":"K_019D"}
                ]
              },
              {"id":"K_O","text":"O",
                "sk":[
                  {"id":"K_00D2"},
                  {"id":"K_020C"},
                  {"id":"K_00D3"},
                  {"id":"K_0150"},
                  {"id":"K_00D4"},
                  {"id":"K_01D1"},
                  {"id":"K_020E"},
                  {"id":"K_014E"},
                  {"id":"K_00D5"},
                  {"id":"K_014C"},
                  {"id":"K_00D6"},
                  {"id":"K_022E"},
                  {"id":"K_1ECC"},
                  {"id":"K_01EA"},
                  {"id":"K_019F"},
                  {"id":"K_00D8"},
                  {"id":"K_0186"},
                  {"id":"K_0152"},
                  {"id":"K_01A2"}
                ]
              },
              {"id":"K_P","text":"P",
                "sk":[
                  {"id":"K_1E54"},
                  {"id":"K_0050"},
                  {"id":"K_1E56"}
                ]
              }
              ]
          },
          {
            "id":"2",
            "key":[
              {"id":"K_A","text":"A","pad":"40",
                "sk":[
                  {"id":"K_00C0"},
                  {"id":"K_0200"},
                  {"id":"K_00C1"},
                  {"id":"K_00C2"},
                  {"id":"K_01CD"},
                  {"id":"K_0202"},
                  {"id":"K_0102"},
                  {"id":"K_00C3"},
                  {"id":"K_0100"},
                  {"id":"K_00C4"},
                  {"id":"K_00C5"},
                  {"id":"K_0226"},
                  {"id":"K_1EA0"},
                  {"id":"K_0104"},
                  {"id":"K_00C6"}
                ]
              },
              {"id":"K_S","text":"S",
                "sk":[
                  {"id":"K_015A"},
                  {"id":"K_015C"},
                  {"id":"K_0160"},
                  {"id":"K_1E60"},
                  {"id":"K_1E62"},
                  {"id":"K_015E"},
                  {"id":"K_1E9E"}
                ]
              },
              {"id":"K_D","text":"D",
                "sk":[
                  {"id":"K_010E"},
                  {"id":"K_0110"},
                  {"id":"K_1E0E"},
                  {"id":"K_1E0A"},
                  {"id":"K_1E0C"},
                  {"id":"K_1E10"},
                  {"id":"K_00D0"},
                  {"id":"K_01C5"},
                  {"id":"K_01C4"}

                ]
              },
              {"id":"K_F","text":"F",
                "sk":[
                  {"id":"K_1E1E"}
                ]
              },
              {"id":"K_G","text":"G",
                "sk":[
                  {"id":"K_01F4"},
                  {"id":"K_011C"},
                  {"id":"K_01E6"},
                  {"id":"K_011E"},
                  {"id":"K_0047"},
                  {"id":"K_1E20"},
                  {"id":"K_0120"},
                  {"id":"K_0122"},
                  {"id":"K_0241"},
                  {"id":"K_01E4"}
                ]
              },
              {"id":"K_H","text":"H",
                "sk":[
                  {"id":"K_0124"},
                  {"id":"K_021E"},
                  {"id":"K_1E2A"},
                  {"id":"K_0126"},
                  {"id":"K_1E26"},
                  {"id":"K_1E22"},
                  {"id":"K_1E24"},
                  {"id":"K_1E28"}
                ]
              },
              {"id":"K_J","text":"J",
                "sk":[
                  {"id":"K_0134"},
                  {"id":"K_0248"}
                ]
              },
              {"id":"K_K","text":"K",
                "sk":[
                  {"id":"K_1E30"},
                  {"id":"K_01E8"},
                  {"id":"K_1E34"},
                  {"id":"K_1E32"},
                  {"id":"K_0136"}
                ]
              },
              {"id":"K_L","text":"L",
                "sk":[
                  {"id":"K_0139"},
                  {"id":"K_013D"},
                  {"id":"K_2C62"},
                  {"id":"K_0141"},
                  {"id":"K_1E3A"},
                  {"id":"K_013F"},
                  {"id":"K_1E36"},
                  {"id":"K_013B"},
                  {"id":"K_01C8"},
                  {"id":"K_01C7"}
                ]
              },
              {"sp":"10","width":"10"}
              ]
          },
          {
            "id":"3",
            "key":[
              {"id":"K_SHIFT","text":"abc","width":"100","font":"Arial","fontsize":"0.65em","sp":"2"},
              {"id":"K_Z","text":"Z",
                "sk":[
                  {"id":"K_021C"},
                  {"id":"K_0179"},
                  {"id":"K_1E90"},
                  {"id":"K_017D"},
                  {"id":"K_01B5"},
                  {"id":"K_1E94"},
                  {"id":"K_017B"},
                  {"id":"K_1E92"},
                  {"id":"K_2C6B"},
                  {"id":"K_01B7"},
                  {"id":"K_01EE"}
                ]
              },
              {"id":"K_X","text":"X",
                "sk":[
                  {"id":"K_1E8C"},
                  {"id":"K_1E8A"}
                ]
              },
              {"id":"K_C","text":"C",
                "sk":[
                  {"id":"K_0106"},
                  {"id":"K_0108"},
                  {"id":"K_010C"},
                  {"id":"K_010A"},
                  {"id":"K_00C7"}
                ]
              },
              {"id":"K_V","text":"V",
                "sk":[
                  {"id":"K_1E7C"},
                  {"id":"K_1E7E"}
                ]
              },
              {"id":"K_B","text":"B",
                "sk":[
                  {"id":"K_0243"},
                  {"id":"K_1E06"},
                  {"id":"K_1E02"},
                  {"id":"K_1E04"}
                ]
              },
              {"id":"K_N","text":"N",
                "sk":[
                  {"id":"K_014A"},
                  {"id":"K_01F8"},
                  {"id":"K_0143"},
                  {"id":"K_0147"},
                  {"id":"K_00D1"},
                  {"id":"K_1E48"},
                  {"id":"K_1E44"},
                  {"id":"K_1E46"},
                  {"id":"K_0145"},
                  {"id":"K_01CB"},
                  {"id":"K_01CA"}
                ]
              },
              {"id":"K_M","text":"M",
                "sk":[
                  {"id":"K_1E3E"},
                  {"id":"K_1E40"},
                  {"id":"K_1E42"}
                ]
              },
              {"id":"K_PERIOD","text":".","layer":"default",
                "sk":[
                {"id":"K_COMMA","text":","},
                {"id":"K_0021"},
                {"id":"K_003F"},
                {"id":"K_0027"},
                {"id":"K_005C"},
                {"id":"K_003A"},
                {"id":"K_003B"}                
                ]
              },
              {"id":"K_BKSP","text":"BkSp","width":"10","font":"Arial","fontsize":"0.65em","sp":"1"}
              ]
          },
          {
            "id":"4",
            "key":[
              {"id":"K_LOPT","width":"150","text":"","sp":"1"},
              {"id":"K_NUMLOCK","text":"123...","font":"Arial","fontsize":"0.65em","sp":"1","nextlayer":"numeric","width":"150"},
              {"sp":"10","width":"20"},
              {"id":"K_SPACE","width":"380","sp":"0"},
              {"sp":"10","width":"20"},
              {"id":"K_ENTER","text":"Enter","width":"150","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_ROPT","width":"100","text":"","sp":"1"}
              ]
          }
          ]
      },
      {
        "id":"numeric",
        "row":[
          {
            "id":"1",
            "key":[
              {"id":"K_1","text":"1","sp":"0",
                "sk":[
                  {"id":"K_00B9"},
                  {"id":"K_00BD"},
                  {"id":"K_2153"},
                  {"id":"K_00BC"},
                  {"id":"K_2155"},
                  {"id":"K_2159"},
                  {"id":"K_215B"}
                ]              
              },
              {"id":"K_2","text":"2","sp":"0",
                "sk":[
                  {"id":"K_00B2"},
                  {"id":"K_2154"},
                  {"id":"K_2156"}                
                ]              
              },
              {"id":"K_3","text":"3","sp":"0",
                "sk":[
                  {"id":"K_00B3"},
                  {"id":"K_00BE"},
                  {"id":"K_2157"},
                  {"id":"K_215C"}                
                ]              
              },
              {"id":"K_4","text":"4","sp":"0",
                "sk":[
                  {"id":"K_2074"},
                  {"id":"K_2158"}                
                ]              
              },
              {"id":"K_5","text":"5","sp":"0",
                "sk":[
                  {"id":"K_2075"},
                  {"id":"K_215A"},
                  {"id":"K_215D"}
                ]              
              },
              {"id":"K_6","text":"6","sp":"0",
                "sk":[
                  {"id":"K_2076"}
                ]              
              },
              {"id":"K_7","text":"7","sp":"0",
                "sk":[
                  {"id":"K_2077"},
                  {"id":"K_215E"}
                ]              
              },
              {"id":"K_8","text":"8","sp":"0",
                "sk":[
                  {"id":"K_2078"}                
                ]              
              },
              {"id":"K_9","text":"9","sp":"0",
                "sk":[
                  {"id":"K_2079"}
                ]              
              },
              {"id":"K_0","text":"0","sp":"0",
                "sk":[
                  {"id":"K_2070"}
                ]              
              }
              ]
          },
          {
            "id":"2",
            "key":[
            
              {"id":"K_0024","pad":"40"},
              {"id":"K_0040"},
              {"id":"K_0023"},
              {"id":"K_0025",
                "sk":[
                  {"id":"K_2030"},
                  {"id":"K_2031"}
                ]
              },
              {"id":"K_0026"},
              {"id":"K_005F"},
              {"id":"K_003D"},
              {"id":"K_007C"},
              {"id":"K_005C"},
              {"sp":"10","width":"10"}
              ]
          },
          {
            "id":"3",
            "key":[
              {"id":"K_SHIFT","text":"~¿¡","width":"100","font":"Arial","fontsize":"0.65em","sp":"1","nextlayer":"symbol"},
              {"id":"K_005B",
                "sk":[
                  {"id":"K_007B"},
                  {"id":"K_00AB"},
                  {"id":"K_003C"}
                ]
              },
              {"id":"K_0028"},
              {"id":"K_0029"},
              {"id":"K_005D",
                "sk":[
                  {"id":"K_007D"},
                  {"id":"K_00BB"},
                  {"id":"K_003E"}
                ]
              },
              {"id":"K_002B"},
              {"id":"K_002D"},
              {"id":"K_002A"},
              {"id":"K_002F"},
              {"id":"K_BKSP","text":"BkSp","width":"10","font":"Arial","fontsize":"0.65em","sp":"1"}
              ]
          },
          {
            "id":"4",
            "key":[
              {"id":"K_LOPT","width":"150","text":"","sp":"1"},
              {"id":"K_NUMLOCK","text":"abc...","font":"Arial","fontsize":"0.65em","sp":"2","nextlayer":"default","width":"150"},
              {"sp":"10","width":"20"},
              {"id":"K_SPACE","width":"380","sp":"0"},
              {"sp":"10","width":"20"},
              {"id":"K_ENTER","text":"Enter","width":"150","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_ROPT","width":"100","text":"","sp":"1"}
              ]
          }
          ]
      },
      {
        "id":"symbol",
        "row":[
          {
            "id":"1",
            "key":[
              {"id":"K_0060"},
              {"id":"K_007E"},
              {"id":"K_005E"},
              {"id":"K_00A8"},
              {"id":"K_00B4"},
              {"id":"K_00B8"},
              {"id":"K_00AF"},
              {"id":"K_00BF"},
              {"id":"K_00A1"},
              {"id":"K_00AC"}
              ]
          },
          {
            "id":"2",
            "key":[
              {"id":"K_00AA","pad":"40"},
              {"id":"K_00BA"},
              {"id":"K_00B6"},
              {"id":"K_00A7"},
              {"id":"K_2021"},
              {"id":"K_2020"},
              {"id":"K_00A6"},
              {"id":"K_2122"},
              {"id":"K_2116"},
              {"sp":"10","width":"10"}
              ]
          },
          {
            "id":"3",
            "key":[
              {"id":"K_SHIFT","text":"€£¥","width":"100","font":"Arial","fontsize":"0.65em","sp":"2","nextlayer":"currency"},
              {"id":"K_00A9"},
              {"id":"K_2117"},
              {"id":"K_00AE"},
              {"id":"K_2014"},
              {"id":"K_2013"},
              {"id":"K_2022"},
              {"id":"K_00B7"},
              {"id":"K_2026",
                "sk":[
                  {"id":"K_00B1"},
                  {"id":"K_00D7"},
                  {"id":"K_00F7"},
                  {"id":"K_00B5"},
                  {"id":"K_00B0"},
                  {"id":"K_2031"}
                ]              
              },
              {"id":"K_BKSP","text":"BkSp","width":"10","font":"Arial","fontsize":"0.65em","sp":"1"}
              ]
          },
          {
            "id":"4",
            "key":[
              {"id":"K_LOPT","width":"150","text":"","sp":"1"},
              {"id":"K_NUMLOCK","text":"abc...","font":"Arial","fontsize":"0.65em","sp":"2","nextlayer":"default","width":"150"},
              {"sp":"10","width":"20"},
              {"id":"K_SPACE", "width":"380","sp":"0"},
              {"sp":"10","width":"20"},
              {"id":"K_ENTER","text":"Enter","width":"150","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_ROPT","width":"100","text":"","sp":"1"}
              ]
          }          
          ]
      },
      {
        "id":"currency",
        "row":[
          {
            "id":"1",
            "key":[
              {"id":"K_00A2"},
              {"id":"K_20AC"},
              {"id":"K_20A4"},
              {"id":"K_00A3"},
              {"id":"K_20AA"},
              {"id":"K_20A8"},
              {"id":"K_20B9"},
              {"id":"K_20A9"},
              {"id":"K_00A5"},
              {"id":"K_00A4"}
              ]
          },
          {
            "id":"2",
            "key":[
              {"id":"K_20AB","pad":"40"},
              {"id":"K_20AF"},
              {"id":"K_20B1"},
              {"id":"K_20A3"},
              {"id":"K_20B0"},
              {"id":"K_20B2"},
              {"id":"K_20B4"},
              {"id":"K_20A1"},
              {"id":"K_20AD"},
              {"sp":"10","width":"10"}
              ]
          },
          {
            "id":"3",
            "key":[
              {"id":"K_SHIFT","text":"123","width":"100","font":"Arial","fontsize":"0.65em","sp":"2","nextlayer":"numeric"},
              {"id":"K_20A6"},
              {"id":"K_20A7"},
              {"id":"K_20AE"},
              {"id":"K_0BF9"},
              {"id":"K_09F3"},
              {"id":"K_0E3F"}, 
              {"sp":"9"},
              {"sp":"9"},
              {"id":"K_BKSP","text":"BkSp","width":"10","font":"Arial","fontsize":"0.65em","sp":"1"}              
              ]
          },
          {
            "id":"4",
            "key":[
              {"id":"K_LOPT","width":"150","text":"","sp":"1"},
              {"id":"K_NUMLOCK","text":"abc...","font":"Arial","fontsize":"0.65em","sp":"2","nextlayer":"default","width":"150"},
              {"sp":"10","width":"20"},
              {"id":"K_SPACE", "width":"380","sp":"0"},
              {"sp":"10","width":"20"},
              {"id":"K_ENTER","text":"Enter","width":"150","font":"Arial","fontsize":"0.65em","sp":"1"},
              {"id":"K_ROPT","width":"100","text":"","sp":"1"}
              ]
          }          
          ]
      }                                                      
      ]
    }  
  }    
;