name: "🐛 Bug report"
title: "bug: "
labels: ["bug"]
description: Report a bug in Keyman
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        Before you submit this bug report, have you searched other reports for this bug?
          https://github.com/keymanapp/keyman/issues?q=is%3Aissue+label%3Abug

        * If you find a matching issue, go ahead and add a comment on that issue.
        * If you find related issues, make sure you list them below.

        You may also wish to discuss your bug report with the Keyman community at:
          https://community.software.sil.org/c/keyman

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of the bug. Include details of affected applications if relevant."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        When reporting on issues with unexpected output, it is very helpful to include the exact sequence of keys, the output expected, and the output received, for example:

        ```
        Typed: <kbd>a</kbd> <kbd>b</kbd> <kbd>Shift</kbd>+<kbd>C</kbd>
        Received: "abc"
        Expected: "abC"
        ```

        It's optional to use `<kbd></kbd>` to get key icons in the keying sequence, but it does add clarity; alternatively, do something like this:

        ```
        Typed: a b shift+C
        ```

        Tip: use key names such as `spacebar` rather than just a space!

  - type: textarea
    id: repro
    attributes:
      label: "Reproduce the bug"
      description: |
        Write up the steps you took which triggered the bug. Be as precise as possible; you can paste screenshots and/or videos if you wish.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."

  - type: textarea
    id: related-issues
    attributes:
      label: "Related issues"
      description: "After completing your issue search, you may find some that seem related; list them here"

  - type: markdown
    attributes:
      value: ---

  - type: checkboxes
    id: context-product
    attributes:
      label: "Keyman apps"
      description: "Which Keyman app(s) are you experiencing this problem with?"
      options:
        - label: Keyman for Android
        - label: Keyman for iPhone and iPad
        - label: Keyman for Linux
        - label: Keyman for macOS
        - label: Keyman for Windows
        - label: Keyman Developer
        - label: KeymanWeb
        - label: Other - give details at bottom of form

  - type: input
    id: context-version
    attributes:
      label: "Keyman version"
      placeholder: "e.g. 15.0.270"

  - type: input
    id: context-os
    attributes:
      label: "Operating system"
      placeholder: "e.g. Windows 10 21H2, macOS 12 Monterey, Ubuntu 22.04, Android 12, iOS 16, ..."

  - type: input
    id: context-device
    attributes:
      label: "Device"
      placeholder: "e.g. iPhone 14, Windows laptop, Macbook Pro, ..."

  - type: input
    id: context-app
    attributes:
      label: "Target application"
      description: "If applicable, the app(s) and app version(s) you are trying to use with Keyman when experiencing this problem"
      placeholder: "e.g. Office 365, ..."

  - type: input
    id: context-browser
    attributes:
      label: "Browser"
      description: "If applicable, the web browser and version you are trying to use with KeymanWeb when experiencing this problem"
      placeholder: "e.g. Firefox 104, ..."

  - type: markdown
    attributes:
      value: ---

  - type: input
    id: context-keyboard
    attributes:
      label: "Keyboard name"
      description: "If applicable, the filename of the keyboard you are using when experiencing this problem"
      placeholder: "e.g. khmer_angkor"

  - type: input
    id: context-keyboard-version
    attributes:
      label: "Keyboard version"
      placeholder: "e.g. 1.0.1"

  - type: input
    id: context-keyboard-language
    attributes:
      label: "Language name"
      placeholder: "e.g. Khmer"

  - type: textarea
    id: context-additional
    attributes:
      label: "Additional context"
      description: "Any other context or notes about the problem here"
