/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by S. Schmitt on 2025-05-12
 *
 * Write Keyman .kmn files from an in-memory representation generated
 *
 */

import { CompilerCallbacks, CompilerOptions } from "@keymanapp/developer-utils";
import { KeylayoutToKmnConverter, ProcessedData, Rule } from './keylayout-to-kmn-converter.js';
import { ConverterMessages } from '../converter-messages.js';
import KEYMAN_VERSION from "@keymanapp/keyman-version";

interface MessageCharacter {
  message: string;
  character: string;
};

interface RuleReview {
  warningMessages: string[];
  extraWarning: string;
  type: 'RuleReview' | 'UnavailableModifier' | 'UnavailableSuperiorRule' |
  'DuplicateRule' | 'AmbiguousRule';
  compare_type: string;
  earlier_later: [boolean, boolean];
  dk_bothPrefix_prevdk_dk: [string, string];// todo rename to dk_prefix
  prevDk_modifier: string;
  prevDk_key: string;
  dk_bothId_prevdk_dk: [number, number];// todo rename to dk_id
  Dk_modifier: string;
  Dk_key: string;
  modifier: string;
  key: string;
  output: string;
};

interface UnavailableModifier extends RuleReview {
  type: 'UnavailableModifier';
};
interface UnavailableSuperiorRule extends RuleReview {
  type: 'UnavailableSuperiorRule';
};
interface DuplicateRules extends RuleReview {
  type: 'DuplicateRule';
};
interface AmbiguousRules extends RuleReview {
  type: 'AmbiguousRule';
};


export class KmnFileWriter {

  constructor(private callbacks: CompilerCallbacks, private options: CompilerOptions) { };

  /**
   * @brief  member function to write data from object to a Uint8Array
   * @param  dataUkelele the array holding all keyboard data
   * @return a Uint8Array holding data
   */
  public write(dataUkelele: ProcessedData): Uint8Array {
    let data: string = "\n";

    // top part of kmn file: STORES
    const dataStores = this.writeKmnFileHeader(dataUkelele);

    // bottom part of kmn file: RULES
    const dataRules = this.writeDataRules(dataUkelele);

    if (dataRules)
      data += dataStores + dataRules;

    try {
      return new TextEncoder().encode(data);
    } catch (err) {
      this.callbacks.reportMessage(ConverterMessages.Error_UnableToWrite({ outputFilename: dataUkelele.kmnFilename, errorText: err }));
      return null;
    }
  }

  /**
   * @brief  member function to create data for the header (stores) that will be printed to the resulting kmn file
   * @param  dataUkelele an object containing all data read from a .keylayout file
   * @return string -  all stores to be printed
   */
  public writeKmnFileHeader(dataUkelele: ProcessedData): string {

    let data: string = "";

    data += "c ..................................................................................................................\n";
    data += "c ..................................................................................................................\n";
    data += "c Keyman keyboard generated by kmn-convert version: " + KEYMAN_VERSION.VERSION + "\n";
    data += "c from Ukelele file: " + dataUkelele.keylayoutFilename + "\n";
    data += "c ..................................................................................................................\n";
    data += "c ..................................................................................................................\n";
    data += "\n";

    data += "store(&TARGETS) \'desktop\'\n";

    data += "\n";
    data += "begin Unicode > use(main)\n\n";
    data += "group(main) using keys\n\n";

    data += "\n";
    return data;
  }

  /**
   * @brief  member function to create data from rules that will be printed to the resulting kmn file
   * @param  dataUkelele an object containing all data read from a .keylayout file
   * @return string -  all rules to be printed
   */
  public writeDataRules(dataUkelele: ProcessedData): string {

    const keylayoutKmnConverter = new KeylayoutToKmnConverter(this.callbacks, this.options);
    let data: string = "";

    // filter array of all rules and remove duplicates
    // during the process of creating Rule[], duplicate rules might occur
    // (e.g. when in a keylayout file the same modifiers occur in several behaviors thus producing the same rules).
    // This is to filter out those duplicate Rule objects
    const uniqueDataRules: Rule[] = dataUkelele.rules.filter((curr) => {
      return (!(curr.output === undefined)
        && (curr.key !== "")
        && ((curr.ruleType === "C0")
          || (curr.ruleType === "C1")
          || (curr.ruleType === "C2" && (curr.deadkey !== ""))
          || (curr.ruleType === "C3" && (curr.deadkey !== "") && (curr.prevDeadkey !== "")))
      );
    }).reduce((unique, o) => {

      if (!unique.some((obj: Rule) =>
        new TextDecoder().decode(obj.output) === new TextDecoder().decode(o.output)

        && obj.ruleType === o.ruleType
        && obj.modifierKey === o.modifierKey
        && obj.key === o.key

        && obj.modifierDeadkey === o.modifierDeadkey
        && obj.deadkey === o.deadkey

        && obj.modifierPrevDeadkey === o.modifierPrevDeadkey
        && obj.prevDeadkey === o.prevDeadkey)
      ) {
        unique.push(o);
      }
      return unique;
    }, []);

    //................................................ C0 C1 ................................................................

    for (let k = 0; k < uniqueDataRules.length; k++) {

      if ((uniqueDataRules[k].ruleType === "C0") || (uniqueDataRules[k].ruleType === "C1")) {

        // lookup key nr of the key which is being processed
        let keyNr: number = 0;
        for (let j = 0; j <= KeylayoutToKmnConverter.MAX_KEY_IDENTIFIER; j++) {
          if (keylayoutKmnConverter.mapUkeleleKeycodeToVK(j) === uniqueDataRules[k].key) {
            keyNr = j;
            break;
          }
        }

        // skip keyNr 48 (K_TAB) and 36 (K_ENTER)
        if ((keyNr === 48) || (keyNr === 36)) {
          continue;
        }

        // add a line after rules of each key
        if ((k > 1) && (uniqueDataRules[k - 1].key !== uniqueDataRules[k].key) && (uniqueDataRules[k - 1].ruleType === uniqueDataRules[k].ruleType)) {
          data += '\n';
        }

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;
        const warnText = this.reviewRules(uniqueDataRules, k);

        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14569 use functions from util instead of the ones in this class
        // const outputUnicodeCharacter = util.convertToUnicodeCharacter(outputCharacter);
        // const outputUnicodeCodePoint = util.convertToUnicodeCodePoint(outputCharacter);

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] = characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[2].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            if (versionOutputCharacter === "'") {
              data += warningTextToWrite
                + "+ ["
                + (uniqueDataRules[k].modifierKey + ' ' + uniqueDataRules[k].key).trim()
                + `]  >  \"`
                + versionOutputCharacter
                + '\"\n';
            }
            else {
              // surround all output characters with '' (e.g. + [K_A]  >  'A')
              // but don`t for U+xxxx in control character message (e.g.  c Use of a control character + [K_A]  >  U+0011 )
              if (warningTextToWrite.indexOf("control character") === -1) {
                data += warningTextToWrite
                  + "+ ["
                  + (uniqueDataRules[k].modifierKey + ' ' + uniqueDataRules[k].key).trim()
                  + `]  >  \'`
                  + versionOutputCharacter
                  + '\'\n';
              }
              else {
                data += warningTextToWrite
                  + "+ ["
                  + (uniqueDataRules[k].modifierKey + ' ' + uniqueDataRules[k].key).trim()
                  + `]  >  `
                  + versionOutputCharacter
                  + '\n';
              }
            }
          }
        }
      }
    }

    //................................................ C2 ...................................................................
    for (let k = 0; k < uniqueDataRules.length; k++) {

      if (uniqueDataRules[k].ruleType === "C2") {

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;
        const warnText = this.reviewRules(uniqueDataRules, k);

        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14569 use functions from util instead of the ones in this class
        // const outputUnicodeCharacter = util.convertToUnicodeCharacter(outputCharacter);
        // const outputUnicodeCodePoint = util.convertToUnicodeCodePoint(outputCharacter);

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] = characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[1].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[1].length > 0)) {
            warningTextToWrite = warnText[1];
          }

          if (!((warnText[1].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "+ [" + (uniqueDataRules[k].modifierDeadkey + " "
                + uniqueDataRules[k].deadkey).trim()
              + "]  >  dk(A" + String(uniqueDataRules[k].idDeadkey)
              + ")\n";
          }
        }

        if ((warnText[2].indexOf("duplicate") < 0)) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            if (versionOutputCharacter === "'") {
              data += warningTextToWrite
                + "dk(A"
                + (String(uniqueDataRules[k].idDeadkey) + ") + ["
                  + uniqueDataRules[k].modifierKey).trim()
                + " "
                + uniqueDataRules[k].key + ']  >  \"'
                + versionOutputCharacter
                + '\"\n';
            }
            else {
              // surround all output characters with '' (e.g. + [K_A]  >  'A')
              // but don`t for U+xxxx in control character message (e.g.  c Use of a control character + [K_A]  >  U+0011 )
              if (warningTextToWrite.indexOf("control character") === -1) {
                data += warningTextToWrite
                  + "dk(A"
                  + (String(uniqueDataRules[k].idDeadkey) + ") + ["
                    + uniqueDataRules[k].modifierKey).trim()
                  + " "
                  + uniqueDataRules[k].key + "]  >  \'"
                  + versionOutputCharacter
                  + "\'\n";
              } else {
                data += warningTextToWrite
                  + "dk(A"
                  + (String(uniqueDataRules[k].idDeadkey) + ") + ["
                    + uniqueDataRules[k].modifierKey).trim()
                  + " "
                  + uniqueDataRules[k].key + "]  >  "
                  + versionOutputCharacter
                  + "\n";
              }
            }
          }
          data += "\n";
        }
      }
    }

    //................................................ C3 ...................................................................

    for (let k = 0; k < uniqueDataRules.length; k++) {
      if (uniqueDataRules[k].ruleType === "C3") {

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;

        const warnText = this.reviewRules(uniqueDataRules, k);
        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14569 use functions from util instead of the ones in this class

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] = characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[0].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";

          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[0].length > 0)) {
            warningTextToWrite = warnText[0];
          }

          if (!((warnText[0].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "+ ["
              + (uniqueDataRules[k].modifierPrevDeadkey + " "
                + uniqueDataRules[k].prevDeadkey).trim()
              + "]   >   dk(A"
              + String(uniqueDataRules[k].idPrevDeadkey) + ")\n";
          }
        }

        if (warnText[1].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[1].length > 0)) {
            warningTextToWrite = warnText[1];
          }

          if (!((warnText[1].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "dk(A" + (String(uniqueDataRules[k].idPrevDeadkey) + ")  + ["
                + uniqueDataRules[k].modifierDeadkey).trim()
              + " "
              + uniqueDataRules[k].deadkey
              + "]  >  dk(B"
              + String(uniqueDataRules[k].idDeadkey)
              + ")\n";
          }
        }

        if (warnText[2].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            // surround all output characters with '' (e.g. + [K_A]  >  'A')
            // but don`t for U+xxxx in control character message (e.g.  c Use of a control character + [K_A]  >  U+0011 )
            if (warningTextToWrite.indexOf("control character") === -1) {
              data += warningTextToWrite + "dk(B"
                + (String(uniqueDataRules[k].idDeadkey)
                  + ") + ["
                  + uniqueDataRules[k].modifierKey).trim()
                + " "
                + uniqueDataRules[k].key
                + "]  >  \'"
                + versionOutputCharacter
                + "\'\n";
            } else {
              data += warningTextToWrite + "dk(B"
                + (String(uniqueDataRules[k].idDeadkey)
                  + ") + ["
                  + uniqueDataRules[k].modifierKey).trim()
                + " "
                + uniqueDataRules[k].key
                + "]  >  "
                + versionOutputCharacter
                + "\n";
            }
          }
        }
        if ((warnText[0].indexOf("duplicate") < 0) || (warnText[1].indexOf("duplicate") < 0) || (warnText[2].indexOf("duplicate") < 0)) {
          data += "\n";
        }
      }
    }
    return data;
  }

  /**
   * @brief  take a child object of RuleReview and return the appropriate warning message
   * @param  inObj : an object containing all data
   * @return outMsg the warning message
   */
  public createWarningText(inObj: RuleReview, pos: number): string[] {

    const outMsg = [...inObj.warningMessages];

    if (inObj.compare_type === 'unav_C0_C1') {
      outMsg[pos] = "unavailable modifier ";
    }

    if (inObj.compare_type === 'unav_C2') {
      // if the dk is unavailable, the dependant C0 rules and theIr modifiers need to get a warning 'unavailable superior rule '
      if (inObj.Dk_modifier) {
        outMsg[1] = "unavailable modifier ";
        outMsg[2] = "unavailable superior rule ( ["
          + inObj.Dk_modifier + " "
          + inObj.Dk_key
          + "]  >  dk("
          + inObj.dk_bothPrefix_prevdk_dk[1]
          + inObj.dk_bothId_prevdk_dk[1]
          + ") ) : ";
      }

      if (inObj.modifier) {
        outMsg[2] = "unavailable modifier ";
      }
    }

    if (inObj.compare_type === 'unav_C3') {

      // if the dk is unavailable, the dependant C0 rules and theIr modifiers need to get a warning 'unavailable superior rule '
      if (inObj.prevDk_modifier) {
        outMsg[0] = "unavailable modifier ";
        outMsg[1] = "unavailable superior rule ( ["
          + inObj.prevDk_modifier + " "
          + inObj.prevDk_key
          + "]  >  dk("
          + inObj.dk_bothPrefix_prevdk_dk[1]
          + inObj.dk_bothId_prevdk_dk[1]
          + ") ) : ";
      }


      // if the dk is unavailable, the dependant C0 rules and theIr modifiers need to get a warning 'unavailable superior rule '
      if (inObj.Dk_modifier) {
        outMsg[1] += "unavailable modifier ";
        outMsg[2] = "unavailable superior rule ( ["
          + inObj.Dk_modifier + " "
          + inObj.Dk_key
          + "]  >  dk("
          + inObj.dk_bothPrefix_prevdk_dk[1]
          + inObj.dk_bothId_prevdk_dk[1]
          + ") ) : ";
      }

      if (inObj.modifier) {
        outMsg[2] = "unavailable modifier ";
      }
    }

    if (inObj.compare_type === 'amb_1_1' || inObj.compare_type === 'dup_1_1') {

      outMsg[pos] = inObj.warningMessages[2]
        + ((inObj.type === 'AmbiguousRule') ? 'ambiguous ' : 'duplicate ') + "rule: "
        + (inObj.earlier_later[0] ? "earlier" : "later")
        + ": [" + inObj.modifier + " " + inObj.key + "]  >  \'"
        + inObj.output + "\' ";
    }


    if (inObj.compare_type === 'amb_2_2' || inObj.compare_type === 'dup_2_2'
      || inObj.compare_type === 'amb_2_1'
      || inObj.compare_type === 'amb_2_4') {

      const textsegment = (
        ((inObj.type === 'AmbiguousRule') ? 'ambiguous ' : 'duplicate ') + "rule: "
        + (inObj.earlier_later[0] ? "earlier" : "later")
        + ": [" + inObj.Dk_modifier + " " + inObj.Dk_key + "]  >  dk("
        + inObj.dk_bothPrefix_prevdk_dk[1] + inObj.dk_bothId_prevdk_dk[1] + ") ");

      if (outMsg[pos].indexOf(textsegment) === -1)
        outMsg[pos] += textsegment;
    }


    if (inObj.compare_type === 'amb_4_4' || inObj.compare_type === 'dup_4_4'
      || inObj.compare_type === 'amb_4_1'
      || inObj.compare_type === 'amb_4_2') {

      const textsegment = (
        ((inObj.type === 'AmbiguousRule') ? 'ambiguous ' : 'duplicate ') + "rule: "
        + (inObj.earlier_later[0] ? "earlier" : "later") + ": ["
        + inObj.prevDk_modifier + " " + inObj.prevDk_key + "]  >  dk("
        + inObj.dk_bothPrefix_prevdk_dk[0] + inObj.dk_bothId_prevdk_dk[0] + ") ");

      if (outMsg[pos].indexOf(textsegment) === -1)
        outMsg[pos] += textsegment;
    }


    if (inObj.compare_type === 'amb_5_5' || inObj.compare_type === 'dup_5_5') {

      const textsegment = (
        ((inObj.type === 'AmbiguousRule') ? 'ambiguous ' : 'duplicate ') + 'rule: '
        + (inObj.earlier_later[0] ? "earlier" : "later")
        + ': dk(' + inObj.dk_bothPrefix_prevdk_dk[1] + inObj.dk_bothId_prevdk_dk[1] + ") + ["
        + inObj.Dk_modifier + " " + inObj.Dk_key + "]  >  "
        + 'dk(' + inObj.dk_bothPrefix_prevdk_dk[0] + inObj.dk_bothId_prevdk_dk[0] + ") ");

      if (outMsg[pos].indexOf(textsegment) === -1)
        outMsg[pos] += textsegment;
    }


    if (inObj.compare_type === 'amb_6_3' || inObj.compare_type === 'dup_6_3'
      || inObj.compare_type === 'amb_3_3' || inObj.compare_type === 'dup_3_3'
      || inObj.compare_type === 'amb_6_6' || inObj.compare_type === 'dup_6_6') {

      const textsegment = (
        ((inObj.type === 'AmbiguousRule') ? 'ambiguous ' : 'duplicate ') + 'rule: ' +
        (inObj.earlier_later[0] ? "earlier" : "later")
        + ': dk(' + inObj.dk_bothPrefix_prevdk_dk[1] + inObj.dk_bothId_prevdk_dk[1] + ") + ["
        + inObj.modifier + " " + inObj.key + "]  >  \'" + inObj.output + "\' ");

      if (outMsg[pos].indexOf(textsegment) === -1)
        outMsg[pos] += textsegment;
    }

    return outMsg;
  }

  /**
   * @brief  member function to review rules for acceptable modifiers, duplicate or ambiguous rules and return an array containing possible warnings.
   *         Keyman can not handle duplicate rules so we need to make sure a rule is written only once by either omitting a duplicate rule or commenting out an ambiguous rule.
   *         Omitting rules and definition of comparisons e.g. 1-1, 2-4, 6-6
   *         see https://docs.google.com/document/d/12J3NGO6RxIthCpZDTR8FYSRjiMgXJDLwPY2z9xqKzJ0/edit?tab=t.0#heading=h.pcz8rjyrl5ug
   * @param  rule : Rule[] - an array of all rules
   * @param  index the index of a rule in Rule[]
   * @return a string[] containing possible warnings for a rule
   */
  public reviewRules(rule: Rule[], index: number): string[] {

    const unavailableModiWarnings = {
      type: 'UnavailableModifier',
      warningMessages: ['', '', ''],
    } as UnavailableModifier;

    const unavailableSuperiWarnings = {
      type: 'UnavailableSuperiorRule',
      warningMessages: ['', '', ''],
    } as UnavailableSuperiorRule;

    const duplicateWarnings = {
      type: 'DuplicateRule',
      warningMessages: ['', '', ''],
    } as DuplicateRules;

    const ambiguousWarnings = {
      type: 'AmbiguousRule',
      warningMessages: ['', '', ''],
    } as AmbiguousRules;

    const keylayoutKmnConverter = new KeylayoutToKmnConverter(this.callbacks, this.options);
    const warningText: string[] = Array(3).fill("");

    // ------------------------- check unavailable modifiers -------------------------

    if ((rule[index].ruleType === "C0") || (rule[index].ruleType === "C1")) {
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        unavailableModiWarnings.compare_type = 'unav_C0_C1';
        unavailableModiWarnings.warningMessages = this.createWarningText(unavailableModiWarnings, 2);
      }
    }


    else if (rule[index].ruleType === "C2") {
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierDeadkey)) {
        unavailableSuperiWarnings.compare_type = 'unav_C2';
        unavailableSuperiWarnings.dk_bothPrefix_prevdk_dk = ['C', 'A'];
        unavailableSuperiWarnings.dk_bothId_prevdk_dk = [rule[0].idPrevDeadkey, rule[0].idDeadkey];
        unavailableSuperiWarnings.Dk_modifier = rule[index].modifierDeadkey;
        unavailableSuperiWarnings.Dk_key = rule[index].deadkey;
        unavailableSuperiWarnings.warningMessages = this.createWarningText(unavailableSuperiWarnings, 2);
      }

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        unavailableModiWarnings.compare_type = 'unav_C2';
        unavailableModiWarnings.modifier = rule[index].modifierKey;
        unavailableModiWarnings.key = rule[index].key;
        unavailableModiWarnings.warningMessages = this.createWarningText(unavailableModiWarnings, 2);
      }
    }


    else if (rule[index].ruleType === "C3") {
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierPrevDeadkey)) {
        unavailableSuperiWarnings.compare_type = 'unav_C3';
        unavailableSuperiWarnings.dk_bothPrefix_prevdk_dk = ['C', 'A'];
        unavailableSuperiWarnings.dk_bothId_prevdk_dk = [rule[0].idPrevDeadkey, rule[0].idDeadkey];
        unavailableSuperiWarnings.prevDk_modifier = rule[index].modifierPrevDeadkey;
        unavailableSuperiWarnings.prevDk_key = rule[index].prevDeadkey;
        unavailableSuperiWarnings.warningMessages = this.createWarningText(unavailableSuperiWarnings, 2);
      }

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierDeadkey)) {
        unavailableSuperiWarnings.compare_type = 'unav_C3';
        unavailableSuperiWarnings.prevDk_modifier = '';
        unavailableSuperiWarnings.dk_bothPrefix_prevdk_dk = ['', 'B'];
        unavailableSuperiWarnings.dk_bothId_prevdk_dk = [rule[0].idPrevDeadkey, rule[0].idDeadkey];
        unavailableSuperiWarnings.Dk_modifier = rule[index].modifierDeadkey;
        unavailableSuperiWarnings.Dk_key = rule[index].deadkey;
        unavailableSuperiWarnings.warningMessages = this.createWarningText(unavailableSuperiWarnings, 2);
      }

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        unavailableModiWarnings.compare_type = 'unav_C3';
        unavailableModiWarnings.modifier = rule[index].modifierKey;
        unavailableModiWarnings.key = rule[index].key;
        unavailableModiWarnings.warningMessages = this.createWarningText(unavailableModiWarnings, 2);
      }
    }

    // ------------------------- check ambiguous/duplicate rules -------------------------

    if ((rule[index].ruleType === "C0") || (rule[index].ruleType === "C1")) {

      // 1-1: + [CAPS K_N]  > 'N' <-> + [CAPS K_N]  >  'A'
      const amb_1_1 = rule.filter((curr, idx) =>
        (curr.ruleType === "C0" || curr.ruleType === "C1")
        && curr.modifierPrevDeadkey === ""
        && curr.prevDeadkey === ""
        && curr.modifierDeadkey === ""
        && curr.deadkey === ""
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
        && idx < index
      );
      // 1-1: + [CAPS K_N]  > 'N' <-> + [CAPS K_N]  >  'N'
      const dup_1_1 = rule.filter((curr, idx) =>
        (curr.ruleType === "C0" || curr.ruleType === "C1")
        && curr.modifierPrevDeadkey === ""
        && curr.prevDeadkey === ""
        && curr.modifierDeadkey === ""
        && curr.deadkey === ""
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      // 4-1: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  'Ñ'
      const amb_4_1 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C3"))
        && curr.modifierPrevDeadkey === rule[index].modifierKey
        && curr.prevDeadkey === rule[index].key
      );

      // 2-1: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  'Ñ'
      const amb_2_1 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C2"))
        && curr.modifierDeadkey === rule[index].modifierKey
        && curr.deadkey === rule[index].key
      );

      if (amb_4_1.length > 0) {
        ambiguousWarnings.compare_type = 'amb_4_1';
        ambiguousWarnings.earlier_later = [false, true];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['C', 'A'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_4_1[0].idPrevDeadkey, amb_4_1[0].idDeadkey];
        ambiguousWarnings.prevDk_modifier = amb_4_1[0].modifierPrevDeadkey;
        ambiguousWarnings.prevDk_key = amb_4_1[0].prevDeadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 2);
      }

      if (amb_2_1.length > 0) {
        ambiguousWarnings.compare_type = 'amb_2_1';
        ambiguousWarnings.earlier_later = [false, true];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['C', 'A'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_2_1[0].idPrevDeadkey, amb_2_1[0].idDeadkey];
        ambiguousWarnings.Dk_modifier = amb_2_1[0].modifierDeadkey;
        ambiguousWarnings.Dk_key = amb_2_1[0].deadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 2);
      }

      if (amb_1_1.length > 0) {
        ambiguousWarnings.compare_type = 'amb_1_1';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.modifier = amb_1_1[0].modifierKey;
        ambiguousWarnings.key = amb_1_1[0].key;
        ambiguousWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(amb_1_1[0].output)).character;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 2);
      }

      if (dup_1_1.length > 0) {
        duplicateWarnings.compare_type = 'dup_1_1';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.modifier = dup_1_1[0].modifierKey;
        duplicateWarnings.key = dup_1_1[0].key;
        duplicateWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(dup_1_1[0].output)).character;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 2);
      }
    }


    if (rule[index].ruleType === "C2") {

      // 2-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C3)
      const amb_2_2 = rule.filter((curr, idx) =>
        curr.ruleType === "C2"
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey !== rule[index].idDeadkey
        && idx < index
      );

      // 2-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C11)
      const dup_2_2 = rule.filter((curr, idx) =>
        curr.ruleType === "C2"
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey
        && idx < index
      );

      //3-3: dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_3_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idDeadkey === rule[index].idDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      //3-3: dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_3_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idDeadkey === rule[index].idDeadkey
        && rule[index].uniqueDeadkey === 0
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      // 4-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(B11)
      const amb_4_2 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C3"))
        && curr.modifierPrevDeadkey === rule[index].modifierDeadkey
        && curr.prevDeadkey === rule[index].deadkey
        && curr.idPrevDeadkey === rule[index].idDeadkey
      );

      if (amb_2_2.length > 0) {
        ambiguousWarnings.compare_type = 'amb_2_2';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['', 'C'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_2_2[0].idPrevDeadkey, amb_2_2[0].idDeadkey];
        ambiguousWarnings.Dk_modifier = amb_2_2[0].modifierDeadkey;
        ambiguousWarnings.Dk_key = amb_2_2[0].deadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 1);
      }

      if (dup_2_2.length > 0) {
        duplicateWarnings.compare_type = 'dup_2_2';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['', 'C'];
        duplicateWarnings.dk_bothId_prevdk_dk = [dup_2_2[0].idPrevDeadkey, dup_2_2[0].idDeadkey];
        duplicateWarnings.Dk_modifier = dup_2_2[0].modifierDeadkey;
        duplicateWarnings.Dk_key = dup_2_2[0].deadkey;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 1);
      }

      if (amb_3_3.length > 0) {
        ambiguousWarnings.compare_type = 'amb_3_3';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['', 'A'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_3_3[0].idPrevDeadkey, amb_3_3[0].idDeadkey];
        ambiguousWarnings.modifier = amb_3_3[0].modifierKey;
        ambiguousWarnings.key = amb_3_3[0].key;
        ambiguousWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(amb_3_3[0].output)).character;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 2);
      }

      if (dup_3_3.length > 0) {
        duplicateWarnings.compare_type = 'dup_3_3';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothId_prevdk_dk = [dup_3_3[0].idPrevDeadkey, dup_3_3[0].idDeadkey];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['', 'A'];
        duplicateWarnings.modifier = dup_3_3[0].modifierKey;
        duplicateWarnings.key = dup_3_3[0].key;
        duplicateWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(dup_3_3[0].output)).character;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 2);
      }

      if (amb_4_2.length > 0) {
        ambiguousWarnings.compare_type = 'amb_4_2';
        ambiguousWarnings.earlier_later = [false, true];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['C', ''];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_4_2[0].idPrevDeadkey, amb_4_2[0].idDeadkey];
        ambiguousWarnings.prevDk_modifier = amb_4_2[0].modifierPrevDeadkey;
        ambiguousWarnings.prevDk_key = amb_4_2[0].prevDeadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 0);
      }
    }


    if (rule[index].ruleType === "C3") {

      // 2-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(B11)
      const amb_2_4 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C2"))
        && curr.modifierDeadkey === rule[index].modifierPrevDeadkey
        && curr.deadkey === rule[index].prevDeadkey
        && curr.idDeadkey === rule[index].idPrevDeadkey
      );

      // 6-3  dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_6_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && (new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output))
      );

      // 6-3 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_6_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
      );

      // 4-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C1)
      const amb_4_4 = rule.filter((curr, idx) =>
        curr.ruleType === "C3"
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.idPrevDeadkey !== rule[index].idPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && rule[index].uniquePrevDeadkey !== 0
        && idx < index
      );

      // 4-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C11)
      const dup_4_4 = rule.filter((curr, idx) =>
        curr.ruleType === "C3"
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && idx < index
      );

      // 5-5  dk(C1) + [SHIFT CAPS K_A]  >   dk(C2)  <-> dk(C1) + [SHIFT CAPS K_A]  >  dk(C3)
      const amb_5_5 = rule.filter((curr, idx) => (
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey)
        && idx < index
        && (rule[index].uniqueDeadkey !== 0 || rule[index].uniquePrevDeadkey !== 0)
      );

      // 5-5 dk(C1) + [SHIFT CAPS K_A]  >   dk(C2)  <-> dk(C1) + [SHIFT CAPS K_A]  >  dk(C2)
      const dup_5_5 = rule.filter((curr, idx) =>
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey
        && rule[index].uniqueDeadkey === 0
        && idx < index
      );

      // 6-6 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_6_6 = rule.filter((curr, idx) =>
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && (new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output))
        && idx < index
      );

      // 6-6 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_6_6 = rule.filter((curr, idx) =>
        (curr.ruleType === "C3")
        && curr.idDeadkey === rule[index].idDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && (new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output))
        && idx < index
      );

      if (amb_2_4.length > 0) {
        ambiguousWarnings.compare_type = 'amb_2_4';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['', 'A'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_2_4[0].idPrevDeadkey, amb_2_4[0].idDeadkey];
        ambiguousWarnings.Dk_modifier = amb_2_4[0].modifierDeadkey;
        ambiguousWarnings.Dk_key = amb_2_4[0].deadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 0);
      }

      if (amb_6_3.length > 0) {
        ambiguousWarnings.compare_type = 'amb_6_3';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['', 'C'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_6_3[0].idPrevDeadkey, amb_6_3[0].idDeadkey];
        ambiguousWarnings.modifier = amb_6_3[0].modifierKey;
        ambiguousWarnings.key = amb_6_3[0].key;
        ambiguousWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(amb_6_3[0].output)).character;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 1);
      }

      if (dup_6_3.length > 0) {
        duplicateWarnings.compare_type = 'dup_6_3';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['', 'C'];
        duplicateWarnings.dk_bothId_prevdk_dk = [dup_6_3[0].idPrevDeadkey, dup_6_3[0].idDeadkey];
        duplicateWarnings.modifier = dup_6_3[0].modifierKey;
        duplicateWarnings.key = dup_6_3[0].key;
        duplicateWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(dup_6_3[0].output)).character;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 1);
      }

      if (amb_4_4.length > 0) {
        ambiguousWarnings.compare_type = 'amb_4_4';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['C', ''];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_4_4[0].idPrevDeadkey, amb_4_4[0].idDeadkey];
        ambiguousWarnings.prevDk_modifier = amb_4_4[0].modifierPrevDeadkey;
        ambiguousWarnings.prevDk_key = amb_4_4[0].prevDeadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 0);
      }

      if (dup_4_4.length > 0) {
        duplicateWarnings.compare_type = 'dup_4_4';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['C', ''];
        duplicateWarnings.dk_bothId_prevdk_dk = [dup_4_4[0].idPrevDeadkey, dup_4_4[0].idDeadkey];
        duplicateWarnings.prevDk_modifier = dup_4_4[0].modifierPrevDeadkey;
        duplicateWarnings.prevDk_key = dup_4_4[0].prevDeadkey;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 0);
      }

      if (amb_5_5.length > 0) {
        ambiguousWarnings.compare_type = 'amb_5_5';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['B', 'B'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_5_5[0].idPrevDeadkey, amb_5_5[0].idDeadkey];
        ambiguousWarnings.Dk_modifier = amb_5_5[0].modifierDeadkey;
        ambiguousWarnings.Dk_key = amb_5_5[0].deadkey;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 1);
      }

      if (dup_5_5.length > 0) {
        duplicateWarnings.compare_type = 'dup_5_5';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['B', 'B'];
        duplicateWarnings.Dk_modifier = rule[index].modifierDeadkey;
        duplicateWarnings.Dk_key = rule[index].deadkey;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 1);
      }

      if (amb_6_6.length > 0) {
        ambiguousWarnings.compare_type = 'amb_6_6';
        ambiguousWarnings.earlier_later = [true, false];
        ambiguousWarnings.dk_bothPrefix_prevdk_dk = ['', 'B'];
        ambiguousWarnings.dk_bothId_prevdk_dk = [amb_6_6[0].idPrevDeadkey, amb_6_6[0].idDeadkey];
        ambiguousWarnings.modifier = amb_6_6[0].modifierKey;
        ambiguousWarnings.key = amb_6_6[0].key;
        ambiguousWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(amb_6_6[0].output)).character;
        ambiguousWarnings.warningMessages = this.createWarningText(ambiguousWarnings, 2);
      }

      if (dup_6_6.length > 0) {
        duplicateWarnings.compare_type = 'dup_6_6';
        duplicateWarnings.earlier_later = [true, false];
        duplicateWarnings.dk_bothPrefix_prevdk_dk = ['', 'B'];
        duplicateWarnings.dk_bothId_prevdk_dk = [dup_6_6[0].idPrevDeadkey, dup_6_6[0].idDeadkey];
        duplicateWarnings.modifier = dup_6_6[0].modifierKey;
        duplicateWarnings.key = dup_6_6[0].key;
        duplicateWarnings.output = this.writeCharacterOrUnicode(new TextDecoder().decode(dup_6_6[0].output)).character;
        duplicateWarnings.warningMessages = this.createWarningText(duplicateWarnings, 2);
      }
    }

    // In rare cases a rule might not be written out therefore we need to inform the user:
    // usually we write the first occurance of an ambiguous C0/C1 rule and comment out the later
    //    assuming that if several C0/C1 rules are ambiguous the user prefers to use the first C0/C1 rule
    // for C2/C3 rules we write the last occurance of an ambiguous rule and comment out the earlier
    //    assuming that if a C0/C1 and a C2/C3 rule is ambiguous the user prefers to use the C2/C3 rule over the C0/C1 rule
    // if both happens, nothing would be written, therefore this messsage

    const extraWarning = "PLEASE CHECK THAT RULE AS IT WILL NOT BE WRITTEN !";

    for (let i = 0; i < 3; i++) {
      if (ambiguousWarnings.warningMessages[i] !== "") {
        if ((ambiguousWarnings.warningMessages[i].indexOf("earlier:") > -1) && (ambiguousWarnings.warningMessages[i].indexOf("later:") > -1)) {
          ambiguousWarnings.warningMessages[i] = ambiguousWarnings.warningMessages[i] + extraWarning;
        }
      }
    }

    for (let i = 0; i < 3; i++) {
      const completeWarning =
        unavailableSuperiWarnings.warningMessages[i]
        + duplicateWarnings.warningMessages[i]
        + ambiguousWarnings.warningMessages[i]
        + unavailableModiWarnings.warningMessages[i];

      completeWarning ? (warningText[i] = "c WARNING: " + completeWarning + " here: ") : warningText[i] = '';

    }

    return warningText;
  }

  /**
  * @brief  member function to write a character as Unicode Character or Unicode Codepoint depending on the character that is to be written
  * @param  ctr : string - the character to be written
  * @return a string containing the Unicode representation of the control character.
  *         A control character will be written as unicode (U+0004),
  *         a non-control character will be written as itself ( 'A', '1', '፩', '😎')
  *         null in case of an empty string or null or undefined input
  */
  public writeCharacterOrUnicode(ctr: string, msg: string = ""): MessageCharacter {

    if ((ctr === null) || (ctr === undefined)) {
      return null;
    }

    let msg_control = '';
    let msg_entity = '';
    let versionOutputCharacter;
    const out: MessageCharacter = {
      message: msg,
      character: ctr
    };

    const m_uni = /^U\+([0-9a-f]{1,6})$/i.exec(ctr);
    const m_hex = /^&#x([0-9a-f]{1,6});$/i.exec(ctr);
    const m_dec = /^&#([0-9]{1,7});$/.exec(ctr);

    // find the value of output character which may be specified in unicode, html hex or html dec format ( e.g. U+1234 -> 1234; &#x1234; -> 1234; &#4660; -> 1234)
    const ctr_val = ((m_uni || m_hex || m_dec) ?
      m_uni ? parseInt(m_uni[1], 16) : m_hex ? parseInt(m_hex[1], 16) : parseInt(m_dec[1], 10) : KeylayoutToKmnConverter.MAX_CTRL_CHARACTER
    );

    if (ctr.length === 0) {
      msg_entity = "empty output or unsupported numerical html entity: ";
    }

    // for control characters in 'U+...', '&#x...' or '&#...' format as well as in "" format
    if ((ctr_val < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) || (ctr.charCodeAt(0) < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER)) {

      // for control characters in 'U+...', '&#x...'  or '&#...' format
      if (ctr_val < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) {
        versionOutputCharacter = "U+" + ctr_val.toString(16).toUpperCase().padStart(4, '0');
      }
      // for control characters in "" format
      if (ctr.charCodeAt(0) < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) {
        versionOutputCharacter = "U+" + ctr.charCodeAt(0).toString(16).toUpperCase().padStart(4, '0');
      }
      if (versionOutputCharacter)
        out.character = versionOutputCharacter;

      msg_control = "Use of a control character ";
    }
    else {
      out.character = this.convertToUnicodeCharacter(ctr);
    }

    // add a warning message
    if (msg !== "") {
      msg = msg + msg_control + msg_entity;
    }
    if ((msg === "") && (msg_entity !== "" || msg_control !== "")) {
      msg = "c WARNING: " + msg_entity + msg_control;
    }
    out.message = msg;

    return out;
  }

  // TODO: move to util in PR 14569
  /**
   * @brief  function to convert a numeric character reference or a unicode value to a unicode character e.g. &#x63 -> c;  U+1F60E -> 😎
   * @param  inputString the value that will converted
   * @return a unicode character like 'c', 'ሴ', '😎' or undefined if inputString is not recognized
   */
  public convertToUnicodeCharacter(inputString: string): string {


    // null, undefined will later be refused for conversion
    if (inputString == null || inputString == undefined) {
      return undefined;
    }

    //  U+ followed by 1.-6. hex digits will later be used for conversion
    const m_uni = /^U\+([0-9a-f]{1,6})$/i.exec(inputString);

    // invalid U+ ( U+ followed by anything) will later be refused for conversion
    const m_uni_inv = /^(U\+)+(.?)+$/i.exec(inputString);

    // &#x followed by 1.-6. hex digits will later be used for conversion
    const m_hex = /^&#x([0-9a-f]{1,6});$/i.exec(inputString);

    // &# followed by 1.-6. decimal digits will later be used for conversion
    const m_dec = /^&#([0-9]{1,7});$/.exec(inputString);

    // & followed by gt, lt, quot, amp, apos will later be used for conversion
    const m_nam = /^&(gt|lt|quot|amp|apos);$/i.exec(inputString);

    //  &# followed by anything will later be refused for conversion
    const m_html_inv = /^(&#)+(.?)+$/i.exec(inputString);

    // one or more characters except starting with U+ or & will later be used for conversion
    const m_chr = /^(?!U\+|&).+$/i.exec(inputString);

    // '&', '&#','&#x', or 'U+' with or without ; will later be refused for conversion
    const m_chr_inv = /^((&;?)+|(&#;?)+|(&#x;?)+|(U\+)+;?)$|^$/i.exec(inputString);

    // valid 'U+xxxx'
    if (m_uni) {
      const codePoint_u = parseInt(m_uni[1], 16);
      // Reject surrogates and invalid codepoints
      if ((codePoint_u >= 0xD800 && codePoint_u <= 0xDFFF) || codePoint_u > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_u);
    }

    // invalid 'U+xxxx'
    else if (m_uni_inv) {
      return undefined;
    }

    // valid '&#x...'
    else if (m_hex) {
      const codePoint_h = parseInt(m_hex[1], 16);
      // Reject surrogates and invalid codepoints
      if ((codePoint_h >= 0xD800 && codePoint_h <= 0xDFFF) || codePoint_h > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_h);
    }
    // valid '&#...'
    else if (m_dec) {
      const codePoint_d = parseInt(m_dec[1], 10);
      // Reject surrogates and invalid codepoints
      if ((codePoint_d >= 0xD800 && codePoint_d <= 0xDFFF) || codePoint_d > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_d);
    }
    // valid '&gt', '&lt',..
    else if (m_nam) {
      switch (m_nam[1].toLowerCase()) {
        case 'gt': return '>';
        case 'lt': return '<';
        case 'quot': return '"';
        case 'amp': return '&';
        case 'apos': return "'";
        default: return undefined;
      }
    }
    // invalid  '&...'
    else if (m_html_inv) {
      return undefined;
    }

    // single 'U+', '&', ''
    else if (m_chr_inv) {
      return inputString;
    }

    // if no matches so far, check for one or more characters ('a','ab', 'ẘ','😎', '😎😎',  )
    else if (m_chr) {
      return inputString;
    }
    return undefined;
  }
  /** @internal */
  public unitTestEndpoints = {
    reviewRules: this.reviewRules.bind(this),
  };
}

