/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by S. Schmitt on 2025-05-12
 *
 * Write Keyman .kmn files from an in-memory representation generated
 *
 */

import { CompilerCallbacks, CompilerOptions } from "@keymanapp/developer-utils";
import { KeylayoutToKmnConverter, ProcessedData, Rule } from './keylayout-to-kmn-converter.js';
import { ConverterMessages } from '../converter-messages.js';
import KEYMAN_VERSION from "@keymanapp/keyman-version";

export interface messageCharacter {
  message: string;
  character: string;
};

export class KmnFileWriter {

  constructor(private callbacks: CompilerCallbacks, private options: CompilerOptions) { };

  /**
   * @brief  member function to write data from object to a Uint8Array
   * @param  dataUkelele the array holding all keyboard data
   * @return a Uint8Array holding data
   */
  public write(dataUkelele: ProcessedData): Uint8Array {
    let data: string = "\n";

    // top part of kmn file: STORES
    const dataStores = this.writeKmnFileHeader(dataUkelele);

    // bottom part of kmn file: RULES
    const dataRules = this.writeDataRules(dataUkelele);

    if (dataRules)
      data += dataStores + dataRules;

    try {
      return new TextEncoder().encode(data);
    } catch (err) {
      this.callbacks.reportMessage(ConverterMessages.Error_UnableToWrite({ outputFilename: dataUkelele.kmnFilename, errorText: err }));
      return null;
    }
  }

  /**
   * @brief  member function to create data for the header (stores) that will be printed to the resulting kmn file
   * @param  dataUkelele an object containing all data read from a .keylayout file
   * @return string -  all stores to be printed
   */
  public writeKmnFileHeader(dataUkelele: ProcessedData): string {

    let data: string = "";

    data += "c ..................................................................................................................\n";
    data += "c ..................................................................................................................\n";
    data += "c Keyman keyboard generated by kmn-convert version: " + KEYMAN_VERSION.VERSION + "\n";
    data += "c from Ukelele file: " + dataUkelele.keylayoutFilename + "\n";
    data += "c ..................................................................................................................\n";
    data += "c ..................................................................................................................\n";
    data += "\n";

    data += "store(&TARGETS) \'desktop\'\n";

    data += "\n";
    data += "begin Unicode > use(main)\n\n";
    data += "group(main) using keys\n\n";

    data += "\n";
    return data;
  }

  /**
   * @brief  member function to create data from rules that will be printed to the resulting kmn file
   * @param  dataUkelele an object containing all data read from a .keylayout file
   * @return string -  all rules to be printed
   */
  public writeDataRules(dataUkelele: ProcessedData): string {

    const keylayoutKmnConverter = new KeylayoutToKmnConverter(this.callbacks, this.options);
    let data: string = "";

    // filter array of all rules and remove duplicates
    // during the process of creating Rule[], duplicate rules might occur
    // (e.g. when in a keylayout file the same modifiers occur in several behaviors thus producing the same rules).
    // This is to filter out those duplicate Rule objects
    const uniqueDataRules: Rule[] = dataUkelele.rules.filter((curr) => {
      return (!(curr.output === new TextEncoder().encode("") || curr.output === undefined)
        && (curr.key !== "")
        && ((curr.ruleType === "C0")
          || (curr.ruleType === "C1")
          || (curr.ruleType === "C2" && (curr.deadkey !== ""))
          || (curr.ruleType === "C3" && (curr.deadkey !== "") && (curr.prevDeadkey !== "")))
      );
    }).reduce((unique, o) => {
      if (!unique.some((obj: Rule) =>
        new TextDecoder().decode(obj.output) === new TextDecoder().decode(o.output)

        && obj.ruleType === o.ruleType
        && obj.modifierKey === o.modifierKey
        && obj.key === o.key

        && obj.modifierDeadkey === o.modifierDeadkey
        && obj.deadkey === o.deadkey

        && obj.modifierPrevDeadkey === o.modifierPrevDeadkey
        && obj.prevDeadkey === o.prevDeadkey)
      ) {
        unique.push(o);
      }
      return unique;
    }, []);

    //................................................ C0 C1 ................................................................

    for (let k = 0; k < uniqueDataRules.length; k++) {

      if ((uniqueDataRules[k].ruleType === "C0") || (uniqueDataRules[k].ruleType === "C1")) {

        // lookup key nr of the key which is being processed
        let keyNr: number = 0;
        for (let j = 0; j <= KeylayoutToKmnConverter.MAX_KEY_IDENTIFIER; j++) {
          if (keylayoutKmnConverter.mapUkeleleKeycodeToVK(j) === uniqueDataRules[k].key) {
            keyNr = j;
            break;
          }
        }

        // skip keyNr 48 (K_TAB) and 36 (K_ENTER)
        if ((keyNr === 48) || (keyNr === 36)) {
          continue;
        }

        // add a line after rules of each key
        if ((k > 1) && (uniqueDataRules[k - 1].key !== uniqueDataRules[k].key) && (uniqueDataRules[k - 1].ruleType === uniqueDataRules[k].ruleType)) {
          data += '\n';
        }

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;
        const warnText = this.reviewRules(uniqueDataRules, k);

        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14564 use functions from util instead of the ones in this class
        // const outputUnicodeCharacter = util.convertToUnicodeCharacter(outputCharacter);
        // const outputUnicodeCodePoint = util.convertToUnicodeCodePoint(outputCharacter);

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] =  characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[2].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            if (versionOutputCharacter === "'") {
              data += warningTextToWrite
                + "+ ["
                + (uniqueDataRules[k].modifierKey + ' ' + uniqueDataRules[k].key).trim()
                + `]  >  \"`
                + versionOutputCharacter
                + '\"\n';
            }
            else {
              data += warningTextToWrite
                + "+ ["
                + (uniqueDataRules[k].modifierKey + ' ' + uniqueDataRules[k].key).trim()
                + `]  >  \'`
                + versionOutputCharacter
                + '\'\n';
            }
          }
        }
      }
    }

    //................................................ C2 ...................................................................
    for (let k = 0; k < uniqueDataRules.length; k++) {

      if (uniqueDataRules[k].ruleType === "C2") {

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;
        const warnText = this.reviewRules(uniqueDataRules, k);

        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14564 use functions from util instead of the ones in this class
        // const outputUnicodeCharacter = util.convertToUnicodeCharacter(outputCharacter);
        // const outputUnicodeCodePoint = util.convertToUnicodeCodePoint(outputCharacter);

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] =  characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[1].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[1].length > 0)) {
            warningTextToWrite = warnText[1];
          }

          if (!((warnText[1].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "+ [" + (uniqueDataRules[k].modifierDeadkey + " "
                + uniqueDataRules[k].deadkey).trim()
              + "]  >  dk(A" + String(uniqueDataRules[k].idDeadkey)
              + ")\n";
          }
        }

        if ((warnText[2].indexOf("duplicate") < 0)) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            if (versionOutputCharacter === "'") {
              data += warningTextToWrite
                + "dk(A"
                + (String(uniqueDataRules[k].idDeadkey) + ") + ["
                  + uniqueDataRules[k].modifierKey).trim()
                + " "
                + uniqueDataRules[k].key + ']  >  \"'
                + versionOutputCharacter
                + '\"\n';
            }
            else {
              data += warningTextToWrite
                + "dk(A"
                + (String(uniqueDataRules[k].idDeadkey) + ") + ["
                  + uniqueDataRules[k].modifierKey).trim()
                + " "
                + uniqueDataRules[k].key + "]  >  \'"
                + versionOutputCharacter
                + "\'\n";
            }


          }
          data += "\n";
        }
      }
    }

    //................................................ C3 ...................................................................

    for (let k = 0; k < uniqueDataRules.length; k++) {
      if (uniqueDataRules[k].ruleType === "C3") {

        // use of Unicode Character vs Unicode Codepoint;
        // If it`s a ctrl character we print out the Unicode Codepoint else we print out the Unicode Character
        let versionOutputCharacter;

        const warnText = this.reviewRules(uniqueDataRules, k);
        const outputCharacter = new TextDecoder().decode(uniqueDataRules[k].output);
        // TODO-kmc-convert: after merge of PR 14564 use functions from util instead of the ones in this class

        if ((outputCharacter !== undefined) || (outputCharacter !== "")) {
          const characterMessage = this.writeCharacterOrUnicode(outputCharacter, warnText[2]);
          versionOutputCharacter = characterMessage.character;
          warnText[2] =  characterMessage.message;
        }

        // add a warning in front of rules in case unavailable modifiers or ambiguous rules are used
        // if warning contains duplicate rules we do not write out the entire rule
        // (even if there are other warnings for the same rule) since that rule had been written before
        if (warnText[0].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";

          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[0].length > 0)) {
            warningTextToWrite = warnText[0];
          }

          if (!((warnText[0].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "+ ["
              + (uniqueDataRules[k].modifierPrevDeadkey + " "
                + uniqueDataRules[k].prevDeadkey).trim()
              + "]   >   dk(A"
              + String(uniqueDataRules[k].idPrevDeadkey) + ")\n";
          }
        }

        if (warnText[1].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[1].length > 0)) {
            warningTextToWrite = warnText[1];
          }

          if (!((warnText[1].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite
              + "dk(A" + (String(uniqueDataRules[k].idPrevDeadkey) + ")  + ["
                + uniqueDataRules[k].modifierDeadkey).trim()
              + " "
              + uniqueDataRules[k].deadkey
              + "]  >  dk(B"
              + String(uniqueDataRules[k].idDeadkey)
              + ")\n";
          }
        }

        if (warnText[2].indexOf("duplicate") < 0) {

          let warningTextToWrite = "";
          if (!KeylayoutToKmnConverter.SKIP_COMMENTED_LINES && (warnText[2].length > 0)) {
            warningTextToWrite = warnText[2];
          }

          if (!((warnText[2].length > 0) && KeylayoutToKmnConverter.SKIP_COMMENTED_LINES)) {
            data += warningTextToWrite + "dk(B"
              + (String(uniqueDataRules[k].idDeadkey)
                + ") + ["
                + uniqueDataRules[k].modifierKey).trim()
              + " "
              + uniqueDataRules[k].key
              + "]  >  \'"
              + versionOutputCharacter
              + "\'\n";
          }
        }

        if ((warnText[0].indexOf("duplicate") < 0) || (warnText[1].indexOf("duplicate") < 0) || (warnText[2].indexOf("duplicate") < 0)) {
          data += "\n";
        }
      }
    }
    return data;
  }

  /**
   * @brief  member function to review rules for acceptable modifiers, duplicate or ambiguous rules and return an array containing possible warnings.
   *         Keyman can not handle duplicate rules so we need to make sure a rule is written only once by either omitting a duplicate rule or commenting out an ambiguous rule.
   *         Omitting rules and definition of comparisons e.g. 1-1, 2-4, 6-6
   *         see https://docs.google.com/document/d/12J3NGO6RxIthCpZDTR8FYSRjiMgXJDLwPY2z9xqKzJ0/edit?tab=t.0#heading=h.pcz8rjyrl5ug
   * @param  rule : Rule[] - an array of all rules
   * @param  index the index of a rule in Rule[]
   * @return a string[] containing possible warnings for a rule
   */
  public reviewRules(rule: Rule[], index: number): string[] {

    const keylayoutKmnConverter = new KeylayoutToKmnConverter(this.callbacks, this.options);
    const warningText: string[] = Array(3).fill("");

    // ------------------------- check unavailable modifiers -------------------------

    if ((rule[index].ruleType === "C0") || (rule[index].ruleType === "C1")) {
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        warningText[2] = "unavailable modifier : ";
      }
    }

    else if (rule[index].ruleType === "C2") {
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierDeadkey)) {
        warningText[1] = "unavailable modifier : ";
        warningText[2] = "unavailable superior rule ( ["
          + rule[index].modifierDeadkey + " "
          + rule[index].deadkey
          + "]  >  dk(A"
          + rule[index].idDeadkey
          + ") ) : ";
      }
      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        warningText[2] = "unavailable modifier : ";
      }
    }

    else if (rule[index].ruleType === "C3") {

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierPrevDeadkey)) {
        warningText[0] = "unavailable modifier : ";
        warningText[1] = "unavailable superior rule ( ["
          + rule[index].modifierPrevDeadkey + " "
          + rule[index].prevDeadkey
          + "]  >  dk(A"
          + rule[index].idPrevDeadkey
          + ") ) : ";
      }

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierDeadkey)) {
        warningText[1] = "unavailable modifier : ";
        warningText[2] = "unavailable superior rule ( ["
          + rule[index].modifierDeadkey + " "
          + rule[index].deadkey
          + "]  >  dk(B"
          + rule[index].idDeadkey
          + ") ) : ";
      }

      if (!keylayoutKmnConverter.isAcceptableKeymanModifier(rule[index].modifierKey)) {
        warningText[2] = "unavailable modifier : ";
      }
    }

    // ------------------------- check ambiguous/duplicate rules -------------------------

    if ((rule[index].ruleType === "C0") || (rule[index].ruleType === "C1")) {

      // 1-1: + [CAPS K_N]  > 'N' <-> + [CAPS K_N]  >  'A'
      const amb_1_1 = rule.filter((curr, idx) =>
        (curr.ruleType === "C0" || curr.ruleType === "C1")
        && curr.modifierPrevDeadkey === ""
        && curr.prevDeadkey === ""
        && curr.modifierDeadkey === ""
        && curr.deadkey === ""
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
        && idx < index
      );
      // 1-1: + [CAPS K_N]  > 'N' <-> + [CAPS K_N]  >  'N'
      const dup_1_1 = rule.filter((curr, idx) =>
        (curr.ruleType === "C0" || curr.ruleType === "C1")
        && curr.modifierPrevDeadkey === ""
        && curr.prevDeadkey === ""
        && curr.modifierDeadkey === ""
        && curr.deadkey === ""
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      // 4-1: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  'Ñ'
      const amb_4_1 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C3"))
        && curr.modifierPrevDeadkey === rule[index].modifierKey
        && curr.prevDeadkey === rule[index].key
      );

      // 2-1: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  'Ñ'
      const amb_2_1 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C2"))
        && curr.modifierDeadkey === rule[index].modifierKey
        && curr.deadkey === rule[index].key
      );

      if (amb_4_1.length > 0) {
        warningText[2] = warningText[2]
          + ("ambiguous rule: later: ["
            + amb_4_1[0].modifierPrevDeadkey
            + " "
            + amb_4_1[0].prevDeadkey
            + "]  >  dk(C"
            + amb_2_1[0].idDeadkey
            + ") ");
      }

      if (amb_2_1.length > 0) {
        warningText[2] = warningText[2]
          + ("ambiguous rule: later: ["
            + amb_2_1[0].modifierDeadkey
            + " "
            + amb_2_1[0].deadkey
            + "]  >  dk(A"
            + amb_2_1[0].idDeadkey
            + ") ");
      }

      if (amb_1_1.length > 0) {
        warningText[2] = warningText[2]
          + ("ambiguous rule: earlier: ["
            + amb_1_1[0].modifierKey
            + " "
            + amb_1_1[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(amb_1_1[0].output)).character
            + "\' ");
      }

      if (dup_1_1.length > 0) {
        warningText[2] = warningText[2]
          + ("duplicate rule: earlier: ["
            + dup_1_1[0].modifierKey
            + " "
            + dup_1_1[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(dup_1_1[0].output)).character
            + "\' ");
      }
    }

    if (rule[index].ruleType === "C2") {

      // 2-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C3)
      const amb_2_2 = rule.filter((curr, idx) =>
        curr.ruleType === "C2"
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey !== rule[index].idDeadkey
        && idx < index
      );

      // 2-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C11)
      const dup_2_2 = rule.filter((curr, idx) =>
        curr.ruleType === "C2"
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey
        && idx < index
      );

      //3-3: dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_3_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idDeadkey === rule[index].idDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      //3-3: dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_3_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idDeadkey === rule[index].idDeadkey
        && rule[index].uniqueDeadkey === 0
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
        && idx < index
      );

      // 4-2: + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(B11)
      const amb_4_2 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C3"))
        && curr.modifierPrevDeadkey === rule[index].modifierDeadkey
        && curr.prevDeadkey === rule[index].deadkey
        && curr.idPrevDeadkey === rule[index].idDeadkey
      );

      if (amb_2_2.length > 0) {
        warningText[1] = warningText[1]
          + ("ambiguous rule: earlier: ["
            + amb_2_2[0].modifierDeadkey
            + " "
            + amb_2_2[0].deadkey
            + "]  >  dk(C"
            + amb_2_2[0].idDeadkey
            + ") ");
      }

      if (dup_2_2.length > 0) {
        warningText[1] = warningText[1]
          + ("duplicate rule: earlier: ["
            + dup_2_2[0].modifierDeadkey
            + " "
            + dup_2_2[0].deadkey
            + "]  >  dk(C"
            + dup_2_2[0].idDeadkey
            + ") ");
      }

      if (amb_3_3.length > 0) {
        warningText[2] = warningText[2]
          + ("ambiguous rule: earlier: dk(A"
            + amb_3_3[0].idDeadkey
            + ") + ["
            + amb_3_3[0].modifierKey
            + " "
            + amb_3_3[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(amb_3_3[0].output)).character
            + "\' ");
      }

      if (dup_3_3.length > 0) {
        warningText[2] = warningText[2]
          + ("duplicate rule: earlier: dk(A"
            + dup_3_3[0].idDeadkey
            + ") + ["
            + dup_3_3[0].modifierKey
            + " "
            + dup_3_3[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(dup_3_3[0].output)).character
            + "\' ");
      }

      if (amb_4_2.length > 0) {
        warningText[0] = warningText[0]
          + ("ambiguous rule: later: ["
            + amb_4_2[0].modifierPrevDeadkey
            + " "
            + amb_4_2[0].prevDeadkey
            + "]  >  dk(C"
            + amb_4_2[0].idPrevDeadkey
            + ") ");
      }
    }

    if (rule[index].ruleType === "C3") {

      // 2-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(B11)
      const amb_2_4 = rule.filter((curr, idx) =>
        ((curr.ruleType === "C2"))
        && curr.modifierDeadkey === rule[index].modifierPrevDeadkey
        && curr.deadkey === rule[index].prevDeadkey
        && curr.idDeadkey === rule[index].idPrevDeadkey
      );

      // 6-3  dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_6_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && (new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output))
      );

      // 6-3 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_6_3 = rule.filter((curr, idx) =>
        (curr.ruleType === "C2")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output)
      );

      // 4-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C1)
      const amb_4_4 = rule.filter((curr, idx) =>
        curr.ruleType === "C3"
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.idPrevDeadkey !== rule[index].idPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && rule[index].uniquePrevDeadkey !== 0
        && idx < index
      );

      // 4-4 + [CAPS K_N]  >  dk(C11) <-> + [CAPS K_N]  >  dk(C11)
      const dup_4_4 = rule.filter((curr, idx) =>
        curr.ruleType === "C3"
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && idx < index
      );

      // 5-5  dk(C1) + [SHIFT CAPS K_A]  >   dk(C2)  <-> dk(C1) + [SHIFT CAPS K_A]  >  dk(C3)
      const amb_5_5 = rule.filter((curr, idx) => (
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey)
        && idx < index
        && (rule[index].uniqueDeadkey !== 0 || rule[index].uniquePrevDeadkey !== 0)
      );

      // 5-5 dk(C1) + [SHIFT CAPS K_A]  >   dk(C2)  <-> dk(C1) + [SHIFT CAPS K_A]  >  dk(C2)
      const dup_5_5 = rule.filter((curr, idx) =>
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierPrevDeadkey === rule[index].modifierPrevDeadkey
        && curr.prevDeadkey === rule[index].prevDeadkey
        && curr.modifierDeadkey === rule[index].modifierDeadkey
        && curr.deadkey === rule[index].deadkey
        && curr.idDeadkey === rule[index].idDeadkey
        && rule[index].uniqueDeadkey === 0
        && idx < index
      );

      // 6-6 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'B'
      const amb_6_6 = rule.filter((curr, idx) =>
        (curr.ruleType === "C3")
        && curr.idPrevDeadkey === rule[index].idPrevDeadkey
        && curr.modifierKey === rule[index].modifierKey
        && curr.key === rule[index].key
        && (new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output))
        && idx < index
      );

      // 6-6 dk(C11) + [SHIFT CAPS K_A]  >  'Ã'  <-> dk(C11) + [SHIFT CAPS K_A]  >  'Ã'
      const dup_6_6 =
        rule.filter((curr, idx) =>
          (curr.ruleType === "C3")
          && curr.idDeadkey === rule[index].idDeadkey
          && curr.modifierKey === rule[index].modifierKey
          && curr.key === rule[index].key
          && (new TextDecoder().decode(curr.output) === new TextDecoder().decode(rule[index].output))
          && idx < index
        );

      if (amb_2_4.length > 0) {
        warningText[0] = warningText[0]
          + ("ambiguous rule: earlier: ["
            + amb_2_4[0].modifierDeadkey
            + " "
            + amb_2_4[0].deadkey
            + "]  >  dk(A"
            + amb_2_4[0].idDeadkey
            + ") ");
      }

      if (amb_6_3.length > 0) {
        warningText[1] = warningText[1]
          + ("ambiguous rule: earlier: dk(C"
            + amb_6_3[0].idDeadkey
            + ") + ["
            + amb_6_3[0].modifierKey
            + " "
            + amb_6_3[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(amb_6_3[0].output)).character
            + "\' ");
      }

      if (dup_6_3.length > 0) {
        warningText[1] = warningText[1]
          + ("duplicate rule: earlier: dk(C"
            + dup_6_3[0].idDeadkey
            + ") + ["
            + dup_6_3[0].modifierKey
            + " "
            + dup_6_3[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(dup_6_3[0].output)).character
            + "\' ");
      }

      if (amb_4_4.length > 0) {
        warningText[0] = warningText[0]
          + ("ambiguous rule: earlier: ["
            + amb_4_4[0].modifierPrevDeadkey
            + " "
            + amb_4_4[0].prevDeadkey
            + "]  >  dk(C"
            + amb_4_4[0].idPrevDeadkey
            + ") ");
      }

      if (dup_4_4.length > 0) {
        warningText[0] = warningText[0]
          + ("duplicate rule: earlier: ["
            + dup_4_4[0].modifierPrevDeadkey
            + " "
            + dup_4_4[0].prevDeadkey
            + "]  >  dk(C"
            + dup_4_4[0].idPrevDeadkey
            + ") ");
      }

      if (amb_5_5.length > 0) {
        warningText[1] = warningText[1]
          + ("ambiguous rule: earlier: dk(B"
            + amb_5_5[0].idPrevDeadkey
            + ") + ["
            + amb_5_5[0].modifierDeadkey
            + " "
            + amb_5_5[0].deadkey
            + "]  >  dk(B"
            + amb_5_5[0].idDeadkey
            + ") ");
      }

      if (dup_5_5.length > 0) {
        warningText[1] = warningText[1]
          + ("duplicate rule: earlier: dk(B"
            + dup_5_5[0].idPrevDeadkey
            + ") + ["
            + dup_5_5[0].modifierDeadkey
            + " "
            + dup_5_5[0].deadkey
            + "]  >  dk(B"
            + dup_5_5[0].idDeadkey
            + ") ");
      }

      if (amb_6_6.length > 0) {
        warningText[2] = warningText[2]
          + ("ambiguous rule: earlier: dk(B"
            + amb_6_6[0].idDeadkey
            + ") + ["
            + amb_6_6[0].modifierKey
            + " "
            + amb_6_6[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(amb_6_6[0].output)).character
            + "\' ");
      }

      if (dup_6_6.length > 0) {
        warningText[2] = warningText[2]
          + ("duplicate rule: earlier: dk(B"
            + dup_6_6[0].idDeadkey
            + ") + ["
            + dup_6_6[0].modifierKey
            + " "
            + dup_6_6[0].key
            + "]  >  \'"
            + this.writeCharacterOrUnicode(new TextDecoder().decode(dup_6_6[0].output)).character
            + "\' ");
      }
    }
    // In rare cases a rule might not be written out therefore we need to inform the user:
    // usually we write the first occurance of an ambiguous C0/C1 rule and comment out the later
    //    assuming that if several C0/C1 rules are ambiguous the user prefers to use the first C0/C1 rule
    // for C2/C3 rules we write the last occurance of an ambiguous rule and comment out the earlier
    //    assuming that if a C0/C1 and a C2/C3 rule is ambiguous the user prefers to use the C2/C3 rule over the C0/C1 rule
    // if both happens, nothing would be written, therefore this messsage

    const extraWarning = "PLEASE CHECK THE FOLLOWING RULE AS IT WILL NOT BE WRITTEN !  ";

    if (warningText[0] !== "") {
      warningText[0] = "c WARNING: " + warningText[0] + "here: ";

      if ((warningText[0].indexOf("earlier:") > 0) && (warningText[0].indexOf("later:") > 0)) {
        warningText[0] = warningText[0] + extraWarning;
      }
    }
    if (warningText[1] !== "") {
      warningText[1] = "c WARNING: " + warningText[1] + "here: ";

      if ((warningText[1].indexOf("earlier:") > 0) && (warningText[1].indexOf("later:") > 0)) {
        warningText[1] = warningText[1] + extraWarning;
      }
    }

    if (warningText[2] !== "") {
      warningText[2] = "c WARNING: " + warningText[2] + "here: ";

      if ((warningText[2].indexOf("earlier:") > 0) && (warningText[2].indexOf("later:") > 0)) {
        warningText[2] = warningText[2] + extraWarning;
      }
    }
    return warningText;
  }

  /**
  * @brief  member function to write a character as Unicode Character or Unicode Codepoint depending on the character that is to be written
  * @param  ctr : string - the character to be written
  * @return a string containing the Unicode representation of the control character.
  *         A control character will be written as unicode (U+0004),
  *         a non-control character will be written as itself ( 'A', '1', '፩', '😎')
  *         null in case of an empty string or null or undefined input
  */
  public writeCharacterOrUnicode(ctr: string, msg: string = ""): messageCharacter {

    if ((ctr === null) || (ctr === undefined) || (ctr.length === 0)) {
      return null;
    }

    let versionOutputCharacter;
    const out: messageCharacter = {
      message: msg,
      character: ctr
    };

    const m_uni = /^U\+([0-9a-f]{1,6})$/i.exec(ctr);
    const m_hex = /^&#x([0-9a-f]{1,6});$/i.exec(ctr);
    const m_dec = /^&#([0-9]{1,7});$/.exec(ctr);

    // find the value of output character which may be specified in unicode, html hex or html dec format ( e.g. U+1234 -> 1234; &#x1234; -> 1234; &#4660; -> 1234)
    const ctr_val = ((m_uni || m_hex || m_dec) ?
      m_uni ? parseInt(m_uni[1], 16) : m_hex ? parseInt(m_hex[1], 16) : parseInt(m_dec[1], 10) : KeylayoutToKmnConverter.MAX_CTRL_CHARACTER
    );

    // for control charactersin 'U+...', '&#x...' or '&#...' format as well as in "" format
    if ((ctr_val < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) || (ctr.charCodeAt(0) < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER)) {

      // for control characters in 'U+...', '&#x...'  or '&#...' format
      if (ctr_val < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) {
        versionOutputCharacter = "U+" + ctr_val.toString(16).toUpperCase().padStart(4, '0');
      }
      // for control characters in "" format
      if (ctr.charCodeAt(0) < KeylayoutToKmnConverter.MAX_CTRL_CHARACTER) {
        versionOutputCharacter = "U+" + ctr.charCodeAt(0).toString(16).toUpperCase().padStart(4, '0');
      }
      if (versionOutputCharacter)
        out.character = versionOutputCharacter;

      // add a warning message
      if (msg == "") {
        out.message = "c WARNING: use of a control character ";
      }
      else {
        out.message = msg + "; Use of a control character ";
      }
    }
    else {
      out.character = this.convertToUnicodeCharacter(ctr);;
    }
    return out;
  }

  // TODO: move to util in PR 14569
  /**
   * @brief  function to convert a numeric character reference or a unicode value to a unicode character e.g. &#x63 -> c;  U+1F60E -> 😎
   * @param  inputString the value that will converted
   * @return a unicode character like 'c', 'ሴ', '😎' or undefined if inputString is not recognized
   */
  public convertToUnicodeCharacter(inputString: string): string {


    // null, undefined will later be refused for conversion
    if (inputString == null || inputString == undefined) {
      return undefined;
    }

    //  U+ followed by 1.-6. hex digits will later be used for conversion
    const m_uni = /^U\+([0-9a-f]{1,6})$/i.exec(inputString);

    // invalid U+ ( U+ followed by anything) will later be refused for conversion
    const m_uni_inv = /^(U\+)+(.?)+$/i.exec(inputString);

    // &#x followed by 1.-6. hex digits will later be used for conversion
    const m_hex = /^&#x([0-9a-f]{1,6});$/i.exec(inputString);

    // &# followed by 1.-6. decimal digits will later be used for conversion
    const m_dec = /^&#([0-9]{1,7});$/.exec(inputString);

    // & followed by gt, lt, quot, amp, apos will later be used for conversion
    const m_nam = /^&(gt|lt|quot|amp|apos);$/i.exec(inputString);

    //  &# followed by anything will later be refused for conversion
    const m_html_inv = /^(&#)+(.?)+$/i.exec(inputString);

    // one or more characters except starting with U+ or & will later be used for conversion
    const m_chr = /^(?!U\+|&).+$/i.exec(inputString);

    // '&', '&#','&#x', or 'U+' with or without ; will later be refused for conversion
    const m_chr_inv = /^((&;?)+|(&#;?)+|(&#x;?)+|(U\+)+;?)$|^$/i.exec(inputString);

    // valid 'U+xxxx'
    if (m_uni) {
      const codePoint_u = parseInt(m_uni[1], 16);
      // Reject surrogates and invalid codepoints
      if ((codePoint_u >= 0xD800 && codePoint_u <= 0xDFFF) || codePoint_u > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_u);
    }

    // invalid 'U+xxxx'
    else if (m_uni_inv) {
      return undefined;
    }

    // valid '&#x...'
    else if (m_hex) {
      const codePoint_h = parseInt(m_hex[1], 16);
      // Reject surrogates and invalid codepoints
      if ((codePoint_h >= 0xD800 && codePoint_h <= 0xDFFF) || codePoint_h > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_h);
    }
    // valid '&#...'
    else if (m_dec) {
      const codePoint_d = parseInt(m_dec[1], 10);
      // Reject surrogates and invalid codepoints
      if ((codePoint_d >= 0xD800 && codePoint_d <= 0xDFFF) || codePoint_d > 0x10FFFF) {
        return undefined;
      }
      return String.fromCodePoint(codePoint_d);
    }
    // valid '&gt', '&lt',..
    else if (m_nam) {
      switch (m_nam[1].toLowerCase()) {
        case 'gt': return '>';
        case 'lt': return '<';
        case 'quot': return '"';
        case 'amp': return '&';
        case 'apos': return "'";
        default: return undefined;
      }
    }
    // invalid  '&...'
    else if (m_html_inv) {
      return undefined;
    }

    // single 'U+', '&', ''
    else if (m_chr_inv) {
      return inputString;
    }

    // if no matches so far, check for one or more characters ('a','ab', 'ẘ','😎', '😎😎',  )
    else if (m_chr) {
      return inputString;
    }
    return undefined;
  }
}
