  // KeymanKeyboardEncodings

  [
    uuid(193C6F5D-05A6-4A44-A316-636686BBB347),
    version(1.0)
  ]
  typedef enum tagKeymanKeyboardEncodings
  {
    keANSI = 1,
    keUnicode = 2
  } KeymanKeyboardEncodings;

  // KeymanKeyboardHotkey

  [
    uuid(E9ECF9BA-8101-4CF7-AF20-ED325FB0BAE6),
    version(1.0)
  ]
  typedef enum tagKeymanKeyboardHotkey
  {
    HK_ALT = 65536,
    HK_CTRL = 131072,
    HK_SHIFT = 262144
  } KeymanKeyboardHotkey;

  // KeymanPackageSubFileCopyLocation

  [
    uuid(54466B35-825D-48D9-BA7D-DE883F6893F5),
	version(1.0)
  ]
  typedef enum tagKeymanPackageSubFileCopyLocation
  {
	pfclPackage = 0,
    pfclKeymanDir = 1,
    pfclInstallTemp = 2
  } KeymanPackageSubFileCopyLocation;

  // KeymanFileType

  [
    uuid(1DC08A90-DD49-4546-950C-4F1933922112),
	version(1.0)
  ]
  typedef enum tagKeymanFileType
  {
	ftKeymanSource = 0,
	ftPackageSource = 1,
	ftKeymanFile = 2, 
	ftPackageFile = 3,
    ftPackageInstallerFile = 4, 
	ftFont = 5, 
	ftReadme = 6, 
	ftTextFile = 7, 
	ftKeymanWizard = 8, 
	ftOther = 9, 
	ftBitmap = 10,
    ftVisualKeyboard = 11, 
	ftAddinFile = 12, 
	ftCustomisation = 13
  } KeymanFileType;

/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanCollection                                                           /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(49C87E53-E98C-4E01-BA36-124A4E6E0F39),
    version(1.0),
    dual,
    oleautomation
  ]
   interface IKeymanCollection: IDispatch
  {
    [propget, id(0x00000001)]
    HRESULT _stdcall Count([out, retval] long * Value );
    [propget, id(0xFFFFFFFC), restricted]
    HRESULT _stdcall _NewEnum([out, retval] IUnknown ** Value );
    [id(0x00000002)]
    HRESULT _stdcall Refresh( void );
  };

  // KeymanCollection

  [
    uuid(D8474577-8368-4546-8897-868E33C7E8AA),
    version(1.0),
    helpstring("KeymanCollection Object"),
    noncreatable
  ]
  coclass KeymanColection
  {
    [default] interface IKeymanCollection;
  };


