  interface IKeymanCollection;

  interface ITavultesoftKeyman;

  interface IKeymanAddin;
  interface IKeymanAddins;
  interface IKeymanAddinsInstalled;

  interface IKeymanProduct;
  interface IKeymanProducts;

  interface IKeymanError;
  interface IKeymanErrors;

  interface IKeymanKeyboard;
  interface IKeymanKeyboards;
  interface IKeymanKeyboardsInstalled;
  interface IKeymanKeyboardsPackage;

  interface IKeymanLanguage;
  interface IKeymanLanguages;

  interface IKeymanLicence;
  interface IKeymanLicences;

  interface IKeymanOption;
  interface IKeymanOptions;

  interface IKeymanPackage;
  interface IKeymanPackageInstalled;
  interface IKeymanPackages;
  interface IKeymanPackagesInstalled;

  interface IKeymanPackageSubFile;
  interface IKeymanPackageSubFiles;

  interface IKeymanSystemInfo;

  interface IKeymanVisualKeyboard;

  interface IKeymanControl;
