/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanLicences : IKeymanCollection                                         /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(C6CD3AEC-7489-4242-982F-FEC9DA9213DC),
    version(1.0),
    helpstring("Dispatch interface for KeymanLicences Object"),
    dual,
    oleautomation
  ]
   interface IKeymanLicences: IKeymanCollection
  {
  };

  [
    uuid(4612D50F-3918-4C92-9A52-203DC774590E),
    version(1.0),
    helpstring("KeymanLicences Object"),
    noncreatable
  ]
  coclass KeymanLicences
  {
    [default] interface IKeymanLicences;
  };

/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanLicnce                                                               /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(A5C3DBE2-B1E2-479A-9C91-1DA7C463184A),
    version(1.0),
    helpstring("Dispatch interface for KeymanLicence Object"),
    dual,
    oleautomation
  ]
   interface IKeymanLicence: IDispatch
  {
  };

  [
    uuid(764AB68C-6746-46B2-B175-3DDD95B2BB40),
    version(1.0),
    helpstring("KeymanLicence Object"),
    noncreatable
  ]
  coclass KeymanLicence
  {
    [default] interface IKeymanLicence;
  };
