/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanLanguages : IKeymanCollection                                        /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(124FDC59-6194-4232-B54A-F251372D9B81),
    version(1.0),
    helpstring("Dispatch interface for KeymanLanguages Object"),
    dual,
    oleautomation
  ]
   interface IKeymanLanguages: IKeymanCollection
  {
    [propget, id(0x00000000), defaultcollelem, uidefault]
    HRESULT _stdcall Items([in] long Index, [out, retval] IKeymanLanguage ** Value );
    [id(0x00000005)]
    HRESULT _stdcall Apply( void );
  };

  // KeymanLanguages

  [
    uuid(581FB7B4-7341-465A-B9DF-D1CC392108A8),
    version(1.0),
    helpstring("KeymanLanguages Object")
  ]
  coclass KeymanLanguages
  {
    [default] interface IKeymanLanguages;
  };

/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanLanguage                                                             /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(785DC47F-406F-48B0-90F7-E4670B92BCF4),
    version(1.0),
    helpstring("Dispatch interface for KeymanLanguage Object"),
    dual,
    oleautomation
  ]
   interface IKeymanLanguage: IDispatch
  {
    [propget, id(0x00000001)]
    HRESULT _stdcall HKL([out, retval] long * Value );
    [propget, id(0x00000002)]
    HRESULT _stdcall KeymanKeyboard([out, retval] IKeymanKeyboard ** Value );
    [propput, id(0x00000002)]
    HRESULT _stdcall KeymanKeyboard([in] IKeymanKeyboard * Value );
    [propget, id(0x00000003)]
    HRESULT _stdcall LayoutName([out, retval] BSTR * Value );
    [propget, id(0x00000004)]
    HRESULT _stdcall Description([out, retval] BSTR * Value );
    [propget, id(0x00000006)]
    HRESULT _stdcall LocaleName([out, retval] BSTR * Value );
    [propget, id(0x00000007)]
    HRESULT _stdcall IsIME([out, retval] VARIANT_BOOL * Value );
    [propget, id(0x00000009)]
    HRESULT _stdcall IsKeymanLayout([out, retval] VARIANT_BOOL * Value );
  };

  // KeymanLanguage

  [
    uuid(EC4051FE-F508-4F89-AAE2-C78EC2355E35),
    version(1.0),
    helpstring("KeymanLanguage Object")
  ]
  coclass KeymanLanguage
  {
    [default] interface IKeymanLanguage;
  };
