/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanStatus                                                               /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(CD7E2FD7-B299-45C9-B9C6-FAC10DBF50FB),
    version(1.0),
    helpstring("Dispatch interface for KeymanStatus Object"),
    hidden,
    dual,
    oleautomation
  ]
   interface IKeymanStatus: IDispatch
  {
    [id(0x00000001)]            HRESULT _stdcall StartKeyman( void );
    [id(0x00000002)]            HRESULT _stdcall StopKeyman( void );
    [propget, id(0x00000003)]   HRESULT _stdcall Running([out, retval] long * Value );
    [propget, id(0x00000004)]   HRESULT _stdcall VisualKeyboardVisible([out, retval] long * Value );
    [id(0x00000005)]            HRESULT _stdcall StartVisualKeyboard( void );
    [id(0x00000006)]            HRESULT _stdcall StopVisualKeyboard( void );
    [propget, id(0x00000007)]   HRESULT _stdcall ActiveKeyboard([out, retval] IKeymanKeyboard ** Value );
    [id(0x00000008)]            HRESULT _stdcall Deactivate( void );
  };

  // KeymanStatus

  [
    uuid(34148E34-8C89-4FCE-9C32-10DFA743EC52),
    version(1.0),
    helpstring("KeymanStatus Object")
  ]
  coclass KeymanStatus
  {
    [default] interface IKeymanStatus;
  };
