/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanSystemInfo                                                           /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(48796430-160C-4B93-AB05-10D2548BF4D1),
    version(1.0),
    helpstring("Dispatch interface for KeymanSystemInfo Object"),
    dual,
    oleautomation
  ]
   interface IKeymanSystemInfo: IDispatch
  {
    [propget, id(0x00000001)]
    HRESULT _stdcall IsAdministrator([out, retval] VARIANT_BOOL * Value );
    [id(0x00000002)]
    HRESULT _stdcall Refresh( void );
  };

  [
    uuid(F8EAAEC3-65CF-49CD-BDD6-F43BBCA7F620),
    version(1.0),
    helpstring("KeymanSystemInfo Object"),
    noncreatable
  ]
  coclass KeymanSystemInfo
  {
    [default] interface IKeymanSystemInfo;
  };
