/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanProducts : IKeymanCollection                                         /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(4AE5C324-1553-45DA-9A42-CA8790B5DC62),
    version(1.0),
    helpstring("Dispatch interface for KeymanProducts Object"),
    hidden,
    dual,
    oleautomation
  ]
   interface IKeymanProducts: IKeymanCollection
  {
    [propget, id(0x00000000), defaultcollelem, uidefault]
                      HRESULT _stdcall Items([in] VARIANT Index, [out, retval] IKeymanProduct ** Value );
    [id(0x0000000A)]  HRESULT _stdcall Install([in] long ParentWindow, [in] BSTR FileName, [in] VARIANT_BOOL AllUsers);
    [propget, id(0x0000000B)]
                      HRESULT _stdcall ItemsByProductID([in] int Index, [out, retval] IKeymanProduct ** Value );
  };

  // KeymanProducts

  [
    uuid(102911CA-2AB7-44AE-B5B0-D9EBDAF550FC),
    version(1.0),
    helpstring("KeymanProducts Object")
  ]
  coclass KeymanProducts
  {
    [default] interface IKeymanProducts;
  };

/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanProduct                                                              /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(DE196E97-18DD-42FB-BA6E-93EFF80C0836),
    version(1.0),
    helpstring("Dispatch interface for KeymanProduct Object"),
    hidden,
    dual,
    oleautomation
  ]
   interface IKeymanProduct: IDispatch
  {
    [propget, id(0x00000001)] HRESULT _stdcall ProductID([out, retval] int * Value );
    [propget, id(0x00000002)] HRESULT _stdcall FileName([out, retval] BSTR * Value );
    [propget, id(0x00000003)] HRESULT _stdcall Name([out, retval] BSTR * Value );
    [propget, id(0x00000004)] HRESULT _stdcall Description([out, retval] BSTR * Value );
    [propget, id(0x00000005)] HRESULT _stdcall Valid([out, retval] VARIANT_BOOL * Value );
    [id(0x00000006)]          HRESULT _stdcall Uninstall( void );
    [id(0x00000007)]          HRESULT _stdcall Validate([in] long ParentWindow, [out, retval] VARIANT_BOOL * Success );
    [propget, id(0x00000008)] HRESULT _stdcall AllUsers([out, retval] VARIANT_BOOL * Value );

    [         id(0x00000009)] HRESULT _stdcall Start( void );
    [         id(0x0000000A)] HRESULT _stdcall Stop( void );
    [propget, id(0x0000000B)] HRESULT _stdcall Running([out, retval] VARIANT_BOOL * Value );
  };

  // KeymanProduct

  [
    uuid(477138A8-E1B1-4CBE-B1C2-5DC44515AB60),
    version(1.0),
    helpstring("KeymanProduct Object")
  ]
  coclass KeymanProduct
  {
    [default] interface IKeymanProduct;
  };
