/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanOptions : IKeymanCollection                                          /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(6F2CA8EE-FAD1-457D-AA9E-D14AA3321D0E),
    version(1.0),
    helpstring("Dispatch interface for KeymanOptions Object"),
    dual,
    oleautomation
  ]
   interface IKeymanOptions: IKeymanCollection
  {
    [propget, id(0x00000000), defaultcollelem]
    HRESULT _stdcall Items([in] VARIANT Index, [out, retval] IKeymanOption ** Value );
    [id(0x00000006)]
    HRESULT _stdcall Apply( void );
    [propget, id(0x00000007)]
    HRESULT _stdcall KeymanOffHotkey([out, retval] long * Value );
    [propput, id(0x00000007)]
    HRESULT _stdcall KeymanOffHotkey([in] long Value );
  };

  // KeymanOptions

  [
    uuid(0D2AF445-8CC4-4883-A300-014BA140543C),
    version(1.0),
    helpstring("KeymanOptions Object"),
    noncreatable,
    hidden
  ]
  coclass KeymanOptions
  {
    [default] interface IKeymanOptions;
  };

/*-----------------------------------------------------------------------------/
/                                                                              /
/  IKeymanOption                                                               /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(2AF26A27-C1F9-44DA-A628-B460676F3D6D),
    version(1.0),
    helpstring("Dispatch interface for KeymanOption Object"),
    hidden,
    dual,
    oleautomation
  ]
   interface IKeymanOption: IDispatch
  {
    [propget, id(0x00000001)]
    HRESULT _stdcall Value([out, retval] VARIANT_BOOL * Value );
    [propput, id(0x00000001)]
    HRESULT _stdcall Value([in] VARIANT_BOOL Value );
    [propget, id(0x00000002)]
    HRESULT _stdcall Name([out, retval] BSTR * Value );
    [propget, id(0x00000003)]
    HRESULT _stdcall Description([out, retval] BSTR * Value );
    [propget, id(0x00000004)]
    HRESULT _stdcall DefaultValue([out, retval] VARIANT_BOOL * Value );
    [propget, id(0x00000005)]
    HRESULT _stdcall Enabled([out, retval] VARIANT_BOOL * Value );
    [propget, id(0x00000006)]
    HRESULT _stdcall Group([out, retval] BSTR * Value );
  };

  // KeymanOption

  [
    uuid(3BE0825F-A5AA-4087-A314-BC33FDADA0BE),
    version(1.0),
    helpstring("KeymanOption Object"),
    noncreatable,
    hidden
  ]
  coclass KeymanOption
  {
    [default] interface IKeymanOption;
  };

