/*-----------------------------------------------------------------------------/
/                                                                              /
/  ITavultesoftKeyman                                                          /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(7B095092-9CFF-4349-AF4C-BC0684981682),
    version(1.0),
    helpstring("Interface for TavultesoftKeyman Object"),
    dual,
    oleautomation
  ]
   interface ITavultesoftKeyman: IDispatch
  {
    [         id(0x00000001)]   HRESULT _stdcall Refresh( void );
    [propget, id(0x00000002)]   HRESULT _stdcall BackgroundRefresh([out, retval] VARIANT_BOOL *Value );
    [propput, id(0x00000002)]   HRESULT _stdcall BackgroundRefresh([in] VARIANT_BOOL Value );
    [propget, id(0x00000003)]   HRESULT _stdcall Keyboards([out, retval] IKeymanKeyboardsInstalled ** Value );
    [propget, id(0x00000004)]   HRESULT _stdcall Addins([out, retval] IKeymanAddinsInstalled ** Value );
    [propget, id(0x00000005)]   HRESULT _stdcall Packages([out, retval] IKeymanPackagesInstalled ** Value );
    [propget, id(0x00000006)]   HRESULT _stdcall SystemInfo([out, retval] IKeymanSystemInfo ** Value );
    [propget, id(0x00000007)]   HRESULT _stdcall Errors([out, retval] IKeymanErrors ** Value );
    [propget, id(0x00000008)]   HRESULT _stdcall Options([out, retval] IKeymanOptions ** Value );
    [propget, id(0x00000009)]   HRESULT _stdcall Languages([out, retval] IKeymanLanguages ** Value );
    [propget, id(0x0000000A)]   HRESULT _stdcall Products([out, retval] IKeymanProducts ** Value );
    [propget, id(0x0000000B)]   HRESULT _stdcall Control([out, retval] IKeymanControl ** Value );
  };

  [
    uuid(7D8879C6-D830-4796-8021-7B6FF69558E4),
    version(1.0),
    helpstring("TavultesoftKeyman Object")
  ]
  coclass TavultesoftKeyman
  {
    [default] interface ITavultesoftKeyman;
  };


/*-----------------------------------------------------------------------------/
/                                                                              /
/  ITavultesoftKeymanController                                                /
/                                                                              /
/-----------------------------------------------------------------------------*/

  [
    uuid(ACA1CF66-F4FA-4467-AD54-E18886E7BAB5),
    version(1.0),
    helpstring("Interface for TavultesoftKeymanController Object"),
    dual,
    oleautomation
  ]
   interface ITavultesoftKeymanController: IDispatch
  {
    [         id(0x00000001)]   HRESULT _stdcall StartKeyman([in] int ProductID );
    [         id(0x00000002)]   HRESULT _stdcall StopKeyman([in] int ProductID );
  };

  [
    uuid(3288951C-A907-4411-B35D-F7FF8F2703D5),
    version(1.0),
    helpstring("TavultesoftKeymanController Object")
  ]
  coclass TavultesoftKeymanController
  {
    [default] interface ITavultesoftKeymanController;
  };




