#
# Support Makefile
#

TARGETS=oskbulkrenderer

!include ..\Header.mak

# ----------------------------------------------------------------------

oskbulkrenderer:
    cd $(ROOT)\src\support\oskbulkrenderer
    $(MAKE) $(TARGET)

!include ..\Target.mak

# ----------------------------------------------------------------------
# EOF
# ----------------------------------------------------------------------
