disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - for_where
  - function_body_length
  - function_parameter_count
  - todo
  - type_body_length

identifier_name:
  min_length:
    warning: 0
    error: 0

# allow underscore to avoid unexpected lint error in generated file in Xcode 15.3
type_name:
  allowed_symbols: "_"
