#
# jedi/jwa Makefile (Keyman project)
#

!include ..\..\Defines.mak

build: dirs
    $(MAKE) install-paths

install: install-paths

install-paths:
    $(DEVTOOLS) -ai $(EXT)\jedi\jwa\branches\2.3\Win32API

clean:
    rem

!include ..\..\Target.mak
