#!/usr/bin/env bash
## START STANDARD BUILD SCRIPT INCLUDE
# adjust relative paths as necessary
THIS_SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
. "${THIS_SCRIPT%/*}/../../../resources/build/builder-full.inc.sh"
## END STANDARD BUILD SCRIPT INCLUDE

. "$KEYMAN_ROOT/resources/build/utils.inc.sh"
. "$KEYMAN_ROOT/resources/build/node.inc.sh"

################################ Main script ################################

builder_describe "Build the include script for current Keyman version" \
  configure \
  clean \
  build \
  test

builder_describe_outputs \
  configure "/node_modules" \
  build     "/common/web/keyman-version/build/version.inc.js"

builder_parse "$@"

function do_build() {
  # Generate version.inc.ts
  echo "
// Generated by common/web/keyman-version/build.sh
//
// Note:  does not use the 'default' keyword so that the export name is
// correct when converted to a CommonJS module with \`esbuild\`.
export class KEYMAN_VERSION {
  static readonly VERSION = \"$KEYMAN_VERSION\";
  static readonly VERSION_RELEASE =\"$KEYMAN_VERSION_RELEASE\";
  static readonly VERSION_MAJOR = \"$KEYMAN_VERSION_MAJOR\";
  static readonly VERSION_MINOR = \"$KEYMAN_VERSION_MINOR\";
  static readonly VERSION_PATCH = \"$KEYMAN_VERSION_PATCH\";
  static readonly TIER =\"$KEYMAN_TIER\";
  static readonly VERSION_TAG = \"$KEYMAN_VERSION_TAG\";
  static readonly VERSION_WITH_TAG = \"$KEYMAN_VERSION_WITH_TAG\";
  static readonly VERSION_ENVIRONMENT = \"$KEYMAN_VERSION_ENVIRONMENT\";
  static readonly VERSION_GIT_TAG = \"$KEYMAN_VERSION_GIT_TAG\";
}

// Also provides it as a 'default' export.
export default KEYMAN_VERSION;
  " > ./version.inc.ts

  tsc --build $builder_verbose
}

builder_run_action clean        rm -rf version.inc.ts keyman-version.mts build/
builder_run_action configure    node_select_version_and_npm_ci
builder_run_action build        do_build
