line: contentLine|blankLine
contentLine: whitespace? content commentEnd? newline
blankLine: commentEnd? newline
commentEnd: whitespace? comment
padding: whitespace|continuationNewline
continuationNewline: whitespace? continuation whitespace? newline
content: stringSystemStoreAssign|casedkeysStoreAssign|hotkeyStoreAssign|
  variableStoreAssign
stringSystemStoreAssign: stringSystemStore padding string
stringSystemStore: store leftBracket whitespace? amphasand stringSystemStoreName whitespace? rightBracket
stringSystemStoreName: bitmap|copyright|displaymap|ethnologuecode|includecodes|
  keyboardversion|kmw_embedcss|kmw_embedjs|kmw_helpfile|kmw_helptext|kmw_rtl|
  language|layoutfile|message|mnemoniclayout|name|targets|version|
  visualkeyboard|windowslanguages
casedkeysStoreAssign: casedkeysStore paddedText+
casedkeysStore: store leftBracket whitespace? amphasand casedkeys whitespace? rightBracket
hotkeyStoreAssign: hotkeyStore padding virtualKey
hotkeyStore: store leftBracket whitespace? amphasand hotkey whitespace? rightBracket
variableStoreAssign: variableStore paddedText+
paddedText: padding text
text: textRange|simpleText
simpleText: string|virtualKey|uChar
textRange: simpleText rangeEnd+
rangeEnd: whitespace? range whitespace? simpleText
virtualKey: leftSquare whitespace? spacedShiftCode* keyCode whitespace? rightSquare
spacedShiftCode: shiftcode whitespace
variableStore: store leftBracket whitespace? variableStoreName whitespace? rightBracket
variableStoreName: parameter

anyStatement: any leftBracket whitespace? variableStoreName whitespace? rightBracket
baselayoutStatement: baselayout leftBracket whitespace? string whitespace? rightBracket
