lineBlock: multiLine|soloLine
multiLine: continuationLine+ soloLine
soloLine: contentLine|blankLine
contentLine: whitespace? content commentEnd? newline
blankLine: commentEnd? newline
continuationLine: whitespace? content whitespace continuationEnd newline
commentEnd: whitespace? comment
continationEnd: continuation whitespace?
content: systemStoreAssign
systemStoreAssign: bitmapStoreAssign|copyrightStoreAssign|includecodesStoreAssign
bitmapStoreAssign: bitmapStore whitespace string
bitmapStore: store leftBracket whitespace? amphasand bitmap whitespace? rightBracket
copyrightStoreAssign: copyrightStore whitespace string
copyrightStore: store leftBracket whitespace? amphasand copyright whitespace? rightBracket
includecodesStoreAssign: includecodesStore whitespace string
includecodesStore: store leftBracket whitespace? amphasand includecodes whitespace? rightBracket
variableStoreAssign: variableStore text+
text: string|virtualKey|uChar
virtualKey: leftSquare whitespace? spacedShiftCode* keyCode whitespace? rightSquare
spacedShiftCode: shiftcode whitespace
variableStore: store leftBracket whitespace? storeName whitespace? rightBracket
storeName: parameter