/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by Dr Mark C. Sinclair on 2025-07-04
 *
 * KMC KMN Next Generation Parser
 *
 * NodeTypes for the Recursive Descent Parser
 */

export enum NodeTypes {
  ALWAYS                = "ALWAYS",
  ANSI                  = "ANSI",
  ANY                   = "ANY",
  BASELAYOUT            = "BASELAYOUT",
  BASELAYOUT_SHORTCUT   = "BASELAYOUT_SHORTCUT",
  BEEP                  = "BEEP",
  BEGIN                 = "BEGIN",
  BITMAP                = "BITMAP",
  BITMAP_HEADER         = "BITMAP_HEADER",
  CALL                  = "CALL",
  CAPS                  = "CAPS",
  CAPSALWAYSOFF         = "CAPSALWAYSOFF",
  CAPSONONLY            = "CAPSONONLY",
  CASEDKEYS             = "CASEDKEYS",
  CLEARCONTEXT          = "CLEARCONTEXT",
  CONTEXT               = "CONTEXT",
  COPYRIGHT             = "COPYRIGHT",
  COPYRIGHT_HEADER      = "COPYRIGHT_HEADER",
  DEADKEY               = "DEADKEY",
  DECIMAL               = "DECIMAL",
  DISPLAYMAP            = "DISPLAYMAP",
  EQUAL                 = "EQUAL",
  ETHNOLOGUECODE        = "ETHNOLOGUECODE",
  FIX                   = "FIX",
  FREES                 = "FREES",
  GROUP                 = "GROUP",
  GROUPNAME             = "GROUPNAME",
  HANGUL                = "HANGUL",
  HEXADECIMAL           = "HEXADECIMAL",
  HOTKEY                = "HOTKEY",
  HOTKEY_HEADER         = "HOTKEY_HEADER",
  IF                    = "IF",
  INCLUDECODES          = "INCLUDECODES",
  INDEX                 = "INDEX",
  INPUT_CONTEXT         = "INPUT_CONTEXT",
  KEY_CODE              = "KEY_CODE",
  KEYBOARDVERSION       = "KEYBOARDVERSION",
  KEYMAN                = "KEYMAN",
  KEYMANONLY            = "KEYMANONLY",
  KEYMANWEB             = "KEYMANWEB",
  KEYS                  = "KEYS",
  KEYSTROKE             = "KEYSTROKE",
  KMFL                  = "KMFL",
  KMW_EMBEDCSS          = "KMW_EMBEDCSS",
  KMW_EMBEDJS           = "KMW_EMBEDJS",
  KMW_HELPFILE          = "KMW_HELPFILE",
  KMW_HELPTEXT          = "KMW_HELPTYEXT",
  KMW_RTL               = "KMW_RTL",
  LANGUAGE              = "LANGUAGE",
  LANGUAGE_HEADER       = "LANGUAGE_HEADER",
  LAYER                 = "LAYER",
  LAYER_SHORTCUT        = "LAYER_SHORTCUT",
  LAYOUT_HEADER         = "LAYOUT_HEADER",
  LAYOUTFILE            = "LAYOUTFILE",
  LHS                   = "LHS",
  LINE                  = "LINE",
  MATCH                 = "MATCH",
  MESSAGE               = "MESSAGE",
  MESSAGE_HEADER        = "MESSAGE_HEADER",
  MNEMONICLAYOUT        = "MNEMONICLAYOUT",
  MODIFIER              = "MODIFIER",
  NAME                  = "NAME",
  NAME_HEADER           = "NAME_HEADER",
  NAMED_CONSTANT        = "NAMED_CONSTANT",
  NEWCONTEXT            = "NEWCONTEXT",
  NEWLAYER              = "NEWLAYER",
  NOMATCH               = "NOMATCH",
  NOT_EQUAL             = "NOT_EQUAL",
  NOTANY                = "NOTANY",
  NUL                   = "NUL",
  OCTAL                 = "OCTAL",
  OFF                   = "OFF",
  OFFSET                = "OFFSET",
  OLDLAYER              = "OLDLAYER",
  ON                    = "ON",
  ONLY                  = "ONLY",
  OUTS                  = "OUTS",
  PARAMETER             = "PARAMETER",
  PLATFORM              = "PLATFORM",
  PLATFORM_SHORTCUT     = "PLATFORM_SHORTCUT",
  POSTKEYSTROKE         = "POSTKEYSTROKE",
  PRODUCTION            = "PRODUCTION",
  RANGE                 = "RANGE",
  READONLY              = "READONLY",
  RESET                 = "RESET",
  RETURN                = "RETURN",
  RHS                   = "RHS",
  SAVE                  = "SAVE",
  SET                   = "SET",
  SHIFT                 = "SHIFT",
  SHIFTFREESCAPS        = "SHIFTFREESCAPS",
  SOURCE_CODE           = "SOURCE_CODE",
  STORE                 = "STORE",
  STORENAME             = "STORENAME",
  STRING                = "STRING",
  TARGETS               = "TARGETS",
  TMP                   = "TMP",
  U_CHAR                = "U_CHAR",
  UNICODE               = "UNICODE",
  USE                   = "USE",
  USING                 = "USING",
  USING_KEYS            = "USING_KEYS",
  VERSION               = "VERSION",
  VERSION_HEADER        = "VERSION_HEADER",
  VIRTUAL_KEY           = "VIRTUAL_KEY",
  VISUALKEYBOARD        = "VISUALKEYBOARD",
  WEAVER                = "WEAVER",
  WINDOWSLANGUAGES      = "WINDOWSLANGUAGES",
}
