/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by Dr Mark C. Sinclair on 2025-07-04
 *
 * KMC KMN Next Generation Compiler
 *
 * TokenType to NodeTypes mapping for TokenRule
 */

import { NodeType } from "./node-type.js";
import { TokenType } from "./token-type.js";

export const TOKEN_TO_NODE = [
  {tokenType: TokenType.ALWAYS,              nodeType: NodeType.ALWAYS},
  {tokenType: TokenType.ANSI,                nodeType: NodeType.ANSI},
  {tokenType: TokenType.ANY,                 nodeType: NodeType.ANY},
  {tokenType: TokenType.BASELAYOUT,          nodeType: NodeType.BASELAYOUT},
  {tokenType: TokenType.BASELAYOUT_SHORTCUT, nodeType: NodeType.BASELAYOUT_SHORTCUT},
  {tokenType: TokenType.BEEP,                nodeType: NodeType.BEEP},
  {tokenType: TokenType.BEGIN,               nodeType: NodeType.BEGIN},
  {tokenType: TokenType.BITMAP,              nodeType: NodeType.BITMAP},
  {tokenType: TokenType.BITMAP_HEADER,       nodeType: NodeType.BITMAP_HEADER},
  {tokenType: TokenType.CALL,                nodeType: NodeType.CALL},
  {tokenType: TokenType.CAPS,                nodeType: NodeType.CAPS},
  {tokenType: TokenType.CAPSALWAYSOFF,       nodeType: NodeType.CAPSALWAYSOFF},
  {tokenType: TokenType.CAPSONONLY,          nodeType: NodeType.CAPSONONLY},
  {tokenType: TokenType.CASEDKEYS,           nodeType: NodeType.CASEDKEYS},
  {tokenType: TokenType.CONTEXT,             nodeType: NodeType.CONTEXT},
  {tokenType: TokenType.COPYRIGHT,           nodeType: NodeType.COPYRIGHT},
  {tokenType: TokenType.COPYRIGHT_HEADER,    nodeType: NodeType.COPYRIGHT_HEADER},
  {tokenType: TokenType.DEADKEY,             nodeType: NodeType.DEADKEY},
  {tokenType: TokenType.DECIMAL,             nodeType: NodeType.DECIMAL},
  {tokenType: TokenType.DISPLAYMAP,          nodeType: NodeType.DISPLAYMAP},
  {tokenType: TokenType.EQUAL,               nodeType: NodeType.EQUAL},
  {tokenType: TokenType.ETHNOLOGUECODE,      nodeType: NodeType.ETHNOLOGUECODE},
  {tokenType: TokenType.FREES,               nodeType: NodeType.FREES},
  {tokenType: TokenType.GROUP,               nodeType: NodeType.GROUP},
  {tokenType: TokenType.HANGUL,              nodeType: NodeType.HANGUL},
  {tokenType: TokenType.HEXADECIMAL,         nodeType: NodeType.HEXADECIMAL},
  {tokenType: TokenType.HOTKEY,              nodeType: NodeType.HOTKEY},
  {tokenType: TokenType.HOTKEY_HEADER,       nodeType: NodeType.HOTKEY_HEADER},
  {tokenType: TokenType.IF,                  nodeType: NodeType.IF},
  {tokenType: TokenType.INCLUDECODES,        nodeType: NodeType.INCLUDECODES},
  {tokenType: TokenType.INDEX,               nodeType: NodeType.INDEX},
  {tokenType: TokenType.KEYBOARDVERSION,     nodeType: NodeType.KEYBOARDVERSION},
  {tokenType: TokenType.KEYMAN,              nodeType: NodeType.KEYMAN},
  {tokenType: TokenType.KEYMANONLY,          nodeType: NodeType.KEYMANONLY},
  {tokenType: TokenType.KEYMANWEB,           nodeType: NodeType.KEYMANWEB},
  {tokenType: TokenType.KEYS,                nodeType: NodeType.KEYS},
  {tokenType: TokenType.KEY_CODE,            nodeType: NodeType.KEY_CODE},
  {tokenType: TokenType.KMFL,                nodeType: NodeType.KMFL},
  {tokenType: TokenType.KMW_EMBEDCSS,        nodeType: NodeType.KMW_EMBEDCSS},
  {tokenType: TokenType.KMW_EMBEDJS,         nodeType: NodeType.KMW_EMBEDJS},
  {tokenType: TokenType.KMW_HELPFILE,        nodeType: NodeType.KMW_HELPFILE},
  {tokenType: TokenType.KMW_HELPTEXT,        nodeType: NodeType.KMW_HELPTEXT},
  {tokenType: TokenType.KMW_RTL,             nodeType: NodeType.KMW_RTL},
  {tokenType: TokenType.LANGUAGE,            nodeType: NodeType.LANGUAGE},
  {tokenType: TokenType.LANGUAGE_HEADER,     nodeType: NodeType.LANGUAGE_HEADER},
  {tokenType: TokenType.LAYER,               nodeType: NodeType.LAYER},
  {tokenType: TokenType.LAYER_SHORTCUT,      nodeType: NodeType.LAYER_SHORTCUT},
  {tokenType: TokenType.LAYOUTFILE,          nodeType: NodeType.LAYOUTFILE},
  {tokenType: TokenType.LAYOUT_HEADER,       nodeType: NodeType.LAYOUT_HEADER},
  {tokenType: TokenType.MATCH,               nodeType: NodeType.MATCH},
  {tokenType: TokenType.MESSAGE,             nodeType: NodeType.MESSAGE},
  {tokenType: TokenType.MESSAGE_HEADER,      nodeType: NodeType.MESSAGE_HEADER},
  {tokenType: TokenType.MNEMONICLAYOUT,      nodeType: NodeType.MNEMONICLAYOUT},
  {tokenType: TokenType.MODIFIER,            nodeType: NodeType.MODIFIER},
  {tokenType: TokenType.NAME,                nodeType: NodeType.NAME},
  {tokenType: TokenType.NAMED_CONSTANT,      nodeType: NodeType.NAMED_CONSTANT},
  {tokenType: TokenType.NAME_HEADER,         nodeType: NodeType.NAME_HEADER},
  {tokenType: TokenType.NEWCONTEXT,          nodeType: NodeType.NEWCONTEXT},
  {tokenType: TokenType.NEWLAYER,            nodeType: NodeType.NEWLAYER},
  {tokenType: TokenType.NEWLINE,             nodeType: NodeType.LINE},
  {tokenType: TokenType.NOMATCH,             nodeType: NodeType.NOMATCH},
  {tokenType: TokenType.NOTANY,              nodeType: NodeType.NOTANY},
  {tokenType: TokenType.NOT_EQUAL,           nodeType: NodeType.NOT_EQUAL},
  {tokenType: TokenType.NUL,                 nodeType: NodeType.NUL},
  {tokenType: TokenType.OCTAL,               nodeType: NodeType.OCTAL},
  {tokenType: TokenType.OFF,                 nodeType: NodeType.OFF},
  {tokenType: TokenType.OLDLAYER,            nodeType: NodeType.OLDLAYER},
  {tokenType: TokenType.ON,                  nodeType: NodeType.ON},
  {tokenType: TokenType.ONLY,                nodeType: NodeType.ONLY},
  {tokenType: TokenType.OUTS,                nodeType: NodeType.OUTS},
  {tokenType: TokenType.PARAMETER,           nodeType: NodeType.PARAMETER},
  {tokenType: TokenType.PLATFORM,            nodeType: NodeType.PLATFORM},
  {tokenType: TokenType.PLATFORM_SHORTCUT,   nodeType: NodeType.PLATFORM_SHORTCUT},
  {tokenType: TokenType.POSTKEYSTROKE,       nodeType: NodeType.POSTKEYSTROKE},
  {tokenType: TokenType.READONLY,            nodeType: NodeType.READONLY},
  {tokenType: TokenType.RESET,               nodeType: NodeType.RESET},
  {tokenType: TokenType.RETURN,              nodeType: NodeType.RETURN},
  {tokenType: TokenType.SAVE,                nodeType: NodeType.SAVE},
  {tokenType: TokenType.SET,                 nodeType: NodeType.SET},
  {tokenType: TokenType.SHIFT,               nodeType: NodeType.SHIFT},
  {tokenType: TokenType.SHIFTFREESCAPS,      nodeType: NodeType.SHIFTFREESCAPS},
  {tokenType: TokenType.STORE,               nodeType: NodeType.STORE},
  {tokenType: TokenType.STRING,              nodeType: NodeType.STRING},
  {tokenType: TokenType.TARGETS,             nodeType: NodeType.TARGETS},
  {tokenType: TokenType.UNICODE,             nodeType: NodeType.UNICODE},
  {tokenType: TokenType.USE,                 nodeType: NodeType.USE},
  {tokenType: TokenType.USING,               nodeType: NodeType.USING},
  {tokenType: TokenType.U_CHAR,              nodeType: NodeType.U_CHAR},
  {tokenType: TokenType.VERSION,             nodeType: NodeType.VERSION},
  {tokenType: TokenType.VERSION_HEADER,      nodeType: NodeType.VERSION_HEADER},
  {tokenType: TokenType.VISUALKEYBOARD,      nodeType: NodeType.VISUALKEYBOARD},
  {tokenType: TokenType.WEAVER,              nodeType: NodeType.WEAVER},
  {tokenType: TokenType.WINDOWSLANGUAGES,    nodeType: NodeType.WINDOWSLANGUAGES},
];
