/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by Dr Mark C. Sinclair on 2025-07-04
 *
 * KMC KMN Next Generation Lexer
 *
 * TokenTypes for the Lexer
 */

/* These have been placed in alphabetical order for ease of access */

export enum TokenType {
  ALWAYS              = "ALWAYS",
  ANSI                = "ANSI",
  ANY                 = "ANY",
  BASELAYOUT          = "BASELAYOUT",
  BASELAYOUT_SHORTCUT = "BASELAYOUT_SHORTCUT",
  BEEP                = "BEEP",
  BEGIN               = "BEGIN",
  BITMAP              = "BITMAP",
  BITMAP_HEADER       = "BITMAP_HEADER",
  CALL                = "CALL",
  CAPS                = "CAPS",
  CAPSALWAYSOFF       = "CAPSALWAYSOFF",
  CAPSONONLY          = "CAPSONONLY",
  CASEDKEYS           = "CASEDKEYS",
  CHEVRON             = "CHEVRON",
  COMMA               = "COMMA",
  COMMENT             = "COMMENT",
  CONTEXT             = "CONTEXT",
  CONTINUATION        = "CONTINUATION",
  COPYRIGHT           = "COPYRIGHT",
  COPYRIGHT_HEADER    = "COPYRIGHT_HEADER",
  DEADKEY             = "DEADKEY",
  DECIMAL             = "DECIMAL",
  DISPLAYMAP          = "DISPLAYMAP",
  EOF                 = "EOF",
  EQUAL               = "EQUAL",
  ETHNOLOGUECODE      = "ETHNOLOGUECODE",
  FREES               = "FREES",
  GROUP               = "GROUP",
  HANGUL              = "HANGUL",
  HEXADECIMAL         = "HEXADECIMAL",
  HOTKEY              = "HOTKEY",
  HOTKEY_HEADER       = "HOTKEY_HEADER",
  IF                  = "IF",
  INCLUDECODES        = "INCLUDECODES",
  INDEX               = "INDEX",
  KEYBOARDVERSION     = "KEYBOARDVERSION",
  KEYMAN              = "KEYMAN",
  KEYMANONLY          = "KEYMANONLY",
  KEYMANWEB           = "KEYMANWEB",
  KEYS                = "KEYS",
  KEY_CODE            = "KEY_CODE",
  KMFL                = "KMFL",
  KMW_EMBEDCSS        = "KMW_EMBEDCSS",
  KMW_EMBEDJS         = "KMW_EMBEDJS",
  KMW_HELPFILE        = "KMW_HELPFILE",
  KMW_HELPTEXT        = "KMW_HELPTEXT",
  KMW_RTL             = "KMW_RTL",
  LANGUAGE            = "LANGUAGE",
  LANGUAGE_HEADER     = "LANGUAGE_HEADER",
  LAYER               = "LAYER",
  LAYER_SHORTCUT      = "LAYER_SHORTCUT",
  LAYOUTFILE          = "LAYOUTFILE",
  LAYOUT_HEADER       = "LAYOUT_HEADER",
  LEFT_BR             = "LEFT_BR",
  LEFT_SQ             = "LEFT_SQ",
  MATCH               = "MATCH",
  MESSAGE             = "MESSAGE",
  MESSAGE_HEADER      = "MESSAGE_HEADER",
  MNEMONICLAYOUT      = "MNEMONICLAYOUT",
  MODIFIER            = "MODIFIER",
  NAME                = "NAME",
  NAMED_CONSTANT      = "NAMED_CONSTANT",
  NAME_HEADER         = "NAME_HEADER",
  NEWCONTEXT          = "NEWCONTEXT",
  NEWLAYER            = "NEWLAYER",
  NEWLINE             = "NEWLINE",
  NOMATCH             = "NOMATCH",
  NOTANY              = "NOTANY",
  NOT_EQUAL           = "NOT_EQUAL",
  NUL                 = "NUL",
  OCTAL               = "OCTAL",
  OFF                 = "OFF",
  OLDCHARPOSMATCHING  = "OLDCHARPOSMATCHING",
  OLDLAYER            = "OLDLAYER",
  ON                  = "ON",
  ONLY                = "ONLY",
  OUTS                = "OUTS",
  PARAMETER           = "PARAMETER",
  PLATFORM            = "PLATFORM",
  PLATFORM_SHORTCUT   = "PLATFORM_SHORTCUT",
  PLUS                = "PLUS",
  POSTKEYSTROKE       = "POSTKEYSTROKE",
  RANGE               = "RANGE",
  READONLY            = "READONLY",
  RESET               = "RESET",
  RETURN              = "RETURN",
  RIGHT_BR            = "RIGHT_BR",
  RIGHT_SQ            = "RIGHT_SQ",
  SAVE                = "SAVE",
  SET                 = "SET",
  SHIFT               = "SHIFT",
  SHIFTFREESCAPS      = "SHIFTFREESCAPS",
  STORE               = "STORE",
  STRING              = "STRING",
  TARGETS             = "TARGETS",
  UNICODE             = "UNICODE",
  USE                 = "USE",
  USING               = "USING",
  U_CHAR              = "U_CHAR",
  VERSION             = "VERSION",
  VERSION_HEADER      = "VERSION_HEADER",
  VISUALKEYBOARD      = "VISUALKEYBOARD",
  WEAVER              = "WEAVER",
  WHITESPACE          = "WHITESPACE",
  WINDOWSLANGUAGES    = "WINDOWSLANGUAGES",
};
