/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by Dr Mark C. Sinclair on 2025-07-04
 *
 * KMC KMN Next Generation Compiler
 *
 * TokenType to NodeTypes mapping for TokenRule
 */

import { NodeTypes } from "./node-types.js";
import { TokenType } from "./token-type.js";

export const TOKEN_TO_NODE = [
  {tokenType: TokenType.ALWAYS,              nodeType: NodeTypes.ALWAYS},
  {tokenType: TokenType.ANSI,                nodeType: NodeTypes.ANSI},
  {tokenType: TokenType.ANY,                 nodeType: NodeTypes.ANY},
  {tokenType: TokenType.BASELAYOUT,          nodeType: NodeTypes.BASELAYOUT},
  {tokenType: TokenType.BASELAYOUT_SHORTCUT, nodeType: NodeTypes.BASELAYOUT_SHORTCUT},
  {tokenType: TokenType.BEEP,                nodeType: NodeTypes.BEEP},
  {tokenType: TokenType.BEGIN,               nodeType: NodeTypes.BEGIN},
  {tokenType: TokenType.BITMAP,              nodeType: NodeTypes.BITMAP},
  {tokenType: TokenType.BITMAP_HEADER,       nodeType: NodeTypes.BITMAP_HEADER},
  {tokenType: TokenType.CALL,                nodeType: NodeTypes.CALL},
  {tokenType: TokenType.CAPS,                nodeType: NodeTypes.CAPS},
  {tokenType: TokenType.CAPSALWAYSOFF,       nodeType: NodeTypes.CAPSALWAYSOFF},
  {tokenType: TokenType.CAPSONONLY,          nodeType: NodeTypes.CAPSONONLY},
  {tokenType: TokenType.CASEDKEYS,           nodeType: NodeTypes.CASEDKEYS},
  {tokenType: TokenType.CONTEXT,             nodeType: NodeTypes.CONTEXT},
  {tokenType: TokenType.COPYRIGHT,           nodeType: NodeTypes.COPYRIGHT},
  {tokenType: TokenType.COPYRIGHT_HEADER,    nodeType: NodeTypes.COPYRIGHT_HEADER},
  {tokenType: TokenType.DEADKEY,             nodeType: NodeTypes.DEADKEY},
  {tokenType: TokenType.DECIMAL,             nodeType: NodeTypes.DECIMAL},
  {tokenType: TokenType.DISPLAYMAP,          nodeType: NodeTypes.DISPLAYMAP},
  {tokenType: TokenType.EQUAL,               nodeType: NodeTypes.EQUAL},
  {tokenType: TokenType.ETHNOLOGUECODE,      nodeType: NodeTypes.ETHNOLOGUECODE},
  {tokenType: TokenType.FREES,               nodeType: NodeTypes.FREES},
  {tokenType: TokenType.GROUP,               nodeType: NodeTypes.GROUP},
  {tokenType: TokenType.HANGUL,              nodeType: NodeTypes.HANGUL},
  {tokenType: TokenType.HEXADECIMAL,         nodeType: NodeTypes.HEXADECIMAL},
  {tokenType: TokenType.HOTKEY,              nodeType: NodeTypes.HOTKEY},
  {tokenType: TokenType.HOTKEY_HEADER,       nodeType: NodeTypes.HOTKEY_HEADER},
  {tokenType: TokenType.IF,                  nodeType: NodeTypes.IF},
  {tokenType: TokenType.INCLUDECODES,        nodeType: NodeTypes.INCLUDECODES},
  {tokenType: TokenType.INDEX,               nodeType: NodeTypes.INDEX},
  {tokenType: TokenType.KEYBOARDVERSION,     nodeType: NodeTypes.KEYBOARDVERSION},
  {tokenType: TokenType.KEYMAN,              nodeType: NodeTypes.KEYMAN},
  {tokenType: TokenType.KEYMANONLY,          nodeType: NodeTypes.KEYMANONLY},
  {tokenType: TokenType.KEYMANWEB,           nodeType: NodeTypes.KEYMANWEB},
  {tokenType: TokenType.KEYS,                nodeType: NodeTypes.KEYS},
  {tokenType: TokenType.KEY_CODE,            nodeType: NodeTypes.KEY_CODE},
  {tokenType: TokenType.KMFL,                nodeType: NodeTypes.KMFL},
  {tokenType: TokenType.KMW_EMBEDCSS,        nodeType: NodeTypes.KMW_EMBEDCSS},
  {tokenType: TokenType.KMW_EMBEDJS,         nodeType: NodeTypes.KMW_EMBEDJS},
  {tokenType: TokenType.KMW_HELPFILE,        nodeType: NodeTypes.KMW_HELPFILE},
  {tokenType: TokenType.KMW_HELPTEXT,        nodeType: NodeTypes.KMW_HELPTEXT},
  {tokenType: TokenType.KMW_RTL,             nodeType: NodeTypes.KMW_RTL},
  {tokenType: TokenType.LANGUAGE,            nodeType: NodeTypes.LANGUAGE},
  {tokenType: TokenType.LANGUAGE_HEADER,     nodeType: NodeTypes.LANGUAGE_HEADER},
  {tokenType: TokenType.LAYER,               nodeType: NodeTypes.LAYER},
  {tokenType: TokenType.LAYER_SHORTCUT,      nodeType: NodeTypes.LAYER_SHORTCUT},
  {tokenType: TokenType.LAYOUTFILE,          nodeType: NodeTypes.LAYOUTFILE},
  {tokenType: TokenType.LAYOUT_HEADER,       nodeType: NodeTypes.LAYOUT_HEADER},
  {tokenType: TokenType.MATCH,               nodeType: NodeTypes.MATCH},
  {tokenType: TokenType.MESSAGE,             nodeType: NodeTypes.MESSAGE},
  {tokenType: TokenType.MESSAGE_HEADER,      nodeType: NodeTypes.MESSAGE_HEADER},
  {tokenType: TokenType.MNEMONICLAYOUT,      nodeType: NodeTypes.MNEMONICLAYOUT},
  {tokenType: TokenType.MODIFIER,            nodeType: NodeTypes.MODIFIER},
  {tokenType: TokenType.NAME,                nodeType: NodeTypes.NAME},
  {tokenType: TokenType.NAMED_CONSTANT,      nodeType: NodeTypes.NAMED_CONSTANT},
  {tokenType: TokenType.NAME_HEADER,         nodeType: NodeTypes.NAME_HEADER},
  {tokenType: TokenType.NEWCONTEXT,          nodeType: NodeTypes.NEWCONTEXT},
  {tokenType: TokenType.NEWLAYER,            nodeType: NodeTypes.NEWLAYER},
  {tokenType: TokenType.NEWLINE,             nodeType: NodeTypes.LINE},
  {tokenType: TokenType.NOMATCH,             nodeType: NodeTypes.NOMATCH},
  {tokenType: TokenType.NOTANY,              nodeType: NodeTypes.NOTANY},
  {tokenType: TokenType.NOT_EQUAL,           nodeType: NodeTypes.NOT_EQUAL},
  {tokenType: TokenType.NUL,                 nodeType: NodeTypes.NUL},
  {tokenType: TokenType.OCTAL,               nodeType: NodeTypes.OCTAL},
  {tokenType: TokenType.OFF,                 nodeType: NodeTypes.OFF},
  {tokenType: TokenType.OLDLAYER,            nodeType: NodeTypes.OLDLAYER},
  {tokenType: TokenType.ON,                  nodeType: NodeTypes.ON},
  {tokenType: TokenType.ONLY,                nodeType: NodeTypes.ONLY},
  {tokenType: TokenType.OUTS,                nodeType: NodeTypes.OUTS},
  {tokenType: TokenType.PARAMETER,           nodeType: NodeTypes.PARAMETER},
  {tokenType: TokenType.PLATFORM,            nodeType: NodeTypes.PLATFORM},
  {tokenType: TokenType.PLATFORM_SHORTCUT,   nodeType: NodeTypes.PLATFORM_SHORTCUT},
  {tokenType: TokenType.POSTKEYSTROKE,       nodeType: NodeTypes.POSTKEYSTROKE},
  {tokenType: TokenType.READONLY,            nodeType: NodeTypes.READONLY},
  {tokenType: TokenType.RESET,               nodeType: NodeTypes.RESET},
  {tokenType: TokenType.RETURN,              nodeType: NodeTypes.RETURN},
  {tokenType: TokenType.SAVE,                nodeType: NodeTypes.SAVE},
  {tokenType: TokenType.SET,                 nodeType: NodeTypes.SET},
  {tokenType: TokenType.SHIFT,               nodeType: NodeTypes.SHIFT},
  {tokenType: TokenType.SHIFTFREESCAPS,      nodeType: NodeTypes.SHIFTFREESCAPS},
  {tokenType: TokenType.STORE,               nodeType: NodeTypes.STORE},
  {tokenType: TokenType.STRING,              nodeType: NodeTypes.STRING},
  {tokenType: TokenType.TARGETS,             nodeType: NodeTypes.TARGETS},
  {tokenType: TokenType.UNICODE,             nodeType: NodeTypes.UNICODE},
  {tokenType: TokenType.USE,                 nodeType: NodeTypes.USE},
  {tokenType: TokenType.USING,               nodeType: NodeTypes.USING},
  {tokenType: TokenType.U_CHAR,              nodeType: NodeTypes.U_CHAR},
  {tokenType: TokenType.VERSION,             nodeType: NodeTypes.VERSION},
  {tokenType: TokenType.VERSION_HEADER,      nodeType: NodeTypes.VERSION_HEADER},
  {tokenType: TokenType.VISUALKEYBOARD,      nodeType: NodeTypes.VISUALKEYBOARD},
  {tokenType: TokenType.WEAVER,              nodeType: NodeTypes.WEAVER},
  {tokenType: TokenType.WINDOWSLANGUAGES,    nodeType: NodeTypes.WINDOWSLANGUAGES},
];
