/*
 * Keyman is copyright (C) SIL Global. MIT License.
 *
 * Created by S. Schmitt on 2025-05-12
 *
 * Tests for KmnFileWriter
 *
 */

import 'mocha';
import { assert } from 'chai';
import KEYMAN_VERSION from "@keymanapp/keyman-version";
import { compilerTestCallbacks, compilerTestOptions, makePathToFixture } from './helpers/index.js';
import { KeylayoutToKmnConverter, ProcessedData, Rule } from '../src/keylayout-to-kmn/keylayout-to-kmn-converter.js';
import { KmnFileWriter, UnicodeCharacterConversion, ReplacedOutputString } from '../src/keylayout-to-kmn/kmn-file-writer.js';
import { KeylayoutFileReader } from '../src/keylayout-to-kmn/keylayout-file-reader.js';
import { Keylayout } from '@keymanapp/developer-utils';

describe('KmnFileWriter', function () {

  before(function () {
    compilerTestCallbacks.clear();
  });

  describe("writeDataRules() ", function () {
    const inputFilename = makePathToFixture('../data/Test.keylayout');
    const sut = new KeylayoutToKmnConverter(compilerTestCallbacks, compilerTestOptions);
    const sutR = new KeylayoutFileReader(compilerTestCallbacks);
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    const read = sutR.read(compilerTestCallbacks.loadFile(inputFilename));
    const converted = sut.unitTestEndpoints.convert(read as Keylayout.KeylayoutXMLSourceFile, inputFilename.replace(/\.keylayout$/, '.kmn'));

    it('writeDataRules() should return true (no error) if written', async function () {
      const result = sutW.writeDataRules(converted);
      assert.isTrue(result.length > 0);
    });

  });

  describe("writeKmnFileHeader() ", function () {
    const sut = new KeylayoutToKmnConverter(compilerTestCallbacks, compilerTestOptions);
    const sutR = new KeylayoutFileReader(compilerTestCallbacks);
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    const inputFilename = makePathToFixture('../data/Test.keylayout');
    const read = sutR.read(compilerTestCallbacks.loadFile(inputFilename));
    const converted = sut.unitTestEndpoints.convert(read as Keylayout.KeylayoutXMLSourceFile, inputFilename.replace(/\.keylayout$/, '.kmn'));

    const outExpectedFirst: string =
      "c ..................................................................................................................\n"
      + "c ..................................................................................................................\n"
      + "c Keyman keyboard generated by kmn-convert version: " + KEYMAN_VERSION.VERSION + "\n"
      + "c from Ukelele file: ";

    const outExpectedLast: string =
      "\n"
      + "c ..................................................................................................................\n"
      + "c ..................................................................................................................\n"
      + "\n"
      + "store(&TARGETS) 'desktop'\n"
      + "\n"
      + "begin Unicode > use(main)\n\n"
      + "group(main) using keys\n\n"
      + "\n";

    it(('writeKmnFileHeader should return store text with filename ').padEnd(62, " ") + 'on correct input', async function () {
      const writtenCorrectName = sutW.writeKmnFileHeader(converted);
      assert.equal(writtenCorrectName, (outExpectedFirst + (converted?.keylayoutFilename ?? "") + outExpectedLast));
    });
  });

  describe('reviewRules messages', function () {
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    [
      [[new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'UNAVAILABLE', 'K_A', new TextEncoder().encode('A'))],
      [''],
      [''],
      ['c WARNING: unavailable modifier ']],

      [[new Rule("C1", '', '', 0, 0, 'CAPS', 'K_EQUAL', 0, 0, 'UNAVAILABLE', 'K_B', new TextEncoder().encode('B'))],
      [''],
      [''],
      ['c WARNING: unavailable modifier ']],

      [[new Rule("C2", '', '', 0, 0, 'CAPS', 'K_EQUAL', 0, 0, 'UNAVAILABLE', 'K_C', new TextEncoder().encode('C'),)],
      [''],
      [''],
      ['c WARNING: unavailable modifier ']],

      [[new Rule("C2", '', '', 1, 1, 'UNAVAILABLE_dk', 'K_EQUAL', 2, 2, 'UNAVAILABLE', 'K_C', new TextEncoder().encode('C'),)],
      [''],
      ['c WARNING: unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [UNAVAILABLE_dk K_EQUAL]  >  dk(A2) ) unavailable modifier ']],

      [[new Rule("C3", 'UNAVAILABLE_prev_dk', 'K_D', 1, 1, 'UNAVAILABLE_dk', 'K_EQUAL', 0, 0, 'SHIFT', 'K_C', new TextEncoder().encode('D'),)],
      ['c WARNING: unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [UNAVAILABLE_prev_dk K_D]  >  dk(A1) ) unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [UNAVAILABLE_prev_dk K_D]  >  dk(A1) ) unavailable superior rule ( dk(A1)  + [UNAVAILABLE_dk K_EQUAL]  >  dk(B0) ) ']],

      [[new Rule("C3", 'UNAVAILABLE_prev_dk', 'K_D', 0, 0, 'UNAVAILABLE_dk', 'K_EQUAL', 0, 0, 'UNAVAIL', 'K_C', new TextEncoder().encode('D'),)],
      ['c WARNING: unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [UNAVAILABLE_prev_dk K_D]  >  dk(A0) ) unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [UNAVAILABLE_prev_dk K_D]  >  dk(A0) ) unavailable superior rule ( dk(A0)  + [UNAVAILABLE_dk K_EQUAL]  >  dk(B0) ) unavailable modifier ']],

      [[new Rule("C3", 'CAPS', 'K_D', 0, 0, 'RALT', 'K_EQUAL', 0, 0, 'SHIFT', 'K_C', new TextEncoder().encode('D'),)],
      [''],
      [''],
      ['']],

      [[new Rule("C3", 'X', 'K_X', 1, 1, 'Y', 'K_Y', 0, 0, 'SHIFT', 'K_Z', new TextEncoder().encode('D'),)],
      ['c WARNING: unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [X K_X]  >  dk(A1) ) unavailable modifier '],
      ['c WARNING: unavailable superior rule ( [X K_X]  >  dk(A1) ) unavailable superior rule ( dk(A1)  + [Y K_Y]  >  dk(B0) ) ']],

    ].forEach(function (values: (string[] | Rule[])[], index: number) {
      it(('rule " ' + (values[0][0] as Rule).ruleType as string + ' "') + 'should create "' + values[1] + ' | ' + values[2] + ' | ' + values[3] + '"', async function () {
        const result: string[] = sutW.unitTestEndpoints.reviewRules(values[0] as Rule[], 0).warningMessages;
        assert.equal(result[0], values[1][0]);
        assert.equal(result[1], values[2][0]);
        assert.equal(result[2], values[3][0]);
      });
    });
  });

  describe('reviewRules messages duplicate and ambiguous', function () {
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    [
      //all
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),],
      ['c WARNING: duplicate rule earlier: [LALT K_A]  >  dk(C0) '],
      ["c WARNING: duplicate rule earlier: dk(C0) + [SHIFT K_B]  >  dk(B0) "],
      ["c WARNING: duplicate rule earlier: dk(B0) + [CAPS K_C]  >  'X' "]],

      //6-6 dup
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'CTRL', 'K_D', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),],
      [''],
      [""],
      ["c WARNING: duplicate rule earlier: dk(B0) + [CAPS K_C]  >  'X' "]],

      //6-6 amb
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'CTRL', 'K_D', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('Y')),],
      [''],
      [""],
      ["c WARNING: ambiguous rule earlier: dk(B0) + [CAPS K_C]  >  'X' "]],

      // 5-5 amb
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'NCAPS', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'NCAPS', 'K_B', 0, 1, 'RALT', 'K_F', new TextEncoder().encode('X')),],
      ['c WARNING: duplicate rule earlier: [LALT K_A]  >  dk(C0) '],
      ["c WARNING: ambiguous rule earlier: dk(C0) + [NCAPS K_B]  >  dk(B0) "], [''],
      ],

      // 5-5 dup
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'NCAPS', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'NCAPS', 'K_B', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('X')),],
      ['c WARNING: duplicate rule earlier: [LALT K_A]  >  dk(C0) '],
      ["c WARNING: duplicate rule earlier: dk(C0) + [NCAPS K_B]  >  dk(B0) "],
      ['']],

      // 4-2 amb
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'LALT', 'K_A', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('X')),],
      ['c WARNING: ambiguous rule later: [LALT K_A]  >  dk(C0) '],
      [''],
      ['']],

      // 4-4 amb
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'LALT', 'K_A', 1, 1, 'NCAPS', 'K_E', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('Y')),],
      ['c WARNING: ambiguous rule earlier: [LALT K_A]  >  dk(C0) '],
      [""],
      [''],],

      // 4-4 dup
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'NCAPS', 'K_E', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('X')),],
      ['c WARNING: duplicate rule earlier: [LALT K_A]  >  dk(C0) '],
      [''],
      ['']],

      // 4-2 amb
      [[
        new Rule("C3", 'LALT', 'K_A', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'LALT', 'K_A', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('Y')),],
      ['c WARNING: ambiguous rule later: [LALT K_A]  >  dk(C0) '],
      [''],
      ['']],

      // 6-3 dup
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'CTRL', 'K_D', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),],
      [''],
      ["c WARNING: duplicate rule earlier: dk(C0) + [CAPS K_C]  >  'X' "],
      [''],],

      // 6-3 amb
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'CTRL', 'K_D', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('Y')),],
      [''],
      ["c WARNING: ambiguous rule earlier: dk(C0) + [CAPS K_C]  >  'X' "],
      [''],],

      // 2-4 amb
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C3", 'SHIFT', 'K_B', 0, 0, 'NCAPS', 'K_E', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('Y')),],
      ['c WARNING: ambiguous rule earlier: [SHIFT K_B]  >  dk(A0) '],
      [''],
      ['']],

      //2-2 amb
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 1, 1, 'RALT', 'K_F', new TextEncoder().encode('Y')),],
      [''],
      ['c WARNING: ambiguous rule earlier: [SHIFT K_B]  >  dk(C0) '],
      ['']],

      // 2-2 dup
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'RALT', 'K_F', new TextEncoder().encode('Y')),],
      [''],
      ['c WARNING: duplicate rule earlier: [SHIFT K_B]  >  dk(C0) '],
      ['']],

      // 3-3 dup
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),],
      [''],
      [''],
      ["c WARNING: duplicate rule earlier: dk(A0) + [CAPS K_C]  >  'X' "]],

      // 3-3 amb
      [[
        new Rule("C2", '', '', 0, 0, 'SHIFT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C2", '', '', 0, 0, 'NCAPS', 'K_E', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('Y')),],
      [''],
      [''],
      ["c WARNING: ambiguous rule earlier: dk(A0) + [CAPS K_C]  >  'X' "]],

      // 2-1 amb
      [[
        new Rule("C2", '', '', 0, 0, 'RALT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'RALT', 'K_B', new TextEncoder().encode('Y'))],
      [''],
      [''],
      ['c WARNING: ambiguous rule later: [RALT K_B]  >  dk(A0) ']],

      // 1-1 amb
      [[
        new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('Y'))],
      [''],
      [''],
      ["c WARNING: ambiguous rule earlier: [CAPS K_C]  >  'X' "]],

      // 1-1 amb
      [[
        new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X')),
        new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('X'))],
      [''],
      [''],
      ["c WARNING: duplicate rule earlier: [CAPS K_C]  >  'X' "]],

    ].forEach(function (values: (string[] | Rule[])[], index: number) {
      it('rule ' + (values[0][0] as Rule).ruleType as string + ' should create " ' + ' "' + values[1] + ' | ' + values[2] + ' | ' + values[3] + '"', async function () {
        const result: string[] = sutW.unitTestEndpoints.reviewRules(values[0] as Rule[], 1).warningMessages;
        assert.equal(result[0], values[1][0]);
        assert.equal(result[1], values[2][0]);
        assert.equal(result[2], values[3][0]);
      });
    });
  });

  describe('reviewRules messages duplicate and ambiguous with Extra warning', function () {
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    [[[
      new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'RALT', 'K_B', new TextEncoder().encode('X')),
      new Rule("C2", '', '', 0, 0, 'RALT', 'K_B', 0, 0, 'CAPS', 'K_C', new TextEncoder().encode('Y')),
      new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'RALT', 'K_B', new TextEncoder().encode('Z'))
    ],
    [''],
    [''],
    ["c WARNING: ambiguous rule later: [RALT K_B]  >  dk(A0) ambiguous rule earlier: [RALT K_B]  >  'X' PLEASE CHECK THE FOLLOWING RULE AS IT WILL NOT BE WRITTEN ! "]],
    ].forEach(function (values: (string[] | Rule[])[], index: number) {
      it(('rule ' + (values[0][0] as Rule).ruleType as string + ' should create " ' + ' "') + values[1] + ' | ' + values[2] + ' | ' + values[3] + '"', async function () {
        const result: string[] = sutW.unitTestEndpoints.reviewRules(values[0] as Rule[], 2).warningMessages;
        assert.equal(result[0], values[1][0]);
        assert.equal(result[1], values[2][0]);
        assert.equal(result[2], values[3][0]);
      });
    });
  });

  describe('write from intermediate data array', function () {
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    [
      [
        [ /* see ../data/Test_C0.keylayout */
          new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'NCAPS', 'K_A', new TextEncoder().encode('a')),
          new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_A', new TextEncoder().encode('A')),
          new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'NCAPS', 'K_S', new TextEncoder().encode('s')),
          new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'NCAPS', 'K_D', new TextEncoder().encode('d'))
        ],
        ["+ [NCAPS K_A]  >  'a'\n" +
          "+ [CAPS K_A]  >  'A'\n\n" +
          "+ [NCAPS K_S]  >  's'\n\n" +
          "+ [NCAPS K_D]  >  'd'\n"]
      ],
      [
        [ /* see ../data/Test_C1.keylayout */
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'NCAPS', 'K_S', new TextEncoder().encode('s')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_S', new TextEncoder().encode('S'))
        ],
        ["+ [NCAPS K_S]  >  's'\n" +
          "+ [CAPS K_S]  >  'S'\n"]
      ],
      [
        [ /* see ../data/Test_C2.keylayout */
          new Rule("C2", '', '', 0, 0, 'NCAPS', 'K_U', 1, 1, 'CAPS', 'K_A', new TextEncoder().encode('Â'))
        ],
        ["+ [NCAPS K_U]  >  dk(A1)\n" +
          "dk(A1) + [CAPS K_A]  >  'Â'\n\n"]
      ],
      [
        [ /* see ../data/Test_C3.keylayout */
          new Rule("C3", 'NCAPS SHIFT', 'K_D', 2, 1, 'NCAPS', 'K_U', 1, 2, 'CAPS', 'K_A', new TextEncoder().encode('Â'))
        ],
        ["+ [NCAPS SHIFT K_D]   >   dk(A2)\n" +
          "dk(A2)  + [NCAPS K_U]  >  dk(B1)\n" +
          "dk(B1) + [CAPS K_A]  >  'Â'\n\n"
        ]
      ],
      [
        [ /* see ../data/Test_C0_C1_C2_C3.keylayout */
          new Rule("C0", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_A', new TextEncoder().encode('A')),
          new Rule("C2", '', '', 0, 0, 'NCAPS RALT', 'K_EQUAL', 1, 1, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_S', new TextEncoder().encode('S')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'NCAPS RALT', 'K_U', new TextEncoder().encode('S')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 1, 'CAPS', 'K_S', 2, 6, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'CAPS', 'K_U', 3, 3, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'NCAPS RALT', 'K_S', 4, 4, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'NCAPS RALT', 'K_U', 5, 5, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_S', new TextEncoder().encode('S')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'NCAPS RALT', 'K_U', new TextEncoder().encode('S')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'CAPS', 'K_S', 2, 0, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'CAPS', 'K_U', 3, 0, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'NCAPS RALT', 'K_S', 4, 0, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 6, 0, 'NCAPS RALT', 'K_U', 5, 0, 'CAPS', 'K_D', new TextEncoder().encode('Â')),
          new Rule("C1", '', '', 0, 0, '', '', 0, 0, 'CAPS', 'K_U', new TextEncoder().encode('U')),
        ],
        ["+ [CAPS K_A]  >  'A'\n" +
          "+ [CAPS K_S]  >  'S'\n\n" +
          "+ [NCAPS RALT K_U]  >  'S'\n" +
          "+ [CAPS K_U]  >  'U'\n" +
          "+ [NCAPS RALT K_EQUAL]  >  dk(A1)\n" +
          "dk(A1) + [CAPS K_D]  >  'Â'\n\n" +
          "+ [NCAPS RALT K_8]   >   dk(A6)\n" +
          "dk(A6)  + [CAPS K_S]  >  dk(B2)\n" +
          "dk(B2) + [CAPS K_D]  >  'Â'\n\n" +
          "dk(A6)  + [CAPS K_U]  >  dk(B3)\n" +
          "dk(B3) + [CAPS K_D]  >  'Â'\n\n" +
          "dk(A6)  + [NCAPS RALT K_S]  >  dk(B4)\n" +
          "dk(B4) + [CAPS K_D]  >  'Â'\n\n" +
          "dk(A6)  + [NCAPS RALT K_U]  >  dk(B5)\n" +
          "dk(B5) + [CAPS K_D]  >  'Â'\n\n"]
      ],
      [
        [ /* see ../data/Test_C3_several.keylayout */
          new Rule("C3", 'NCAPS RALT', 'K_8', 3, 1, 'CAPS', 'K_U', 1, 3, 'NCAPS', 'K_A', new TextEncoder().encode('â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 3, 0, 'CAPS', 'K_U', 1, 0, 'NCAPS RALT', 'K_A', new TextEncoder().encode('â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 3, 0, 'NCAPS RALT', 'K_U', 2, 2, 'NCAPS', 'K_A', new TextEncoder().encode('â')),
          new Rule("C3", 'NCAPS RALT', 'K_8', 3, 0, 'NCAPS RALT', 'K_U', 2, 0, 'NCAPS RALT', 'K_A', new TextEncoder().encode('â'))
        ],
        ["+ [NCAPS RALT K_8]   >   dk(A3)\n" +
          "dk(A3)  + [CAPS K_U]  >  dk(B1)\n" +
          "dk(B1) + [NCAPS K_A]  >  'â'\n\n" +
          "dk(B1) + [NCAPS RALT K_A]  >  'â'\n\n" +
          "dk(A3)  + [NCAPS RALT K_U]  >  dk(B2)\n" +
          "dk(B2) + [NCAPS K_A]  >  'â'\n\n" +
          "dk(B2) + [NCAPS RALT K_A]  >  'â'\n\n"
        ]
      ],
    ].forEach(function (values: (string[] | Rule[])[], index: number) {
      it(('an array of Rules should create a set of kmn rules '), async function () {
        const data: ProcessedData = {
          keylayoutFilename: "",
          kmnFilename: "",
          modifiers: [[]],
          rules: values[0] as Rule[]
        };
        const result1 = sutW.writeDataRules(data);
        assert.isTrue(result1 === values[1][0]);
      });
    });
  });

  describe('writeCharacterOrUnicode and return values', function () {
    const sutW = new KmnFileWriter(compilerTestCallbacks, compilerTestOptions);
    [
      ["A", "A", "Msg "],
      ["ሴ", "ሴ", "Msg "],
      ["😀", "😀", "Msg "],
      ["ẘ", "ẘ", "Msg "],
      ["U+0001", "U+0001", "Msg Use of a control character "],
      ["U+0061", "U+0061", "Msg invalid Unicode code point used "],
      ["&#x0061;", "a", "Msg "],
      ["&#x0002;", "U+0002", "Msg Use of a control character "],
      ["&#x1234;", 'ሴ', "Msg "],
      ["&#0003;", "U+0003", "Msg Use of a control character "],
      ["&#4666;", "ሺ", "Msg "],
      ["", "U+0006", "Msg Use of a control character "],
      ['', '', 'Msg empty output or unsupported numerical html entity '],
    ].forEach(function (values) {
      it(('should convert "' + values[0] + '"').padEnd(25, " ") + 'to "' + values[1] + '"', async function () {
        const result = sutW.writeCharacterOrUnicode(values[0] as string, "Msg ");
        assert.isNotNull(result);
        assert.equal(result?.character, values[1]);
        assert.equal(result?.message, values[2]);
      });
    });
  });

  describe('UnicodeCharacterConversion processXmlValue', function () {
    [
      ["", ''],
      [undefined, undefined],
      [null, undefined],

      ['<', '<'],
      ['a', 'a'],
      ['ሴ', 'ሴ'],
      ['W̊', 'W̊'],
      ['😎', '😎'],
      ['ab', 'ab'],
      ['ሴЖ', 'ሴЖ'],
      ['ẘẈ', 'ẘẈ'],
      ['😎😆', '😎😆'],
      ['aሴẘ😆', 'aሴẘ😆'],
      ['U+0061', 'U+0061'],
      ['&#x61;', 'a'],
      ['&#x1E98;', 'ẘ'],
      ['&#x0002;', '\u0002'],
      ['&#4660;', 'ሴ'],
      ['&#128518;', '😆'],
      ['&#0003;', '\u0003'],
      ['&lt;', '<'],
      ['&quot;', '"'],
      ['&apos;', "'"],
      ['␤', '␤'],
      ['␕', '␕'],
      ['', ''],
      ['U+', 'U+'],

      ['&gt;', '>'],
      ['&amp;gt', '&gt'],
      [' &amp;gt', ' &gt'],
      ['y&amp;gt', 'y&gt'],
      ['&amp;', '&'],
      ['&amp;amp;', '&'],
      ['&amp;amp;amp;', '&'],
      ['&amp;#x1234;', 'ሴ'],
      ['&amp;#x1234;&amp;', 'ሴ&'],
      ['&amp;#x&amp;#x;', '&#x&#x;'],
      ['a&gt;b', 'a>b'],
      ['a &gt; b', 'a > b'],

      ['&', '&'],
      ['&#x;', '&#x;'],
      ['&#;', '&#;'],
      ['&##;', '&##;'],

      ['&a', '&a'],
      ['a&b', 'a&b'],
      ['a&bcd&defg', 'a&bcd&defg'],
      ['a&gt', 'a&gt'],
      ['&&', '&&'],
      ['&&;', '&&;'],
      ['&#&#', '&#&#'],
      ['&#x&#x', '&#x&#x'],
      ['&#', '&#'],
      ['&#x', '&#x'],
      ['&##', '&##'],

      ['&#x10FFFF;', undefined],
      ['&#1114111;', undefined],
      ['&#x110000;', undefined],
      ['&#x0026;gt;', '>'],
      ['&#x1000000;', '&#x1000000;'],
      ['&#x2000000;', '&#x2000000;'],
      ['aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547&#x1F60F;', 'aሴ😏bẘ>😆z<y&a😎-&#128547😏'],
      ['aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547;&#x1F60F;', 'aሴ😏bẘ>😆z<y&a😎-😣😏'],

      ['&#1234;56', 'Ӓ56'],
      ['&#&#1234;56', '&#Ӓ56'],
      ['a&#&#1234;56', 'a&#Ӓ56'],
      ['&#x0026;gt', '&gt'],

      ['&#x1F60F;', '😏'],
      ['&#x1234;', 'ሴ'],
      ['&#97;', 'a'],
      ['&#7835;', 'ẛ'],
      ['&#x1F606;', '😆'],
      ['&#1000000;', '󴉀'],
      ['&gt', '&gt'],

      ['&amp;#x1234;', 'ሴ'],
      ['&#x0026;amp;#x1234;', 'ሴ'],
      ['&commat;', '&commat;'],
      ['&amp;lt;', '<'],
      ['x&amp;lt;', 'x<'],
      [' &amp;lt;', ' <'],

      ['typing a &gt;', 'typing a >'],
      ['typing a &amp;gt;', 'typing a >'],
      ['typing a amp;gt;', 'typing a amp;gt;'],
      ['typing a "&gt;"', 'typing a ">"'],
      ['typing a &amp;gt', 'typing a &gt'],

    ].forEach(function (values) {
      it(('processXmlValue should convert ' + values[0] + "'").padEnd(30, " ") + " to '" + values[1] + "'", async function () {
        const out: ReplacedOutputString = {
          input: values[0] as string,
          replaced_character: '',
          replaced_string: '',
          rest_string: values[0] as string,
          carryOver: '',
        };
        const result = UnicodeCharacterConversion.processXmlValue(out);
        assert.equal(result.replaced_string, values[1]);
      });
    });
  });

  describe('unescape_string', function () {
    [
      ['', ''],
      [undefined, undefined],
      [null, undefined],
      ['&amp;', '&'],
      ['&amp;amp;', '&'],
      ['&amp;amp;amp;', '&'],
      ['&amp;gt;', '>'],
      ['&apos;', "'"],
      ['&gt;', '>'],
      ['&GT;', '&GT;'],
      ['&Gt;', '&Gt;'],
      ['&gT;', '&gT;'],
      ['&lt;', '<'],
      ['&amp;#x1234;', '&#x1234;'],
      ['&amp;#x1234;&amp;', '&#x1234;&'],
      ['aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547;&#x1F60F;', 'aሴ&#x1F60F;bẘ>😆z<y&&#97;😎-&#128547;&#x1F60F;'],
      ['a&gt;', 'a>'],
      ['a&gt;b', 'a>b'],
      ['a &gt; b', 'a > b'],
      ["typing a '&gt;'", "typing a '>'"],
      ['typing a &gt;', 'typing a >'],
      ['typing a &amp;gt', 'typing a &gt'],
      ['a&bcd', 'a&bcd'],
      ['&', '&'],
      ['&#;', '&#;'],
      ['&#x;', '&#x;'],
      ['&##;', '&##;'],
      ['&#x110000;', '&#x110000;'],
      ['&#x2000000;', '&#x2000000;'],
      ['&#1234;56', '&#1234;56'],
      ['&#&#1234;56', '&#&#1234;56'],
      ['a&#&#1234;56', 'a&#&#1234;56'],
      ['&#x0026;gt;', '&#x0026;gt;'],
      ['&#x0026;gt', '&#x0026;gt'],
    ].forEach(function (values) {
      it(('unescape_string should unescape ' + values[0] + "'").padEnd(30, ' ') + " to '" + values[1] + "'", async function () {
        const result = UnicodeCharacterConversion.unescape_string(values[0] as string);
        assert.equal(result, values[1]);
      });
    });
  });

  describe('convert_htmlToCharacter', function () {
    [
      ["", ''],
      [undefined, undefined],
      [null, undefined],

      ['<', '<'],
      ['a', 'a'],
      ['ሴ', 'ሴ'],
      ['W̊', 'W̊'],
      ['😎', '😎'],
      ['ab', 'ab'],
      ['ሴЖ', 'ሴЖ'],
      ['ẘẈ', 'ẘẈ'],
      ['😎😆', '😎😆'],
      ['aሴẘ😆', 'aሴẘ😆'],
      ['U+0061', 'U+0061'],
      ['&#x61;', 'a'],
      ['&#x1E98;', 'ẘ'],
      ['&#x0002;', '\u0002'],
      ['&#4660;', 'ሴ'],
      ['&#128518;', '😆'],
      ['&#0003;', '\u0003'],
      ['&lt;', '&lt;'],
      ['&quot;', '&quot;'],
      ['&apos;', '&apos;'],
      ['␤', '␤'],
      ['␕', '␕'],
      ['', ''],
      ['U+', 'U+'],

      ['&gt;', '&gt;'],
      ['&amp;gt', '&amp;gt'],
      [' &amp;gt', ' &amp;gt',],
      ['y&amp;gt', 'y&amp;gt'],
      ['&amp;', '&amp;'],
      ['&amp;amp;', '&amp;amp;'],
      ['&amp;amp;amp;', '&amp;amp;amp;'],
      ['&amp;#x1234;', '&amp;#x1234;'],
      ['&amp;#x1234;&amp;', '&amp;#x1234;&amp;'],
      ['&amp;#x&amp;#x;', '&amp;#x&amp;#x;'],
      ['a&gt;b', 'a&gt;b'],
      ['a &gt; b', 'a &gt; b'],

      ['&', '&'],
      ['&#x;', '&#x;'],
      ['&#;', '&#;'],
      ['&##;', '&##;'],

      ['&a', '&a'],
      ['a&b', 'a&b'],
      ['a&bcd&defg', 'a&bcd&defg'],
      ['a&gt', 'a&gt'],
      ['&&', '&&'],
      ['&&;', '&&;'],
      ['&#&#', '&#&#'],
      ['&#x&#x', '&#x&#x'],
      ['&#', '&#'],
      ['&#x', '&#x'],
      ['&##', '&##'],

      ['&#x10FFFF;', undefined],
      ['&#1114111;', undefined],
      ['&#x110000;', undefined],
      ['&#x0026;gt;', '&#x0026;gt;'],
      ['&#x1000000;', '&#x1000000;'],
      ['&#x2000000;', '&#x2000000;'],
      ['aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547&#x1F60F;', 'aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547&#x1F60F;'],
      ['aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547;&#x1F60F;', 'aሴ&#x1F60F;bẘ&gt;😆z<y&amp;&#97;😎-&#128547;&#x1F60F;'],

      ['&#1234;56', '&#1234;56'],
      ['&#&#1234;56', '&#&#1234;56'],
      ['a&#&#1234;56', 'a&#&#1234;56'],
      ['&#x0026;gt', '&#x0026;gt'],

      ['&#x1F60F;', '😏'],
      ['&#x1234;', 'ሴ'],
      ['&#97;', 'a'],
      ['&#7835;', 'ẛ'],
      ['&#x1F606;', '😆'],
      ['&#1000000;', '󴉀'],
      ['&gt', '&gt'],

      ['&amp;#x1234;', '&amp;#x1234;'],
      ['&#x0026;amp;#x1234;', '&#x0026;amp;#x1234;'],
      ['&commat;', '&commat;'],
      ['&amp;lt;', '&amp;lt;'],
      ['x&amp;lt;', 'x&amp;lt;'],
      [' &amp;lt;', ' &amp;lt;'],

      ['typing a &gt;', 'typing a &gt;'],
      ['typing a &amp;gt;', 'typing a &amp;gt;'],
      ['typing a amp;gt;', 'typing a amp;gt;'],
      ['typing a "&gt;"', 'typing a "&gt;"'],
      ['typing a &amp;gt', 'typing a &amp;gt'],
    ].forEach(function (values) {
      it(('convert_htmlToCharacter should convert ' + values[0] + "'").padEnd(30, ' ') + " to '" + values[1] + "'", async function () {
        const result = UnicodeCharacterConversion.convert_htmlToCharacter(values[0] as string);
        assert.equal(result, values[1]);
      });
    });
  });

});
