library kmcomapi;

{ Important note about DLL memory management: ShareMem must be the
  first unit in your library's USES clause AND your project's (select
  Project-View Source) USES clause if your DLL exports any procedures or
  functions that pass strings as parameters or function results. This
  applies to all strings passed to and from your DLL--even those that
  are nested in records and classes. ShareMem is the interface unit to
  the BORLNDMM.DLL shared memory manager, which must be deployed along
  with your DLL. To avoid using BORLNDMM.DLL, pass string information
  using PChar or ShortString parameters. }

uses
  Imagehlp in '..\..\global\delphi\vcl\Imagehlp.pas',
  SysUtils,
  ComServ,
  keymanautoobject in 'util\keymanautoobject.pas',
  keyman_implementation in 'com\keyman_implementation.pas' {Keyman: CoClass},
  keymancontrol in 'com\system\keymancontrol.pas',
  keymanerror in 'com\errors\keymanerror.pas',
  keymanerrors in 'com\errors\keymanerrors.pas',
  keymanhotkey in 'com\hotkeys\keymanhotkey.pas',
  keymanhotkeys in 'com\hotkeys\keymanhotkeys.pas',
  keymankeyboard in 'com\keyboards\keymankeyboard.pas',
  keymankeyboardfile in 'com\keyboards\keymankeyboardfile.pas',
  keymankeyboardinstalled in 'com\keyboards\keymankeyboardinstalled.pas',
  keymankeyboardlanguageinstalled in 'com\keyboardlanguages\keymankeyboardlanguageinstalled.pas',
  keymankeyboardlanguagesinstalled in 'com\keyboardlanguages\keymankeyboardlanguagesinstalled.pas',
  keymankeyboardoption in 'com\keyboardoptions\keymankeyboardoption.pas',
  keymankeyboardoptions in 'com\keyboardoptions\keymankeyboardoptions.pas',
  keymankeyboardsinstalled in 'com\keyboards\keymankeyboardsinstalled.pas',
  keymanlanguage in 'com\languages\keymanlanguage.pas',
  keymanlanguages in 'com\languages\keymanlanguages.pas',
  keymanoption in 'com\options\keymanoption.pas',
  keymanoptions in 'com\options\keymanoptions.pas',
  keymanpackagecontentfile in 'com\packages\keymanpackagecontentfile.pas',
  keymanpackagecontentfiles in 'com\packages\keymanpackagecontentfiles.pas',
  keymanpackagecontentfont in 'com\packages\keymanpackagecontentfont.pas',
  keymanpackagecontentfonts in 'com\packages\keymanpackagecontentfonts.pas',
  keymanpackagecontentkeyboards in 'com\keyboards\keymanpackagecontentkeyboards.pas',
  keymanpackagefile in 'com\packages\keymanpackagefile.pas',
  keymanpackageinstalled in 'com\packages\keymanpackageinstalled.pas' {KeymanPackage: CoClass},
  keymanpackagesinstalled in 'com\packages\keymanpackagesinstalled.pas' {KeymanPackages: CoClass},
  keymansysteminfo in 'com\system\keymansysteminfo.pas' {KeymanSystemInfo: CoClass},
  keymanvisualkeyboard in 'com\keyboards\keymanvisualkeyboard.pas' {KeymanVisualKeyboard: CoClass},
  exception_keyman in 'util\exception_keyman.pas',
  isadmin in 'util\isadmin.pas',
  baseerror in 'util\baseerror.pas',
  utilkeyman in 'util\utilkeyman.pas',
  KeyNames in '..\..\..\..\common\windows\delphi\general\KeyNames.pas',
  RegistryKeys in '..\..\..\..\common\windows\delphi\general\RegistryKeys.pas',
  GetOsVersion in '..\..\..\..\common\windows\delphi\general\GetOsVersion.pas',
  RegKeyboards in '..\..\global\delphi\general\RegKeyboards.pas',
  HotkeyUtils in '..\..\global\delphi\general\HotkeyUtils.pas',
  Glossary in '..\..\..\..\common\windows\delphi\general\Glossary.pas',
  kpbase in 'processes\kpbase.pas',
  kpinstallkeyboard in 'processes\keyboard\kpinstallkeyboard.pas',
  utilunicode in 'util\utilunicode.pas',
  kpuninstallkeyboard in 'processes\keyboard\kpuninstallkeyboard.pas',
  keymancontext in 'keymancontext.pas',
  utilvararray in 'util\utilvararray.pas',
  kpinstallpackage in 'processes\package\kpinstallpackage.pas',
  kmpinffile in '..\..\..\..\common\windows\delphi\packages\kmpinffile.pas',
  PackageInfo in '..\..\..\..\common\windows\delphi\packages\PackageInfo.pas',
  PackageFileFormats in '..\..\..\..\common\windows\delphi\packages\PackageFileFormats.pas',
  ttinfo in '..\..\..\..\common\windows\delphi\general\ttinfo.pas',
  keymanerrorcodes in 'util\keymanerrorcodes.pas',
  kpuninstallpackage in 'processes\package\kpuninstallpackage.pas',
  kpinstallfont in 'processes\font\kpinstallfont.pas',
  kpuninstallfont in 'processes\font\kpuninstallfont.pas',
  utilkeymanoption in 'util\utilkeymanoption.pas',
  BitmapIPicture in '..\..\global\delphi\general\BitmapIPicture.pas',
  KPUninstallVisualKeyboard in 'processes\visualkeyboard\KPUninstallVisualKeyboard.pas',
  KPInstallVisualKeyboard in 'processes\visualkeyboard\KPInstallVisualKeyboard.pas',
  VisualKeyboard in '..\..\..\..\common\windows\delphi\visualkeyboard\VisualKeyboard.pas',
  keymancustomisation in 'com\customisation\keymancustomisation.pas',
  CustomisationMessages in '..\..\global\delphi\cust\CustomisationMessages.pas',
  CustomisationStorage in '..\..\global\delphi\cust\CustomisationStorage.pas',
  custinterfaces in '..\..\global\delphi\cust\custinterfaces.pas',
  utilkeymancontrol in 'util\utilkeymancontrol.pas',
  klog in '..\..\..\..\common\windows\delphi\general\klog.pas',
  utilfiletypes in '..\..\..\..\common\windows\delphi\general\utilfiletypes.pas',
  keymanapi_TLB in 'keymanapi_TLB.pas',
  kmxfile in '..\..\..\..\common\windows\delphi\keyboards\kmxfile.pas',
  utilhandleexception in 'util\utilhandleexception.pas',
  StockFileNames in '..\..\..\..\common\windows\delphi\general\StockFileNames.pas',
  CustomisationMenu in '..\..\global\delphi\cust\CustomisationMenu.pas',
  utilolepicture in 'util\utilolepicture.pas',
  utilxml in '..\..\..\..\common\windows\delphi\general\utilxml.pas',
  VersionInfo in '..\..\..\..\common\windows\delphi\general\VersionInfo.pas',
  extshiftstate in '..\..\..\..\common\windows\delphi\visualkeyboard\extshiftstate.pas',
  utilsystem in '..\..\..\..\common\windows\delphi\general\utilsystem.pas',
  utilstr in '..\..\..\..\common\windows\delphi\general\utilstr.pas',
  utildir in '..\..\..\..\common\windows\delphi\general\utildir.pas',
  utiltsf in '..\..\global\delphi\general\utiltsf.pas',
  MessageIdentifierConsts in '..\..\global\delphi\cust\MessageIdentifierConsts.pas',
  KeymanEngineControl in '..\..\global\delphi\general\KeymanEngineControl.pas',
  ErrorControlledRegistry in '..\..\..\..\common\windows\delphi\vcl\ErrorControlledRegistry.pas',
  kmxfileutils in '..\..\..\..\common\windows\delphi\keyboards\kmxfileutils.pas',
  kmxfileconsts in '..\..\..\..\common\windows\delphi\keyboards\kmxfileconsts.pas',
  kmxfileusedchars in '..\..\global\delphi\general\kmxfileusedchars.pas',
  kmxfileusedscripts in '..\..\global\delphi\general\kmxfileusedscripts.pas',
  UnicodeBlocks in '..\..\global\delphi\general\UnicodeBlocks.pas' { UnicodeBlock: CoClass},
  KeymanControlMessages in '..\..\global\delphi\general\KeymanControlMessages.pas',
  internalinterfaces in 'util\internalinterfaces.pas',
  VKeyChars in '..\..\..\..\common\windows\delphi\general\VKeyChars.pas',
  UserMessages in '..\..\..\..\common\windows\delphi\general\UserMessages.pas',
  DebugPaths in '..\..\..\..\common\windows\delphi\general\DebugPaths.pas',
  keyman_msctf in '..\..\global\delphi\winapi\keyman_msctf.pas',
  Unicode in '..\..\..\..\common\windows\delphi\general\Unicode.pas',
  utilexecute in '..\..\..\..\common\windows\delphi\general\utilexecute.pas',
  KeymanVersion in '..\..\..\..\common\windows\delphi\general\KeymanVersion.pas',
  kprecompilemnemonickeyboard in 'processes\keyboard\kprecompilemnemonickeyboard.pas',
  TempFileManager in '..\..\..\..\common\windows\delphi\general\TempFileManager.pas',
  input_installlayoutortip in '..\..\global\delphi\winapi\input_installlayoutortip.pas',
  KPInstallPackageStartMenu in '..\..\global\delphi\general\KPInstallPackageStartMenu.pas',
  KPUninstallPackageStartMenu in '..\..\global\delphi\general\KPUninstallPackageStartMenu.pas',
  utilwow64 in '..\..\global\delphi\general\utilwow64.pas',
  KeymanDesktopShell in '..\keyman\KeymanDesktopShell.pas',
  KeymanPaths in '..\..\..\..\common\windows\delphi\general\KeymanPaths.pas',
  KeymanMutex in '..\..\global\delphi\general\KeymanMutex.pas',
  KeymanOptionNames in '..\..\global\delphi\general\KeymanOptionNames.pas',
  VisualKeyboardLoaderBinary in '..\..\..\..\common\windows\delphi\visualkeyboard\VisualKeyboardLoaderBinary.pas',
  VisualKeyboardLoaderXML in '..\..\..\..\common\windows\delphi\visualkeyboard\VisualKeyboardLoaderXML.pas',
  VisualKeyboardSaverBinary in '..\..\..\..\common\windows\delphi\visualkeyboard\VisualKeyboardSaverBinary.pas',
  VisualKeyboardSaverXML in '..\..\..\..\common\windows\delphi\visualkeyboard\VisualKeyboardSaverXML.pas',
  VKeys in '..\..\..\..\common\windows\delphi\general\VKeys.pas',
  Windows8LanguageList in '..\..\global\delphi\general\Windows8LanguageList.pas',
  BCP47Tag in '..\..\..\..\common\windows\delphi\general\BCP47Tag.pas',
  JsonUtil in '..\..\..\..\common\windows\delphi\general\JsonUtil.pas',
  Keyman.System.LanguageCodeUtils in '..\..\..\..\common\windows\delphi\general\Keyman.System.LanguageCodeUtils.pas',
  Keyman.System.Standards.ISO6393ToBCP47Registry in '..\..\..\..\common\windows\delphi\standards\Keyman.System.Standards.ISO6393ToBCP47Registry.pas',
  Keyman.System.Standards.LCIDToBCP47Registry in '..\..\..\..\common\windows\delphi\standards\Keyman.System.Standards.LCIDToBCP47Registry.pas',
  keymankeyboardlanguage in 'com\keyboardlanguages\keymankeyboardlanguage.pas',
  keymankeyboardlanguagesfile in 'com\keyboardlanguages\keymankeyboardlanguagesfile.pas',
  keymankeyboardlanguagefile in 'com\keyboardlanguages\keymankeyboardlanguagefile.pas',
  Keyman.System.Standards.BCP47SubtagRegistry in '..\..\..\..\common\windows\delphi\standards\Keyman.System.Standards.BCP47SubtagRegistry.pas',
  Keyman.System.Standards.BCP47SuppressScriptRegistry in '..\..\..\..\common\windows\delphi\standards\Keyman.System.Standards.BCP47SuppressScriptRegistry.pas',
  Keyman.System.CanonicalLanguageCodeUtils in '..\..\..\..\common\windows\delphi\general\Keyman.System.CanonicalLanguageCodeUtils.pas',
  utilicon in '..\..\..\..\common\windows\delphi\general\utilicon.pas',
  Keyman.System.MitigateWin10_1803LanguageInstall in 'processes\keyboard\Keyman.System.MitigateWin10_1803LanguageInstall.pas',
  Keyman.System.Process.KPInstallKeyboardLanguage in 'processes\keyboard\Keyman.System.Process.KPInstallKeyboardLanguage.pas',
  Keyman.System.Process.KPUninstallKeyboardLanguage in 'processes\keyboard\Keyman.System.Process.KPUninstallKeyboardLanguage.pas',
  Keyman.System.Standards.LangTagsRegistry in '..\..\..\..\common\windows\delphi\standards\Keyman.System.Standards.LangTagsRegistry.pas',
  Keyman.System.AndroidStringToKeymanLocaleString in '..\..\..\..\common\windows\delphi\general\Keyman.System.AndroidStringToKeymanLocaleString.pas',
  Keyman.System.BaseKeyboard in 'util\Keyman.System.BaseKeyboard.pas';

{$R *.TLB}
{$R *.RES}
{$R VERSION.RES}
{$R MANIFEST.RES}

exports
  DllGetClassObject,
  DllCanUnloadNow,
  DllRegisterServer,
  DllUnregisterServer;

begin
    // I1642 move GetErrLogPath out of DllMain - causes memory issues later due to COM calls.  Now in TavultesoftKeyman:Initialize
end.


