.TH KEYMAN-SYSTEM-SERVICE "1" "May 2023" "keyman-system-service" "User Commands"
.SH NAME
keyman-system-service \- System service for Keyman
.SH DESCRIPTION
\&keyman\-system\-service
.TP
This command should not be run directly. It will be started as a DBUS
system service by systemd.
.SH "SEE ALSO"
.BR ibus-engine-keyman(1)
