program kmconvert;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  Keyman.Developer.System.KeymanConvertMain in 'Keyman.Developer.System.KeymanConvertMain.pas',
  Keyman.Developer.System.ImportWindowsKeyboard in 'Keyman.Developer.System.ImportWindowsKeyboard.pas',
  RegistryKeys in '..\..\global\delphi\general\RegistryKeys.pas',
  KeymanVersion in '..\..\global\delphi\general\KeymanVersion.pas',
  utilexecute in '..\..\global\delphi\general\utilexecute.pas',
  Keyman.Developer.System.KeyboardProjectTemplate in 'Keyman.Developer.System.KeyboardProjectTemplate.pas',
  UKeymanTargets in '..\..\global\delphi\general\UKeymanTargets.pas',
  utilstr in '..\..\global\delphi\general\utilstr.pas',
  Unicode in '..\..\global\delphi\general\Unicode.pas',
  StockFileNames in '..\..\global\delphi\cust\StockFileNames.pas',
  utilfiletypes in '..\..\global\delphi\general\utilfiletypes.pas',
  KeyboardParser in '..\TIKE\main\KeyboardParser.pas',
  kmxfile in '..\..\global\delphi\general\kmxfile.pas',
  kmxfileconsts in '..\..\global\delphi\general\kmxfileconsts.pas',
  OnlineConstants in '..\..\global\delphi\productactivation\OnlineConstants.pas',
  ExtShiftState in '..\..\global\delphi\comp\ExtShiftState.pas',
  utilsystem in '..\..\global\delphi\general\utilsystem.pas',
  VKeys in '..\..\global\delphi\general\VKeys.pas',
  WindowsLanguages in '..\..\global\delphi\general\WindowsLanguages.pas',
  GetOsVersion in '..\..\global\delphi\general\GetOsVersion.pas',
  CRC32 in '..\..\global\delphi\general\CRC32.pas',
  KeyNames in '..\..\global\delphi\general\KeyNames.pas',
  utildir in '..\..\global\delphi\general\utildir.pas',
  TextFileFormat in '..\TIKE\main\TextFileFormat.pas',
  kpsfile in '..\..\global\delphi\general\kpsfile.pas',
  PackageInfo in '..\..\global\delphi\general\PackageInfo.pas',
  JsonUtil in '..\..\global\delphi\general\JsonUtil.pas',
  VersionInfo in '..\..\global\delphi\general\VersionInfo.pas',
  PackageFileFormats in '..\..\global\delphi\general\PackageFileFormats.pas',
  ProjectLog in '..\TIKE\project\ProjectLog.pas',
  BCP47Tag in '..\..\global\delphi\general\BCP47Tag.pas',
  Keyman.System.CanonicalLanguageCodeUtils in '..\..\global\delphi\general\Keyman.System.CanonicalLanguageCodeUtils.pas',
  Keyman.System.LanguageCodeUtils in '..\..\global\delphi\general\Keyman.System.LanguageCodeUtils.pas',
  Keyman.System.KeyboardJSInfo in '..\..\global\delphi\keyboards\Keyman.System.KeyboardJSInfo.pas',
  Keyman.System.KeyboardUtils in '..\..\global\delphi\keyboards\Keyman.System.KeyboardUtils.pas',
  Keyman.System.KMXFileLanguages in '..\..\global\delphi\keyboards\Keyman.System.KMXFileLanguages.pas',
  Keyman.System.Standards.BCP47SubtagRegistry in '..\..\global\delphi\standards\Keyman.System.Standards.BCP47SubtagRegistry.pas',
  Keyman.System.Standards.BCP47SuppressScriptRegistry in '..\..\global\delphi\standards\Keyman.System.Standards.BCP47SuppressScriptRegistry.pas',
  Keyman.System.Standards.ISO6393ToBCP47Registry in '..\..\global\delphi\standards\Keyman.System.Standards.ISO6393ToBCP47Registry.pas',
  Keyman.System.Standards.LCIDToBCP47Registry in '..\..\global\delphi\standards\Keyman.System.Standards.LCIDToBCP47Registry.pas',
  Keyman.System.Standards.LibPalasoAllTagsRegistry in '..\..\global\delphi\standards\Keyman.System.Standards.LibPalasoAllTagsRegistry.pas',
  Keyman.System.RegExGroupHelperRSP19902 in '..\..\global\delphi\general\Keyman.System.RegExGroupHelperRSP19902.pas',
  Keyman.System.PackageInfoRefreshKeyboards in '..\..\global\delphi\packages\Keyman.System.PackageInfoRefreshKeyboards.pas',
  ProjectFile in '..\TIKE\project\ProjectFile.pas',
  ProjectFiles in '..\TIKE\project\ProjectFiles.pas',
  ProjectSaver in '..\TIKE\project\ProjectSaver.pas',
  ProjectFileType in '..\TIKE\project\ProjectFileType.pas',
  mrulist in '..\TIKE\main\mrulist.pas',
  ErrorControlledRegistry in '..\..\global\delphi\vcl\ErrorControlledRegistry.pas',
  TempFileManager in '..\..\global\delphi\general\TempFileManager.pas',
  klog in '..\..\global\delphi\general\klog.pas',
  compile in '..\..\global\delphi\general\compile.pas',
  RedistFiles in '..\TIKE\main\RedistFiles.pas',
  DebugPaths in '..\..\global\delphi\general\DebugPaths.pas',
  Upload_Settings in '..\..\global\delphi\general\Upload_Settings.pas',
  Project in '..\TIKE\project\Project.pas',
  ProjectLoader in '..\TIKE\project\ProjectLoader.pas',
  kmnProjectFile in '..\TIKE\project\kmnProjectFile.pas',
  kpsProjectFile in '..\TIKE\project\kpsProjectFile.pas',
  CompileKeymanWeb in '..\TIKE\compile\CompileKeymanWeb.pas',
  CompileErrorCodes in '..\..\global\delphi\general\CompileErrorCodes.pas',
  KeymanWebKeyCodes in '..\TIKE\compile\KeymanWebKeyCodes.pas',
  kmxfileutils in '..\..\global\delphi\general\kmxfileutils.pas',
  VisualKeyboard in '..\..\global\delphi\visualkeyboard\VisualKeyboard.pas',
  VKeyChars in '..\..\global\delphi\general\VKeyChars.pas',
  UnicodeData in '..\..\global\delphi\charmap\UnicodeData.pas',
  ADOX_TLB in '..\..\global\delphi\tlb\ADOX_TLB.pas',
  ADODB_TLB in '..\..\global\delphi\tlb\ADODB_TLB.pas',
  ttinfo in '..\..\global\delphi\general\ttinfo.pas',
  VisualKeyboardLoaderBinary in '..\..\global\delphi\visualkeyboard\VisualKeyboardLoaderBinary.pas',
  VisualKeyboardLoaderXML in '..\..\global\delphi\visualkeyboard\VisualKeyboardLoaderXML.pas',
  VisualKeyboardSaverBinary in '..\..\global\delphi\visualkeyboard\VisualKeyboardSaverBinary.pas',
  VisualKeyboardSaverXML in '..\..\global\delphi\visualkeyboard\VisualKeyboardSaverXML.pas',
  KeymanDeveloperOptions in '..\TIKE\main\KeymanDeveloperOptions.pas',
  CompilePackage in '..\..\global\delphi\general\CompilePackage.pas',
  CompilePackageInstaller in '..\..\global\delphi\general\CompilePackageInstaller.pas',
  kmpinffile in '..\..\global\delphi\general\kmpinffile.pas',
  UMD5Hash in '..\..\global\delphi\general\UMD5Hash.pas',
  Keyman.Developer.System.KMConvertParameters in 'Keyman.Developer.System.KMConvertParameters.pas',
  Keyman.Developer.System.ImportKeyboardDLL in 'Keyman.Developer.System.ImportKeyboardDLL.pas',
  ScanCodeMap in '..\..\global\delphi\general\ScanCodeMap.pas',
  Keyman.Developer.System.TouchLayoutToVisualKeyboardConverter in 'Keyman.Developer.System.TouchLayoutToVisualKeyboardConverter.pas',
  OnScreenKeyboardData in '..\..\global\delphi\visualkeyboard\OnScreenKeyboardData.pas',
  TouchLayout in '..\TIKE\oskbuilder\TouchLayout.pas',
  TouchLayoutDefinitions in '..\TIKE\oskbuilder\TouchLayoutDefinitions.pas',
  TouchLayoutUtils in '..\TIKE\oskbuilder\TouchLayoutUtils.pas',
  KeyboardFonts in '..\..\global\delphi\general\KeyboardFonts.pas',
  Keyman.System.Util.RenderLanguageIcon in '..\..\global\delphi\ui\Keyman.System.Util.RenderLanguageIcon.pas',
  utilicon in '..\..\global\delphi\general\utilicon.pas',
  ResourceStrings in '..\..\global\delphi\general\ResourceStrings.pas';

{$R icons.RES}
{$R version.res}
{$R manifest.res}

begin
  try
    Run;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
