.TH kmflcomp "1" "February 2009" "kmflcomp 0.9.8"
.SH NAME
kmflcomp \- keyboard mapping for linux compiler
.SH SYNOPSIS
.B kmflcomp \-v
.br
.BR kmflcomp " [" \-d "]" 
.RB "[" \-f "]"
.RB "[" \-V "]" 
.RB \fIkeyboardfile\fR
.br
.B kmflcomp \-h
.SH DESCRIPTION
KMFL is a keyboard input method project which brings Tavultesoft Keyman functionality to *nix operating systems.
.PP
kmflcomp is the keyboard compiler and syntax checker for the kmfl project. The files created by kmflcomp can be loaded by the kmfl libraries to provide input methods to clients.
.PP
Note that the kmfl libraries now have the capability to compile kmfl keyboards on the fly so kmflcomp is no longer strictly necessary. The most useful part of kmflcomp is its kmfl keyboard syntax checking.
.SH OPTIONS
.TP
.BR \fB\-d\fR
Output debugging information
.TP
.BR \fB\-f\fR
Force compilation even if there are errors found in the keyboard file
.TP
.BR \fB\-h\fR
Print this help message
.TP
.BR \fB\-V\fR
Be more verbose in kmfcomp's information messages
.TP
.BR \fB\-v\fR
Print program version
.SH "SEE ALSO"
The full documentation for
.B kmflcomp
can be found on the kmfl website (kmfl.sourceforge.net).
This includes documentation for the kmfl language syntax, useful for creating new keyboards, or modifying existing keyboards.
.SH AUTHORS
KMFL was developed jointly by SIL international(www.sil.org) and Tavultesoft(www.tavultesoft.com). The primary authors are John Durdin and Doug Rintoul.
