[DESCRIPTION]
Keyman makes it possible for you to type in over 1,000 languages on Windows,
macOS, iPhone, iPad, Android tablets and phones, and even instantly in your web browser.
Soon it will work on Linux and similar systems as well.

With the world's most powerful keyboarding engine, intuitive and rapid text input is now 
possible in your language, and for over 99% of the global population's mother tongues!

keyman-config shows the currently installed Keyman keyboard packages and allows you to
view information about them. It enables you to download new keyboard packages from
the website or install from local files.

[SEE ALSO]
install_kmp(1)
list_installed_kmp(1)
uninstall_kmp(1)
