[<DESCRIPTION]
Keyman makes it possible for you to type in over 2,500 languages on Windows, Linux,
macOS, iPhone, iPad, Android tablets and phones, and even instantly in your web browser.

With the world's most powerful keyboarding engine, intuitive and rapid text input is now
possible in your language, and for over 99% of the global population's mother tongues!

[SEE ALSO]
km-package-install(1)
km-package-list-installed(1)
km-package-uninstall(1)
