[TAB COMPLETION]

You may use tab completion to find keyboard packages to install.
The list comes from the network so there may be a small delay before
tab completion will work the first time you use it.
The list of packages is cached for one week.

The list is the full list including keyboards that do not work on
Linux, so they won't necessarily install.

[SEE ALSO]
km-config(1)
km-package-list-installed(1)
km-package-uninstall(1)
