# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'
use_frameworks!

target 'Keyman' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Keyman
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.24.0'
  
  target 'KeymanTests' do
    inherit! :search_paths
    pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.24.0'
    use_frameworks!
    # Pods for testing
  end

end
