# Uncomment the next line to define a global platform for your project
platform :osx, '10.7'

target 'Keyman' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Keyman
  pod 'Fabric'
  pod 'Crashlytics'

  target 'KeymanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
