#
# Samples Makefile
#

TARGETS=imsample
!include ..\..\Header.mak

imsample:
    cd $(ROOT)\src\developer\samples\imsample
    $(MAKE) $(TARGET)

# ----------------------------------------------------------------------
# EOF
# ----------------------------------------------------------------------
