#!groovy
// Copyright (c) 2019-2021 SIL International
// This software is licensed under the MIT license (http://opensource.org/licenses/MIT)

@Library('lsdev-pipeline-library') _

keymanPackaging {
	distributionsToPackage = 'bionic focal groovy hirsute'
	arches = 'amd64 i386'
}
