name: build-binary-packages
description: |
  Build binary packages
inputs:
  dist:
    description: 'dist to build binary packages for'
    required: true
  arch:
    description: 'the architecture'
    required: false
    default: 'amd64'
  version:
    description: 'The Keyman version'
    required: true
  prerelease_tag:
    description: 'The prerelease tag'
    required: true
  deb_fullname:
    description: 'The full name used for the packages'
    required: true
  deb_email:
    description: 'The email address used for the packages'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: keyman-srcpkg
        path: artifacts/keyman-srcpkg

    - name: Build
      uses: sillsdev/gha-ubuntu-packaging@b619077451b27c16dc6fd699bc1daf8d5ce07659 # v1.2
      with:
        dist: "${{ inputs.dist }}"
        platform: "${{ inputs.arch }}"
        source_dir: "artifacts/keyman-srcpkg"
        sourcepackage: "keyman_${{ inputs.version }}-1.dsc"
        deb_fullname: ${{inputs.deb_fullname}}
        deb_email: ${{inputs.deb_email}}
        prerelease_tag: ${{ inputs.prerelease_tag }}

    - name: Output resulting .deb files
      shell: bash
      run: |
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "$(find artifacts/ -name \*.deb)" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Store binary packages
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: keyman-binarypkgs-${{ inputs.dist }}_${{ inputs.arch }}
        path: |
          artifacts/*
          !artifacts/keyman-srcpkg/
      if: always()
