#
# DcpCrypt Makefile (Tavultesoft)
#

!include ..\..\Defines.mak

build: install

install:
    $(DEVTOOLS) -ai $(COMMON_ROOT)\ext\dcpcrypt

clean: def-clean
    $(CLEAN) *.bpl
    $(CLEAN) *.dcp

!include ..\..\Target.mak
