/***
   KeymanWeb 2.0
   Copyright 2014 Tavultesoft Pty Ltd

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
***/

window['dfltLayout'] = {
	"desktop":
		{
		"font":"Tahoma,Helvetica",
		"layer":[
			{	
				"id":"default",
				"row":[
					{
						"id":"1",
						"key":[
							{"id":"K_BKQUOTE"},
							{"id":"K_1"},
							{"id":"K_2"},
							{"id":"K_3"},
							{"id":"K_4"},
							{"id":"K_5"},
							{"id":"K_6"},
							{"id":"K_7"},
							{"id":"K_8"},
							{"id":"K_9"},
							{"id":"K_0"},
							{"id":"K_HYPHEN"},
							{"id":"K_EQUAL"},
      				{"id":"K_BKSP","text":"*BkSp*","sp":"1","width":"130"}
							]
					},
					{
						"id":"2",
						"key":[
      				{"id":"K_TAB","text":"*Tab*","sp":"1","width":"130"},
							{"id":"K_Q"},
							{"id":"K_W"},
							{"id":"K_E"},
							{"id":"K_R"},
							{"id":"K_T"},
							{"id":"K_Y"},
							{"id":"K_U"},
							{"id":"K_I"},
							{"id":"K_O"},
							{"id":"K_P"},
							{"id":"K_LBRKT"},
							{"id":"K_RBRKT"},
							{"id":"K_BKSLASH"}
							]
					},
					{
						"id":"3",
						"key":[
      				{"id":"K_CAPS","text":"*Caps*","sp":"1","width":"165"},
							{"id":"K_A"},
							{"id":"K_S"},
							{"id":"K_D"},
							{"id":"K_F"},
							{"id":"K_G"},
							{"id":"K_H"},
							{"id":"K_J"},
							{"id":"K_K"},
							{"id":"K_L"},
							{"id":"K_COLON"},
							{"id":"K_QUOTE"},
      				{"id":"K_ENTER","text":"*Enter*","sp":"1","width":"165"}
							]
					},
					{
						"id":"4",
						"key":[
      				{"id":"K_SHIFT","text":"*Shift*","sp":"1","width":"130"},
							{"id":"K_oE2"},
							{"id":"K_Z"},
							{"id":"K_X"},
							{"id":"K_C"},
							{"id":"K_V"},
							{"id":"K_B"},
							{"id":"K_N"},
							{"id":"K_M"},
							{"id":"K_COMMA"},
							{"id":"K_PERIOD"},
							{"id":"K_SLASH"},
      				{"id":"K_RSHIFT","text":"*Shift*","sp":"1","width":"130"}
							]
					},
					{
						"id":"5",
						"key":[
      				{"id":"K_LCONTROL","text":"*Ctrl*","sp":"1","width":"170"},
      				{"id":"K_LALT","text":"*Alt*","sp":"1","width":"160"},
							{"id":"K_SPACE","text":"","width":"770"},
      				{"id":"K_ALT","text":"*Alt*","sp":"1","width":"160"},
      				{"id":"K_RCONTROL","text":"*Ctrl*","sp":"1","width":"170"}
							]
					}
					]
			}      
			]
		},
	"tablet":
		{
		"font":"Tahoma,Helvetica",
		"layer":[
			{	
				"id":"default",
				"row":[
				  {
						"id":"0",
            "key":[
							{"id":"K_1"},
							{"id":"K_2"},
							{"id":"K_3"},
							{"id":"K_4"},
							{"id":"K_5"},
							{"id":"K_6"},
							{"id":"K_7"},
							{"id":"K_8"},
							{"id":"K_9"},
							{"id":"K_0"},
							{"id":"K_HYPHEN"},
							{"id":"K_EQUAL"},
							{"sp":"10","width":"1"}
              ]				  
				  },
					{
						"id":"1",
						"key":[
							{"id":"K_Q","pad":"25"},
							{"id":"K_W"},
							{"id":"K_E"},
							{"id":"K_R"},
							{"id":"K_T"},
							{"id":"K_Y"},
							{"id":"K_U"},
							{"id":"K_I"},
							{"id":"K_O"},
							{"id":"K_P"},
							{"id":"K_LBRKT"},
							{"id":"K_RBRKT"},
							{"sp":"10","width":"1"}
							]
					},
					{
						"id":"2",
						"key":[
							{"id":"K_A","pad":"50"},
							{"id":"K_S"},
							{"id":"K_D"},
							{"id":"K_F"},
							{"id":"K_G"},
							{"id":"K_H"},
							{"id":"K_J"},
							{"id":"K_K"},
							{"id":"K_L"},
							{"id":"K_COLON"}, 
							{"id":"K_QUOTE"},
							{"id":"K_BKSLASH","width":"90"}
							]
					},
					{
						"id":"3",
						"key":[
						  {"id":"K_oE2","width":"90"},
							{"id":"K_Z"},
							{"id":"K_X"},
							{"id":"K_C"},
							{"id":"K_V"},
							{"id":"K_B"},
							{"id":"K_N"},
							{"id":"K_M"},
							{"id":"K_COMMA"},
							{"id":"K_PERIOD"},
							{"id":"K_SLASH"},
							{"id":"K_BKQUOTE"},
							{"sp":"10","width":"1"}							
							]
					},
					{
						"id":"4",
						"key":[
      				{"id":"K_SHIFT","text":"*Shift*","sp":"1","width":"200","sk":[
                {"id":"K_LCONTROL","text":"*Ctrl*","sp":"1","width":"50","nextlayer":"ctrl"},
                {"id":"K_LALT","text":"*Alt*","sp":"1","width":"50","nextlayer":"alt"},
                {"id":"K_ALTGR","text":"*AltGr*","sp":"1","width":"50","nextlayer":"ctrlalt"}]
              },
      				{"id":"K_LOPT","text":"*Menu*","sp":"1","width":"150"},
							{"id":"K_SPACE","text":"","width":"570"},
      				{"id":"K_BKSP","text":"*BkSp*","sp":"1","width":"150"},
      				{"id":"K_ENTER","text":"*Enter*","sp":"1","width":"200"}
							]
					}
					]
			}                                          
			]
		},
	"phone":
		{
		"font":"Tahoma,Helvetica",
		"layer":[
			{	
				"id":"default",
				"row":[
				  {
						"id":"0",
            "key":[
							{"id":"K_1"},
							{"id":"K_2"},
							{"id":"K_3"},
							{"id":"K_4"},
							{"id":"K_5"},
							{"id":"K_6"},
							{"id":"K_7"},
							{"id":"K_8"},
							{"id":"K_9"},
							{"id":"K_0"},
							{"id":"K_HYPHEN"},
							{"id":"K_EQUAL"},
							{"sp":"10","width":"1"}
              ]				  
				  },
					{
						"id":"1",
						"key":[
							{"id":"K_Q","pad":"25"},
							{"id":"K_W"},
							{"id":"K_E"},
							{"id":"K_R"},
							{"id":"K_T"},
							{"id":"K_Y"},
							{"id":"K_U"},
							{"id":"K_I"},
							{"id":"K_O"},
							{"id":"K_P"},
							{"id":"K_LBRKT"},
							{"id":"K_RBRKT"},
							{"sp":"10","width":"1"}
							]
					},
					{
						"id":"2",
						"key":[
							{"id":"K_A","pad":"50"},
							{"id":"K_S"},
							{"id":"K_D"},
							{"id":"K_F"},
							{"id":"K_G"},
							{"id":"K_H"},
							{"id":"K_J"},
							{"id":"K_K"},
							{"id":"K_L"},
							{"id":"K_COLON"}, 
							{"id":"K_QUOTE"},
							{"id":"K_BKSLASH","width":"90"}
							]
					},
					{
						"id":"3",
						"key":[
						  {"id":"K_oE2","width":"90"},
							{"id":"K_Z"},
							{"id":"K_X"},
							{"id":"K_C"},
							{"id":"K_V"},
							{"id":"K_B"},
							{"id":"K_N"},
							{"id":"K_M"},
							{"id":"K_COMMA"},
							{"id":"K_PERIOD"},
							{"id":"K_SLASH"},
							{"id":"K_BKQUOTE"},
							{"sp":"10","width":"1"}							
							]
					},
					{
						"id":"4",
						"key":[
      				{"id":"K_SHIFT","text":"*Shift*","sp":"1","width":"200","sk":[
                {"id":"K_LCONTROL","text":"*Ctrl*","sp":"1","width":"50","nextlayer":"ctrl"},
                {"id":"K_LALT","text":"*Alt*","sp":"1","width":"50","nextlayer":"alt"},
                {"id":"K_ALTGR","text":"*AltGr*","sp":"1","width":"50","nextlayer":"ctrlalt"}]
              },
      				{"id":"K_LOPT","text":"*Menu*","width":"150","sp":"1"},
							{"id":"K_SPACE","width":"570","text":""},
      				{"id":"K_BKSP","text":"*BkSp*","width":"150","sp":"1"},
      				{"id":"K_ENTER","text":"*Enter*","width":"200","sp":"1"}
							]
					}
					]
			}                                          
			]
		}
	};

