#
# Samples Makefile
#

TARGETS=imsample
!include ..\Header.mak

imsample: .virtual
    cd $(DEVELOPER_ROOT)\src\samples\imsample
    $(MAKE) $(TARGET)

!include ..\Target.mak

# ----------------------------------------------------------------------
# EOF
# ----------------------------------------------------------------------
