#
# Samples Makefile
#

TARGETS=imsample
!include ..\..\Header.mak

imsample: .virtual
    cd $(ROOT)\src\developer\samples\imsample
    $(MAKE) $(TARGET)

!include ..\..\Target.mak

# ----------------------------------------------------------------------
# EOF
# ----------------------------------------------------------------------
