#!/usr/bin/env bash
# 
# Copyright:        Copyright (C) 2022-2025 SIL International.
# Authors:          srl295
# This file provides constants for the KMX Plus (LDML support) binary format,
# to be shared between TypeScript, C++, and shell via the generator (below)
# 
# Generated File - do not edit
# 
# This file is generated by core/tools/ldml-const-builder/build.sh
# based on core/include/ldml/keyman_core_ldml.ts
# 

LDML_CLDR_IMPLIED_FORMS_IMPORT="46/scanCodes-implied.xml"
LDML_CLDR_IMPLIED_KEYS_IMPORT="46/keys-Latn-implied.xml"
LDML_CLDR_IMPORT_BASE="cldr"
LDML_CLDR_TEST_VERSION_LATEST="techpreview"
LDML_CLDR_VERSION_LATEST="46"
LDML_LAYR_LIST_HARDWARE_TOUCH="touch"
LDML_VERSION="1.0"
