#
# jedi/jwa Makefile (Keyman project)
#

!include ..\..\Defines.mak

build: install-paths
install: install-paths

install-paths:
    $(DEVTOOLS) -ai $(COMMON_ROOT)\ext\jwa\Win32API

clean:
    rem

!include ..\..\Target.mak
